### ISSUE TITLE
Crash when switching from Bishop bible program back to AndBible

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1060]
Raised here: https://support.andbible.org/scp/tickets.php?id=508

![image](https://user-images.githubusercontent.com/13920678/118352590-a789f680-b5a5-11eb-8b54-c8b37cbc64b9.png)

```
--------- beginning of crash
05-11 17:55:53.092  3686  3686 E AndroidRuntime: FATAL EXCEPTION: main
05-11 17:55:53.092  3686  3686 E AndroidRuntime: Process: net.bible.android.activity, PID: 3686
05-11 17:55:53.092  3686  3686 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property dedicatedLinksWindow has not been initialized
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at net.bible.android.control.page.window.WindowRepository.getDedicatedLinksWindow(WindowRepository.kt:137)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at net.bible.android.control.page.window.WindowControl.defaultBibleDoc(WindowControl.kt:97)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at net.bible.android.control.bookmark.BookmarkControl.addText$app_release(BookmarkControl.kt:291)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at net.bible.android.view.activity.bookmark.BookmarkItemAdapter.getView(BookmarkItemAdapter.kt:54)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:3189)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2197)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.ListView.fillSpecific(ListView.java:1522)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1914)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2961)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.View.layout(View.java:20854)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2961)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2648)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-11 17:55:53.092  3686  3686 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by tuomas2** [comment]
Has anyone been able to reproduce this?

**Comment by tuomas2** [comment]
Only once happened to original reporter too.

**Comment by timbze** [comment]
> Only once happened to original reporter too. 

My guess is it has nothing to do with switching from Bishop.

Should check play store to see if this crash has happened more often.

**Comment by tuomas2** [comment]
also this https://support.andbible.org/scp/tickets.php?id=626

**Comment by timbze** [comment]
Outdated
