### ISSUE TITLE
Crash after speak button pressed on studypad

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1063]
Originally raised here: https://support.andbible.org/scp/tickets.php?id=475

![image](https://user-images.githubusercontent.com/13920678/118352973-aeb20400-b5a7-11eb-8e54-6f09c08b0059.png)

```
--------- beginning of crash
04-26 09:47:26.969  8721  8721 E AndroidRuntime: FATAL EXCEPTION: main
04-26 09:47:26.969  8721  8721 E AndroidRuntime: Process: net.bible.android.activity, PID: 8721
04-26 09:47:26.969  8721  8721 E AndroidRuntime: net.bible.service.common.AndRuntimeException: Error preparing Speech
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.control.speak.SpeakControl.toggleSpeak(SpeakControl.kt:237)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity$setupToolbarButtons$$inlined$apply$lambda$3.onClick(MainBibleActivity.kt:550)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.view.View.performClick(View.java:7869)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7838)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.view.View.access$3600(View.java:886)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:29362)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: Caused by: net.bible.service.common.AndRuntimeException: Error preparing Speech
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.control.speak.SpeakControl.speakText(SpeakControl.kt:282)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.control.speak.SpeakControl.toggleSpeak(SpeakControl.kt:232)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	... 12 more
04-26 09:47:26.969  8721  8721 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.control.page.CachedKeyPage.getKeyPlus(CachedKeyPage.kt:95)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageBase.getPagePlus(CurrentPageBase.kt:119)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	at net.bible.android.control.speak.SpeakControl.speakText(SpeakControl.kt:270)
04-26 09:47:26.969  8721  8721 E AndroidRuntime: 	... 13 more

```

**Comment by tuomas2** [comment]
In general I think it might not be good to post users automatically generated screenshots here especially if they contain user notes for security and trust reasons. It's okay to post my screenshots though.. but I think it's sufficient to have link to osticket so developers can look there for additional info :-)

**Comment by agrogers** [comment]
No problems. Will do.

**Comment by bvahedy** [comment]
Unable to duplicate this in 522.2 build.
