### ISSUE TITLE
Crash in bookmarks view added label to a bookmark

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1065]
Raised here: https://support.andbible.org/scp/tickets.php?id=483
And Bible version: 3.4.518-beta#9ad2dd683 (built 01/05/21 09:04:57)

![image](https://user-images.githubusercontent.com/13920678/118354420-57636200-b5ae-11eb-8ced-3ebe8d63f115.png)

```
--------- beginning of crash
04-30 20:41:59.091 25854 25854 E AndroidRuntime: FATAL EXCEPTION: main
04-30 20:41:59.091 25854 25854 E AndroidRuntime: Process: net.bible.android.activity, PID: 25854
04-30 20:41:59.091 25854 25854 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.RuntimeException: MainBibleActivity was attempted to be created second time! This would cause issues so let's crash!
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5763)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5671)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: Caused by: java.lang.RuntimeException: MainBibleActivity was attempted to be created second time! This would cause issues so let's crash!
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:202)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7957)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7946)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
04-30 20:41:59.091 25854 25854 E AndroidRuntime: 	... 13 more
```

**Comment by tuomas2** [comment]
Thanks for digging the crash report. 
This time it reveals to me that this issue has been fixed.
