### ISSUE TITLE
Crash when creating a new bookmark with auto-assigning labels

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1108]
Reported here by me: https://support.andbible.org/scp/tickets.php?id=534

1. Chose a new label to be automatically assigned to new bookmarks via clicking on the coloured icon 
2. Then added a new bookmark 
3. Crash 

```
--------- beginning of crash
05-29 07:29:20.075 20673 20673 E AndroidRuntime: FATAL EXCEPTION: main
05-29 07:29:20.075 20673 20673 E AndroidRuntime: Process: net.bible.android.activity, PID: 20673
05-29 07:29:20.075 20673 20673 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.database.bookmarks.BookmarkDao_Impl.insert(BookmarkDao_Impl.java:400)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.control.bookmark.BookmarkControl.addOrUpdateBookmark(BookmarkControl.kt:105)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.makeBookmark(BibleView.kt:252)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.makeBookmark$default(BibleView.kt:237)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.onActionMenuItemClicked(BibleView.kt:206)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.access$onActionMenuItemClicked(BibleView.kt:132)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$ActionModeCallback2.onActionItemClicked(BibleView.kt:380)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2659)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:98)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:123)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:442)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.view.View.performClick(View.java:7307)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7284)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.view.View.access$3600(View.java:821)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28059)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7592)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
05-29 07:29:20.075 20673 20673 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
05-29 07:29:20.091 20673 20673 D OOMEventManagerFK: checkEventAndDumpForJE: 0
05-29 07:29:20.981 20673 20673 I Process : Sending signal. PID: 20673 SIG: 9
05-29 07:29:33.218 15452 15452 E ndroid.activit: Unknown bits set in runtime_flags: 0x40000

```

**Comment by tuomas2** [comment]
This was fixed in latest build
