### ISSUE TITLE
Crash when clicking desktop widget

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1212]
https://support.andbible.org/scp/tickets.php?id=614

```
06-30 18:41:16.604 25676 25676 E AndroidRuntime: FATAL EXCEPTION: main
06-30 18:41:16.604 25676 25676 E AndroidRuntime: Process: net.bible.android.activity, PID: 25676
06-30 18:41:16.604 25676 25676 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=92, result=0, data=null} to activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.NullPointerException
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3796)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:280)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6706)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=92, result=0, data=null} to activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.NullPointerException
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3785)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	... 11 more
06-30 18:41:16.604 25676 25676 E AndroidRuntime: Caused by: java.lang.NullPointerException
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onActivityResult(MainBibleActivity.kt:1320)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4375)
06-30 18:41:16.604 25676 25676 E AndroidRuntime: 	... 12 more
```

**Comment by tuomas2** [comment]
probably this too: https://support.andbible.org/scp/tickets.php?id=620

(though not happening via widget, but could be same bug)

**Comment by tuomas2** [comment]
I'm quite sure we'll get these in production in bigger numbers, but difficult to fix before we know how to reproduce.

**Comment by timbze** [comment]
Change this
```kotlin
TEXT_DISPLAY_SETTINGS_CHANGED -> {
                val extras = data?.extras!!
```

to this?
```kotlin
TEXT_DISPLAY_SETTINGS_CHANGED -> {
                val extras = data?.extras ?: return
```

**Comment by tuomas2** [comment]
when is it needed?

**Comment by timbze** [comment]
I think after returning from text display settings activity, but not on my Linux right now to check definitely.

The bug is weird, but regardless, when `data.extras` is null it should not throw error. We've already changed some before to do a null check because there are situations where it is null.

**Comment by timbze** [comment]
> Change this
> 
> ```kotlin
> TEXT_DISPLAY_SETTINGS_CHANGED -> {
>                 val extras = data?.extras!!
> ```
> 
> to this?
> 
> ```kotlin
> TEXT_DISPLAY_SETTINGS_CHANGED -> {
>                 val extras = data?.extras ?: return
> ```

Better yet would be to run the check at the start of method, something like `val extras = data?.extras ?: return`

EDIT: actually no, because last case check doesn't even use extras

**Comment by timbze** [comment]
Though #1342 should fix the crash, if widget is passing some data to AB then that might still need to be fixed
