### ISSUE TITLE
DatabaseNotReady crash

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1362]
From https://support.andbible.org/scp/tickets.php?id=640

**Describe the bug**
DatabaseNotReady crash

**Bug was found on And Bible version**
Build 4.0.534-beta#b4c52b7 (built 17/07/21 20:32:47)

Relevant log:
```
07-18 01:02:22.462  6344  6344 E AndroidRuntime: FATAL EXCEPTION: main
07-18 01:02:22.462  6344  6344 E AndroidRuntime: Process: net.bible.android.activity, PID: 6344
07-18 01:02:22.462  6344  6344 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.navigation.GridChoosePassageBook}: net.bible.service.common.DataBaseNotReady
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3322)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3471)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7592)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: Caused by: net.bible.service.common.DataBaseNotReady
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.getSettings(CommonUtils.kt:260)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at net.bible.android.view.activity.navigation.GridChoosePassageBook.onCreate(GridChoosePassageBook.kt:141)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7916)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7903)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
07-18 01:02:22.462  6344  6344 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
```

**Comment by tuomas2** [comment]
Should be fixed in 50e51875031b23e6f74000740cf33cfd58beaf49
