### ISSUE TITLE
Restore backup does not migrate database

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#155]
Further the extra column causes errors after restore of previous backups. I get:

```
android.database.sqlite.SQLiteException: no such column: speak_settings (code 1)
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
at net.bible.service.db.bookmark.BookmarkDBAdapter.getAllBookmarks(BookmarkDBAdapter.java:150)
at net.bible.android.control.bookmark.BookmarkControl.getBookmarksWithLabel(BookmarkControl.java:305)
at net.bible.android.view.activity.bookmark.Bookmarks.loadBookmarkList(Bookmarks.java:201)
```

**Comment by tuomas2** [comment]
Hmm. Could not reproduce this. Tried this in emulator:
 - Install and start last stable version (249) 
 - Create some bookmarks
 - Backup bookmarks
 - Uninstall
 - Start latest version 
 - Restore from backup
 - Go to bookmark listing, create new bookmarks, etc.

-> no failure.
 
@mjdenham Do you remember more precisely what did you do to produce this error? 
Do you have a specific database that fails when restoring?

**Comment by tuomas2** [comment]
Now could reproduce it (with android 26) in emulator.
