### ISSUE TITLE
"MainBibleActivity was created second time" crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1591]
https://support.andbible.org/scp/tickets.php?id=694

**Comment by tuomas2** [comment]
Waiting for user to answer questions.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=850 too

**Comment by timbze** [comment]
v612

https://support.andbible.org/scp/tickets.php?id=911

**Comment by tuomas2** [comment]
> v612
> 
> https://support.andbible.org/scp/tickets.php?id=911

Screenshot indicates that this happens already in app startup

**Comment by tuomas2** [comment]
Not really. He was in main bible view and then suddenly somehow StartupActivity appears again and tries to start MainBibleActivity again.

Interesting log lines:

```
10-12 23:57:33.717  8433  8433 I StartupActivity: onDestroy:net.bible.android.activity.StartupActivity@b915813
10-12 23:57:33.734  8433  8433 E WindowManager: 
10-12 23:57:33.734  8433  8433 E WindowManager: android.view.WindowLeaked: Activity net.bible.android.activity.StartupActivity has leaked window DecorView@7a6e18c[] that was originally added here
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:499)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:390)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.app.Dialog.show(Dialog.java:360)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.app.AlertDialog$Builder.show(AlertDialog.java:1193)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity.checkWebView(StartupActivity.kt:175)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity.access$checkWebView(StartupActivity.kt:75)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity$postBasicInitialisationControl$2.invokeSuspend(StartupActivity.kt:212)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity$postBasicInitialisationControl$2.invoke(Unknown Source:8)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity$postBasicInitialisationControl$2.invoke(Unknown Source:4)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity.postBasicInitialisationControl(StartupActivity.kt:211)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity.access$postBasicInitialisationControl(StartupActivity.kt:75)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at net.bible.android.view.activity.StartupActivity$onCreate$1$1.invokeSuspend(StartupActivity.kt:199)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:790)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.os.Looper.loop(Looper.java:164)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6661)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-12 23:57:33.734  8433  8433 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tuomas2** [comment]
MainBibleActivity has received Keycode:4 (back key) which has started StartupActivity. Normally this closes app but for some reason here it goes "back" to StartupActivity. 

```
10-12 23:57:33.499  8433  8433 D MainBibleActivity: Keycode:4
10-12 23:57:33.533  8433  8433 I net.bible.android.view.activity.page.MainBibleActivity: onPause:net.bible.android.view.activity.page.MainBibleActivity@3da915e
10-12 23:57:33.561  8433  8433 I StartupActivity: onRestart:net.bible.android.activity.StartupActivity@b915813
10-12 23:57:33.573  8433  8433 I StartupActivity: onStart:net.bible.android.activity.StartupActivity@b915813
10-12 23:57:33.576  8433  8433 I StartupActivity: onResume:net.bible.android.activity.StartupActivity@b915813
10-12 23:57:33.579  8433  8433 D BibleView[3]: Focus changed so start/stop scroll false
10-12 23:57:33.649  8433  8433 I StartupActivity: onPause:net.bible.android.activity.StartupActivity@b915813
10-12 23:57:33.650  8433  8433 E ActivityBase: closeKeyboard: java.lang.NullPointerException
10-12 23:57:33.655  8433  8433 I StartupActivity: onStop:net.bible.android.activity.StartupActivity@b915813
```

This has happened on Android 8.1. Should try if it reproduces.

**Comment by tuomas2** [comment]
Though at this point I can conclude that this is not as critical issue as I thought.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1234 (From me)

From what I am seeing is that:
1. I'm using And Bible. I'm not sure if I have used UI because I often listen to bible using only widget on that device.
2. Leaving it on background. Possibly last action is text to speech which is stopped.
3. Forgetting it there for some time (probably multiple days, it's from my Android 9 phone and it's not my main bible device)
4. Opening it again either (probably from widget, but not sure about that, but with an intention to use UI this time for sure)
-> report of past crash pops up.

Log shows that crash has happened 8:47 and I'm trying to use UI 9:08 same day. Log does not show much more about the incident.

**Comment by tuomas2** [comment]
On android 9 (API 28) and lower (tested also API 27) this seem to be very reproducible:
1. Add both launcher button and AB widget to your home screen
2. Press launcher
3. go back to home screen
4. press back of the widget
-> crash

Can't reproduce on API 30 / 31 / 29 emulators.

**Comment by tuomas2** [comment]
Solution was found here: https://stackoverflow.com/a/34328608/1343995
