### ISSUE TITLE
Crash when installing only HunIMIT at install time

### ISSUE THREAD

**Issue by krisek** [AndBible/and-bible#1593]
**Describe the bug**
Application crashes once modules have been downloaded.

**Bug was found on And Bible version**
Build beta-541.4 or version 4.0.541-beta

**To Reproduce**
1. Open the app for the first time
2. Download desired modules
3. Application crashes

**Expected behavior**
Application doesn't crash

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Pixel5
 - OS: Android
 - Version: 11

**Additional context**
n/a

**Comment by krisek** [comment]
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/7003226/logcat.txt.gz)

**Comment by krisek** [comment]
Interestingly, if I download only one module at app initialization, it gets through. And if I download all desired modules only afterwards, it doesn't crash anymore.

**Comment by tuomas2** [comment]
Thank you for reporting this!

```
08-17 23:33:19.767 27320 27320 E AndroidRuntime: Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Too many parts to the Verse. (Parts are separated by any of Joh.3.16-Joh.3.18, Joh, 3, 16)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.buildVersePartsException(AccuracyType.java:493)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:480)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:398)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at org.crosswire.jsword.passage.VerseRangeFactory.fromText(VerseRangeFactory.java:117)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:90)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:55)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.getDefaultVerse(CommonUtils.kt:913)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageManager.setFirstUseDefaultVerse(CurrentPageManager.kt:279)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at net.bible.android.control.page.window.WindowRepository.initialize(WindowRepository.kt:118)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.initializeApp(CommonUtils.kt:884)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at net.bible.android.view.activity.base.ActivityBase.onCreate(ActivityBase.kt:89)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:213)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7994)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7978)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-17 23:33:19.767 27320 27320 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
```

**Comment by tuomas2** [comment]
What modules did you have installed when crash happened?

**Comment by tuomas2** [comment]
Probably HunIMIT (#1594), what else?

**Comment by krisek** [comment]
> Probably HunIMIT (#1594), what else?

Yes, I've checked now, HunIMIT is the trigger.

If I select solely HunIMIT, the crash happens. With the remaining modules it is all good.

**Comment by krisek** [comment]
[logcat-imit.txt.gz](https://github.com/AndBible/and-bible/files/7005083/logcat-imit.txt.gz)
