### ISSUE TITLE
Crash when trying to add bookmark in other workspace. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1659]
Using beta build 543.11
Ref ticket: https://support.andbible.org/scp/tickets.php?id=727

When in a different workspace other than the one at the top of my workspace list. Crash happened everytime I tried to select either a verse or a portion of the verse to create a bookmark.

**Comment by tuomas2** [comment]
```
08-30 20:50:36.433 20124 20124 E AndroidRuntime: FATAL EXCEPTION: main
08-30 20:50:36.433 20124 20124 E AndroidRuntime: Process: net.bible.android.activity, PID: 20124
08-30 20:50:36.433 20124 20124 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:1217)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.database.bookmarks.BookmarkDao_Impl.insert(BookmarkDao_Impl.java:428)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.control.bookmark.BookmarkControl.addOrUpdateBookmark(BookmarkControl.kt:106)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.makeBookmark(BibleView.kt:323)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.makeBookmark$default(BibleView.kt:305)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.onActionMenuItemClicked(BibleView.kt:273)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.access$onActionMenuItemClicked(BibleView.kt:183)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$ActionModeCallback2.onActionItemClicked(BibleView.kt:495)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:3857)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:157)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:127)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:477)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
08-30 20:50:36.433 20124 20124 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by tuomas2** [comment]
Root cause: Label has been removed but it's id is still in this workspaces settings.
