### ISSUE TITLE
Search / Find crashes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1724]
https://support.andbible.org/scp/tickets.php?id=763

**Comment by tuomas2** [comment]
```
09-19 01:41:34.775 20818 20818 E AndroidRuntime: FATAL EXCEPTION: main
09-19 01:41:34.775 20818 20818 E AndroidRuntime: Process: net.bible.android.activity, PID: 20818
09-19 01:41:34.775 20818 20818 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at android.view.View.performClick(View.java:5197)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:20926)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5942)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	... 10 more
09-19 01:41:34.775 20818 20818 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.crosswire.jsword.index.query.QueryDecorator.decorateAllWords(java.lang.String)' on a null object reference
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at org.crosswire.jsword.index.search.SearchType$2.decorate(SearchType.java:48)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at net.bible.android.control.search.SearchControl.decorateSearchString(SearchControl.kt:108)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search.decorateSearchString(Search.kt:231)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search.onSearch(Search.kt:213)
09-19 01:41:34.775 20818 20818 E AndroidRuntime: 	... 13 more

```

**Comment by tuomas2** [comment]
here too https://support.andbible.org/scp/tickets.php?id=771

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=772

**Comment by tuomas2** [comment]
The actual issue that leads to this is this:

```
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: create QueryDecorator failed [QueryDecoratorFactory:<clinit>:69] Thread[main,5,main]
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: java.lang.ClassNotFoundException: Didn't find class "org.crosswire.jsword.index.lucene.LuceneQueryDecorator" on path: DexPathList[[zip file "/data/app/com.google.android.webview-1/base.apk", zip file "/data/app/com.google.android.webview-1/split_config.en.apk", zip file "/data/app/com.google.android.webview-1/split_weblayer.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-1/lib/arm, /vendor/lib, /system/lib]]
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at org.crosswire.common.util.ClassUtil.forName(ClassUtil.java:53)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at org.crosswire.common.util.PluginUtil.getImplementor(PluginUtil.java:151)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at org.crosswire.common.util.PluginUtil.getImplementation(PluginUtil.java:180)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at org.crosswire.jsword.index.query.QueryDecoratorFactory.<clinit>(QueryDecoratorFactory.java:65)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at org.crosswire.jsword.index.query.QueryDecoratorFactory.getSearchSyntax(QueryDecoratorFactory.java:47)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at org.crosswire.jsword.index.search.SearchType.<clinit>(SearchType.java:147)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at net.bible.android.view.activity.search.Search.getSearchType(Search.kt:69)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at net.bible.android.view.activity.search.Search.decorateSearchString(Search.kt:231)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at net.bible.android.view.activity.search.Search.onSearch(Search.kt:213)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at java.lang.reflect.Method.invoke(Method.java:372)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at android.view.View.performClick(View.java:5197)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at android.view.View$PerformClick.run(View.java:20926)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at android.os.Handler.handleCallback(Handler.java:739)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at android.os.Looper.loop(Looper.java:145)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at android.app.ActivityThread.main(ActivityThread.java:5942)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at java.lang.reflect.Method.invoke(Method.java:372)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 	Suppressed: java.io.IOException: Zip archive '/data/app/com.google.android.webview-1/split_config.en.apk' doesn't contain classes.dex (error msg: Entry not found)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexFile.<init>(DexFile.java:80)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexFile.<init>(DexFile.java:59)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:262)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.DexPathList.<init>(DexPathList.java:109)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:120)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:45)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:415)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.app.ContextImpl.getClassLoader(ContextImpl.java:1223)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:142)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.getFactory(WebView.java:2193)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.view.View.<init>(View.java:3792)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.view.View.<init>(View.java:3915)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.view.ViewGroup.<init>(ViewGroup.java:507)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.<init>(WebView.java:547)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.<init>(WebView.java:492)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.<init>(WebView.java:475)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.<init>(WebView.java:462)
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: 		at android.webkit.WebView.<init
09-20 09:59:14.111 23630 23630 D AndroidRuntime: Shutting down VM
```

**Comment by tuomas2** [comment]
This happens only with app installed from play store.

**Comment by tuomas2** [comment]
And seemingly not always even there.

**Comment by tuomas2** [comment]
Maybe only with Android 5?

**Comment by tuomas2** [comment]
On emulator (android 5) also find index creatiion fails. Looks similar:

```
09-20 21:03:26.406 5476-5476/net.bible.android.activity.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.bible.android.activity.debug, PID: 5476
    java.lang.NullPointerException: Attempt to invoke interface method 'org.crosswire.jsword.index.IndexStatus org.crosswire.jsword.book.Book.getIndexStatus()' on a null object reference
        at net.bible.android.view.activity.search.SearchIndexProgressStatus.jobFinished(SearchIndexProgressStatus.java:68)
        at net.bible.android.view.activity.base.ProgressActivityBase.updateProgress(ProgressActivityBase.kt:117)
        at net.bible.android.view.activity.base.ProgressActivityBase$initialiseView$uiUpdaterRunnable$1.run(ProgressActivityBase.kt:73)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

(after looking a little there was something weird on emulator, so it is not after all similar case, I guess). The module that it tried to index was not installed.

**Comment by tuomas2** [comment]
Can't reproduce on emulator (android 5), even though I use apk backed up from app installed via Google Play.

**Comment by tuomas2** [comment]
All reports are from single user. Continuing investigating later, but maybe this is not *so* critical after all.

**Comment by tuomas2** [comment]
from log it looks like it's somehow confused about the package in which to search class.

```
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: create QueryDecorator failed [QueryDecoratorFactory:<clinit>:69] Thread[main,5,main]
09-20 09:59:14.111 23630 23630 E Slf4jAndroidLogger: java.lang.ClassNotFoundException: Didn't find class "org.crosswire.jsword.index.lucene.LuceneQueryDecorator" on path: DexPathList[[zip file "/data/app/com.google.android.webview-1/base.apk", zip file "/data/app/com.google.android.webview-1/split_config.en.apk", zip file "/data/app/com.google.android.webview-1/split_weblayer.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-1/lib/arm, /vendor/lib, /system/lib]]

```

It is looking for it in *webview* apks. That's wrong!

**Comment by tuomas2** [comment]
Another instance of this: https://support.andbible.org/scp/tickets.php?id=875

**Comment by timbze** [comment]
Another, also android 5
https://support.andbible.org/scp/tickets.php?id=1233
