### ISSUE TITLE
Crash (Unique constraint failed: DocumentBackup.osisId)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1755]
https://support.andbible.org/scp/tickets.php?id=795

**Comment by tuomas2** [comment]
```
09-22 20:46:30.819 13812 13838 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
09-22 20:46:30.819 13812 13838 E AndroidRuntime: Process: net.bible.android.activity, PID: 13812
09-22 20:46:30.819 13812 13838 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DocumentBackup.osisId (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:97)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at net.bible.android.database.SwordDocumentInfoDao_Impl.insert(SwordDocumentInfoDao_Impl.java:131)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.checkDocBackupDBInSync(MainBibleActivity.kt:343)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.access$checkDocBackupDBInSync(MainBibleActivity.kt:134)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity$onCreate$5.invokeSuspend(MainBibleActivity.kt:322)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
09-22 20:46:30.819 13812 13838 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=805

**Comment by tuomas2** [comment]
Still happening. https://support.andbible.org/scp/tickets.php?id=834

**Comment by tuomas2** [comment]
New incident looks like user has had this issue earlier (25.9) but then upgraded and now there is no new crash on 28.9. I'm asking user if the app is crashing still, or did it just report the crash one time just before upgrade.

**Comment by tuomas2** [comment]
User reported that no longer happening so my theory is true.
