### ISSUE TITLE
Crash in showStableNotice

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1760]
```
--------- beginning of crash
09-23 23:29:34.840  3598  3598 E AndroidRuntime: FATAL EXCEPTION: main
09-23 23:29:34.840  3598  3598 E AndroidRuntime: Process: net.bible.android.activity, PID: 3598
09-23 23:29:34.840  3598  3598 E AndroidRuntime: java.lang.IllegalStateException: Already resumed
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity$showStableNotice$$inlined$suspendCoroutine$lambda$1.onClick(MainBibleActivity.kt:432)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:225)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7563)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
09-23 23:29:34.840  3598  3598 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
09-23 23:29:35.262  3598  3598 W BpBinder: Slow Binder: BpBinder transact took 326 ms, interface=miui.mqsas.IMQSService, code=6 oneway=false
09-23 23:29:36.381  3598  3598 I Process : Sending signal. PID: 3598 SIG: 9

```

https://support.andbible.org/scp/tickets.php?id=801

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1018
