### ISSUE TITLE
Crash in reading plans (onDone)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1771]
https://support.andbible.org/scp/tickets.php?id=839

```
09-30 07:03:13.741 26118 26118 E AndroidRuntime: java.lang.NoClassDefFoundError: org.apache.commons.lang3.Validate$$ExternalSyntheticLambda0
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at org.apache.commons.lang3.time.DateUtils.validateDateNotNull(DateUtils.java:1789)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at org.apache.commons.lang3.time.DateUtils.truncate(DateUtils.java:813)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.getTruncatedDate(CommonUtils.kt:319)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.control.readingplan.ReadingPlanControl.getDueDay(ReadingPlanControl.kt:187)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.control.readingplan.ReadingPlanControl.isDueToBeRead(ReadingPlanControl.kt:257)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.control.readingplan.ReadingPlanControl.done(ReadingPlanControl.kt:247)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.view.activity.readingplan.DailyReading.onDone(DailyReading.kt:233)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.view.activity.readingplan.DailyReading.onCreate$lambda-1$lambda-0(DailyReading.kt:113)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.view.activity.readingplan.DailyReading.$r8$lambda$x0u48VL5apVeUuKxakaU2N8m8pM(DailyReading.kt)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at net.bible.android.view.activity.readingplan.DailyReading$$ExternalSyntheticLambda2.onClick(Unknown Source)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.view.View.performClick(View.java:5698)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:10908)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22557)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7231)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-30 07:03:13.741 26118 26118 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Device info:
And Bible version: 4.0.608#fa7acf841 (built 27/09/21 09:22:38)
Android version: 6.0.1
Android SDK version: 23
Manufacturer: samsung
Model: SM-J510FN
Storage Mb free: 590
WebView version: 94.0.4606.61
SQLITE version: 3.8.10.2

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=870

Device info:
And Bible version: 4.0.608#fa7acf841 (built 27/09/21 09:22:38)
Android version: 6.0.1
Android SDK version: 23
Manufacturer: samsung
Model: SM-J500Y
Storage Mb free: 439
WebView version: 92.0.4515.131
SQLITE version: 3.8.10.2

**Comment by tuomas2** [comment]
Can see from screenshot that this crash also takes place in Reading Plan https://support.andbible.org/scp/tickets.php?id=872. But logcat does not report actual crash...

And Bible version: 4.0.608#fa7acf841 (built 27/09/21 09:22:38)
Android version: 5.1
Android SDK version: 22
Manufacturer: HUAWEI
Model: HUAWEI LUA-U22
Storage Mb free: 156
WebView version: 94.0.4606.61
SQLITE version: 3.8.6.1
Used heap memory in Mb: 15
Max heap memory in Mb: 128
