### ISSUE TITLE
Change workspace font size causes a crash.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1776]
> Multi view loaded in preconfigured workspaces. In "compare" window, touching to change workspace font size causes a crash.

```
09-26 11:48:46.078  1956  1956 E AndroidRuntime: FATAL EXCEPTION: main
09-26 11:48:46.078  1956  1956 E AndroidRuntime: Process: net.bible.android.activity, PID: 1956
09-26 11:48:46.078  1956  1956 E AndroidRuntime: java.lang.RuntimeException: Font asset not found /storage/emulated/0/Android/data/net.bible.android.activity/files/./modules/texts/ztext/FontPack/and-bible/SBL_Grk.ttf
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.graphics.Typeface.createFromFile(Typeface.java:998)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.util.widget.FontSizeWidgetKt.getTypeFace(FontSizeWidget.kt:75)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.util.widget.FontSizeWidget.updateValue(FontSizeWidget.kt:133)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.util.widget.FontSizeWidget$Companion.dialog(FontSizeWidget.kt:143)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.activity.page.FontSizePreference.openDialog(OptionsMenuItems.kt:330)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea.handlePrefItem(SplitBibleArea.kt:651)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea.access$handlePrefItem(SplitBibleArea.kt:105)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea$showPopupMenu$1.onMenuItemClick(SplitBibleArea.kt:667)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4116)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-26 11:48:46.078  1956  1956 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=812
