### ISSUE TITLE
Crash: OOM in replaceDocument

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1777]
https://support.andbible.org/scp/tickets.php?id=842

```
09-30 13:18:48.959 16863 16888 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 10957776 byte allocation with 4181040 free bytes and 4083KB until OOM, target footprint 100663296, growth limit 100663296
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at java.lang.StringBuilder.<init>(StringBuilder.java:102)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at kotlin.text.StringsKt__IndentKt.replaceIndent(Indent.kt:118)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at kotlin.text.StringsKt__IndentKt.trimIndent(Indent.kt:63)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at kotlin.text.StringsKt.trimIndent(Unknown Source:0)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.replaceDocument(BibleView.kt:1082)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.access$replaceDocument(BibleView.kt:182)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$loadDocument$4.invokeSuspend(BibleView.kt:974)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7604)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-30 13:18:48.959 16863 16888 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by tuomas2** [comment]
Can't allocate 10 megabytes of ram. 

1. Why 10 megabytes? (why such a large document)
2. Why it crashes? Mobile phones have plenty of memory these days?

**Comment by tuomas2** [comment]
Trimming indentation is not at all necessary (can also slow down) so let's remove that first of all...

**Comment by tuomas2** [comment]
I have asked user which do and which verse does it crash, waiting for answer to that still.
