### ISSUE TITLE
Parsing error in bible view

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1778]
Gill Ps 84:0 (or 84:1)

https://support.andbible.org/scp/tickets.php?id=843
```

10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: Parsing error
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.jdom2.Element.getContent()' on a null object reference
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.service.sword.SwordContentFacade.readXmlTextStandardJSwordMethod(SwordContentFacade.kt:101)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.service.sword.SwordContentFacade.readOsisFragment(SwordContentFacade.kt:89)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.CurrentPageBase.getPageContent(CurrentPageBase.kt:137)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.CurrentPageBase.getCurrentPageContent(CurrentPageBase.kt:126)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.CurrentCommentaryPage.getCurrentPageContent(CurrentCommentaryPage.kt:79)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invokeSuspend(Window.kt:236)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:8)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:4)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.window.Window.fetchDocument(Window.kt:231)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.window.Window.access$fetchDocument(Window.kt:46)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at net.bible.android.control.page.window.Window$updateText$1.invokeSuspend(Window.kt:188)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-01 06:43:16.144 26562 30024 E net.bible.service.sword.SwordContentFacade: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-01 06:43:16.145 26562 30024 E CurrentPage: Error getting bible text

10-01 06:43:16.145 26562 30024 E CurrentPage: Error getting bible text
10-01 06:43:16.145 26562 30024 E CurrentPage: net.bible.service.common.ParseException: Parsing error
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.service.sword.SwordContentFacade.readXmlTextStandardJSwordMethod(SwordContentFacade.kt:111)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.service.sword.SwordContentFacade.readOsisFragment(SwordContentFacade.kt:89)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.CurrentPageBase.getPageContent(CurrentPageBase.kt:137)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.CurrentPageBase.getCurrentPageContent(CurrentPageBase.kt:126)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.CurrentCommentaryPage.getCurrentPageContent(CurrentCommentaryPage.kt:79)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invokeSuspend(Window.kt:236)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:8)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:4)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.window.Window.fetchDocument(Window.kt:231)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.window.Window.access$fetchDocument(Window.kt:46)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at net.bible.android.control.page.window.Window$updateText$1.invokeSuspend(Window.kt:188)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-01 06:43:16.145 26562 30024 E CurrentPage: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-01 06:43:16.145 26562 30024 E CurrentPage: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.jdom2.Element.getContent()' on a null object reference
```

**Comment by tuomas2** [comment]
- 2 windows, 1 FinRK, 1 GIll, synced
- Go to Ps 84:1 with FinRK 
- > error

**Comment by tuomas2** [comment]
Something weird in either module or JSword.
Why does getRawText(ps.84.0) give psalm intro (that is in ps.1.0)?
Anyway, low prio...
