### ISSUE TITLE
Crash in indexing module

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1782]
https://support.andbible.org/scp/tickets.php?id=845

```
10-01 10:25:26.856  4955  4955 E AndroidRuntime: FATAL EXCEPTION: main
10-01 10:25:26.856  4955  4955 E AndroidRuntime: Process: net.bible.android.activity, PID: 4955
10-01 10:25:26.856  4955  4955 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'org.crosswire.jsword.index.IndexStatus org.crosswire.jsword.book.Book.getIndexStatus()' on a null object reference
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at net.bible.android.view.activity.search.SearchIndexProgressStatus.jobFinished(SearchIndexProgressStatus.java:68)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at net.bible.android.view.activity.base.ProgressActivityBase.updateProgress(ProgressActivityBase.kt:117)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at net.bible.android.view.activity.base.ProgressActivityBase$initialiseView$uiUpdaterRunnable$1.run(ProgressActivityBase.kt:73)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5597)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
10-01 10:25:26.856  4955  4955 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-01 10:25:26.856  4955  4955 I AndroidRuntime: To Report FATAL to activityManagerService
10-01 10:25:26.953  4955  4955 I AndroidRuntime: Finished reporting FATAL to activityManagerService
```

**Comment by timbze** [comment]
Maybe same or related to #789
