### ISSUE TITLE
Crash in ProcessText (permission exception)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1802]
https://support.andbible.org/scp/tickets.php?id=849

```
10-03 10:45:10.828  9644  9644 E AndroidRuntime: FATAL EXCEPTION: main
10-03 10:45:10.828  9644  9644 E AndroidRuntime: Process: net.bible.android.activity, PID: 9644
10-03 10:45:10.828  9644  9644 E AndroidRuntime: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.PROCESS_TEXT typ=text/plain flg=0x10000000 cmp=com.microsoft.launcher/com.microsoft.bing.ProcessTextSearch (has extras) } from ProcessRecord{7b737c9 9644:net.bible.android.activity/u0a236} (pid=9644, uid=10236) not exported from uid 10252
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2074)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2042)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1990)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3973)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1714)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:968)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:939)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:393)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:162)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:123)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.lambda$createOverflowPanel$2$FloatingToolbar$FloatingToolbarPopup(FloatingToolbar.java:1475)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.widget.-$$Lambda$FloatingToolbar$FloatingToolbarPopup$E8FwnPCl7gZpcTlX_UaRPIBRnT0.onItemClick(Unknown Source:8)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1196)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3207)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4141)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3895)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:13574)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3135)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2789)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$OverflowPanel.dispatchTouchEvent(FloatingToolbar.java:1580)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3163)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2567)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:13840)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5815)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5606)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5103)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5156)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5122)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5262)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5130)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5319)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5103)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5156)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5122)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5130)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5103)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7939)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7908)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7859)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8081)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:250)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:336)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:181)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7561)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1065)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:785)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:584)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1388)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:515)
10-03 10:45:10.828  9644  9644 E AndroidRuntime: 
```

**Comment by tuomas2** [comment]
Microsoft Bing Search is being used... trying that.

**Comment by tuomas2** [comment]
does not appear in popup menu

**Comment by tuomas2** [comment]
I believe this crash happens after selecting "Microsoft bing" from popup menu. That would make this non-fatal and probably more Bing bug...  In stack trace I don't see that this would even originate in our code so there's not much we can do to avoid this.

**Comment by tuomas2** [comment]
Here again: https://support.andbible.org/scp/tickets.php?id=954
> Select a word from the Bible and click Search to close the application.
