### ISSUE TITLE
Crash in FirstDownload 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1808]
```
10-04 08:49:56.798 12233 12343 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-9
10-04 08:49:56.798 12233 12343 E AndroidRuntime: Process: net.bible.android.activity, PID: 12233
10-04 08:49:56.798 12233 12343 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@e6c01e5 is not valid; is your activity running?
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1071)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:340)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.app.AlertDialog$Builder.show(AlertDialog.java:1131)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at net.bible.android.view.activity.download.DownloadActivity$warnUserBooksNotDownloaded$1$1.invokeSuspend(DownloadActivity.kt:253)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-04 08:49:56.798 12233 12343 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-04 08:49:56.824 12233 12233 I net.bible.android.view.activity.download.FirstDownload: onPause:net.bible.android.view.activity.download.FirstDownload@99fd373
1
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=860

**Comment by tuomas2** [comment]
Investigated this a little. Somehow user could not download repo listings and then it crashed (weirdly) in FIrstDownload.

Waiting for more information so that we can prioritize this.

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=1228

This user report has similar issue, but in InstallZip
