### ISSUE TITLE
XZ compression not supported 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1809]
https://support.andbible.org/scp/tickets.php?id=871

```
10-05 21:29:24.562 14245  6436 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tukaani/xz/SingleXZInputStream;
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.apache.commons.compress.compressors.xz.XZCompressorInputStream.<init>(XZCompressorInputStream.java:98)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.apache.commons.compress.compressors.xz.XZCompressorInputStream.<init>(XZCompressorInputStream.java:72)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.common.compress.XZ.uncompress(XZ.java:76)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.ZVerseBackend.readRawContent(ZVerseBackend.java:366)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.ZVerseBackend.readRawContent(ZVerseBackend.java:132)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.AbstractBackend.readPassageOsis(AbstractBackend.java:256)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.AbstractBackend.readToOsis(AbstractBackend.java:189)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.SwordBook.getOsis(SwordBook.java:151)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.basic.AbstractPassageBook.getOsisIterator(AbstractPassageBook.java:121)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.BookData.getOsisContent(BookData.java:195)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at org.crosswire.jsword.book.BookData.getOsisFragment(BookData.java:120)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.readXmlTextStandardJSwordMethod(SwordContentFacade.kt:107)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.readOsisFragment(SwordContentFacade.kt:89)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageBase.getPageContent(CurrentPageBase.kt:137)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.CurrentBiblePage.getPageContent(CurrentBiblePage.kt:75)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageBase.getCurrentPageContent(CurrentPageBase.kt:126)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invokeSuspend(Window.kt:236)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:8)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:4)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.window.Window.fetchDocument(Window.kt:231)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.window.Window.access$fetchDocument(Window.kt:46)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$updateText$1.invokeSuspend(Window.kt:188)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-05 21:29:24.562 14245  6436 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.tukaani.xz.SingleXZInputStream
10-05 21:29:24.562 14245  6436 E AndroidRuntime: 	... 31 more
```

**Comment by zdposter** [comment]
[testxz.imp.zip](https://github.com/AndBible/and-bible/files/7303329/testxz.imp.zip)
[testxz.zip](https://github.com/AndBible/and-bible/files/7303330/testxz.zip)

Steps to reproduce problem:

```sh
$ unzip testxz.zip
$ unzip testxz.imp.zip

$ imp2vs testxz.imp -z xz -v KJV -o modules/texts/ztext/testxz
from file: Genesis 1:1
adding entry: Genesis 1:1 length 55/55
from file: Genesis 1:2
adding entry: Genesis 1:2 length 144/144

$ installmgr -li . testxz

Installed module: [testxz]


$ installmgr -l | grep -i testxz
 [testxz]       (1.0)   - Test Bible with XZ compression


$ diatheke -b testxz -k Gen 1:1
Genesis 1:1: In the beginning God created the heaven and the earth.
(testxz)
```

Then copy testxz.zip android device and install it to Bible study app via `Download Documents` -> `Load Documents From Zip`.
Then use module `testxz` and got to Gen 1:1  and app will crash...

**Comment by zdposter** [comment]
BTW: how can I uninstall `testxz` (manually installed) module?

**Comment by tuomas2** [comment]
Go to documents -> long click module -> trash can
