### ISSUE TITLE
Crash when pausing speaking

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1810]
```
-------- beginning of crash
10-03 05:24:42.213 27968 27968 E AndroidRuntime: FATAL EXCEPTION: main
10-03 05:24:42.213 27968 27968 E AndroidRuntime: Process: net.bible.android.activity, PID: 27968
10-03 05:24:42.213 27968 27968 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5ea0a7 is not valid; is your activity running?
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.view.ViewRootImpl.setView(ViewRootImpl.java:697)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.widget.Toast$TN.handleShow(Toast.java:459)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.os.Looper.loop(Looper.java:154)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6196)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
10-03 05:24:42.213 27968 27968 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
10-03 05:24:45.459 28937 28937 W System : ClassLoader referenced unknown path: /data/app/net.bible.android.activity-1/lib/arm
10-03 05:24:45.496 28937 28937 I System.out: Running on Android
10-03 05:24:45.513 28937 28937 D BibleApplication: BibleApplication:onCreate
10-03 05:24:45.525 28937 28937 I BibleApplication: OS:Linux ver 3.18.31-perf-gcade327
10-03 05:24:45.525 28937 28937 I BibleApplication: Java:The Android Project ver 0
10-03 05:24:45.526 28937 28937 I BibleApplication: Java home:/system
10-03 05:24:45.526 28937 28937 I BibleApplication: User dir:/ Timezone:null
10-03 05:24:45.534 28937 28937 D BibleApplication: SQLite version: 3.9.3
10-03 05:24:45.577 28937 28937 I System.out: isAndroid:true
10-03 05:24:45.839 28937 28937 E Slf4jAndroidLogger: Missing resource: Locale=en_US name=And Bible package=org.crosswire.jsword.JSMsg [MsgBase:obtainString:74] Thread[main,5,main]
10-03 05:24:45.936 28937 28937 D net.bible.service.sword.SwordDocumentFacade: Main JSword path:file:/storage/emulated/0/Android/data/net.bible.android.activity/files/
10-03 05:24:45.942 28937 28937 D BibleApplication: Finished all Upgrading
10-03 05:24:45.946 28937 28937 I ProgressNotificatnMngr: Initializing
10-03 05:24:45.947 28937 28937 D ProgressNotificatnMngr: Finished Initializing
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=853
