### ISSUE TITLE
Crash in SwordGenBook.getKey

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1817]
```
10-07 07:57:04.660 31000 31000 E AndroidRuntime: FATAL EXCEPTION: main
10-07 07:57:04.660 31000 31000 E AndroidRuntime: Process: net.bible.android.activity, PID: 31000
10-07 07:57:04.660 31000 31000 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.SwordGenBook.getKey(SwordGenBook.java:202)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageBase.restoreFrom(CurrentPageBase.kt:258)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.page.CurrentGeneralBookPage.restoreFrom(CurrentGeneralBookPage.kt:207)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageManager.restoreFrom(CurrentPageManager.kt:258)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.page.CurrentPageManager.restoreFrom$default(CurrentPageManager.kt:249)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.page.window.LinksWindow.initialisePageStateIfClosed(LinksWindow.kt:43)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.page.window.WindowControl.showLink(WindowControl.kt:114)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.showLink(LinkControl.kt:268)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.loadApplicationUrl(LinkControl.kt:130)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.loadApplicationUrl(LinkControl.kt:98)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.openLink(BibleView.kt:809)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$BibleViewClient.shouldOverrideUrlLoading(BibleView.kt:854)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-460607123:14)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:326)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:181)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-07 07:57:04.660 31000 31000 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
https://support.andbible.org/scp/tickets.php?id=878

**Comment by tuomas2** [comment]
```
10-07 07:35:31.167 31000 31000 D CurrentPage: State document:UZNTS
10-07 07:35:31.167 31000 31000 D CurrentPage: Restored document:Ð¯Ð½Ð³Ð¸ ÐÒ³Ð´ ÑÐ°ÑÒ³Ð¸, ÐÐµÑÐ¸Ð»Ð» Ð¡. Ð¢ÐµÐ½Ð½Ð¸

```

**Comment by tuomas2** [comment]
Could be due to this issue https://github.com/AndBible/and-bible/issues/1818

**Comment by tuomas2** [comment]
Asking user if complete reinstall of module helps.

**Comment by tuomas2** [comment]
Complete reinstall of module did help.

**Comment by tuomas2** [comment]
Reproduced myself now.

https://support.andbible.org/scp/tickets.php?id=2627

Happens after module is updated and after that scrolling the text causes the error.
