### ISSUE TITLE
Crash in Reading Plans (getTruncatedDate)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1819]
https://support.andbible.org/scp/tickets.php?id=888

```
10-09 01:48:44.724 22144 22144 E AndroidRuntime: FATAL EXCEPTION: main
10-09 01:48:44.724 22144 22144 E AndroidRuntime: Process: net.bible.android.activity, PID: 22144
10-09 01:48:44.724 22144 22144 E AndroidRuntime: java.lang.NoClassDefFoundError: org.apache.commons.lang3.-$$Lambda$Validate$XJJZURDO20sZXXyZMfTRRv13t2c
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at org.apache.commons.lang3.time.DateUtils.validateDateNotNull(DateUtils.java:1789)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at org.apache.commons.lang3.time.DateUtils.truncate(DateUtils.java:813)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.getTruncatedDate(CommonUtils.kt:319)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at net.bible.service.db.readingplan.ReadingPlanRepository.startPlan$default(ReadingPlanRepository.kt:65)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at net.bible.android.control.readingplan.ReadingPlanControl.startReadingPlan(ReadingPlanControl.kt:150)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at net.bible.android.view.activity.readingplan.ReadingPlanSelectorList.onListItemClick(ReadingPlanSelectorList.kt:85)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at net.bible.android.view.activity.base.ListActivityBase$mOnClickListener$1.onItemClick(ListActivityBase.kt:182)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5423)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
10-09 01:48:44.724 22144 22144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
```

**Comment by tuomas2** [comment]
Error looks like there would be issue in our proguard-rules.pro. BUT. I can't reproduce this issue when I run CommonUtils.truncateDate in app initialization, with production build.

**Comment by tuomas2** [comment]
https://play.google.com/console/u/0/developers/6727655833913220393/app/4974350217168681006/vitals/crashes/25945467/details?installedFrom=PLAY_STORE&days=30

**Comment by tuomas2** [comment]
According to Google Play, it reproduces only on Android 5.0-6.0.

**Comment by tuomas2** [comment]
I think I got it reproduced on Android 5 emulator.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=889

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=894

**Comment by timbze** [comment]
I think #1771 is the same underlying issue

`at net.bible.service.common.CommonUtils.getTruncatedDate(CommonUtils.kt:319)`

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=912
