### ISSUE TITLE
Crash when backing up modules

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1822]
https://support.andbible.org/scp/tickets.php?id=891

```
10-09 07:43:17.014 17919 17946 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
10-09 07:43:17.014 17919 17946 E AndroidRuntime: Process: net.bible.android.activity, PID: 17919
10-09 07:43:17.014 17919 17946 E AndroidRuntime: java.io.FileNotFoundException: Error downloading file: modules.zip
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1494)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.backupModulesToUri(BackupControl.kt:280)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.access$backupModulesToUri(BackupControl.kt:73)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$backupModulesViaIntent$2.invokeSuspend(BackupControl.kt:332)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-09 07:43:17.014 17919 17946 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by tuomas2** [comment]
> Sorry, but now it works. I was saving to Nextcloud folder and it also had 
> saved versions from the older android app (before v4). So I made a nee 
> folder on my phone. Works bow. Thank you.

**Comment by tuomas2** [comment]
User says it works in 613 also in Nextcloud
