### ISSUE TITLE
Crash in KJV / New Testament Introduction 1:1

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1853]
https://support.andbible.org/scp/tickets.php?id=901

See screenshot there

Last lines before crash

```
10-10 22:05:08.193  7012  7012 I ndroid.activit: Clamp target GC heap from 261MB to 256MB
10-10 22:05:08.193  7012  7012 I ndroid.activit: Alloc concurrent copying GC freed 7(16KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 237MB/256MB, paused 31us total 372.793ms
10-10 22:05:08.193  7012  7012 W ndroid.activit: Throwing OutOfMemoryError "Failed to allocate a 24312344 byte allocation with 18908808 free bytes and 18MB until OOM, target footprint 268435456, growth limit 268435456" (VmSize 6101592 kB)
10-10 22:05:08.194  7012  7012 W Looper  : Slow Looper main: Long Msg: seq=35236 plan=22:05:04.313  late=0ms wall=3882ms running=3193ms runnable=6ms h=android.os.Handler c=kotlinx.coroutines.internal.DispatchedContinuation
10-10 22:05:08.194  7012  7012 W Looper  : Slow Looper main: MotionEvent is 4100ms late (event_seq=14155, action=ACTION_DOWN) because of 2 msg, msg 2 took 3882ms (seq=35236 running=3193ms runnable=6ms h=android.os.Handler c=kotlinx.coroutines.internal.DispatchedContinuation)
10-10 22:05:08.194  7012  7012 W InputEventReceiver: App Input: 4100ms before dispatchInputEvent (MotionEvent: event_seq=14155, seq=632838, action=ACTION_DOWN)
10-10 22:05:08.195  7012  7012 W InputEventReceiver: App Input: 3993ms before dispatchInputEvent (MotionEvent: event_seq=14159, seq=632844, action=ACTION_UP)
10-10 22:05:08.196  7012  7012 W Looper  : Slow Looper main: MotionEvent is 2272ms late (event_seq=14161, action=ACTION_DOWN) because of 1 msg, msg 1 took 3882ms (seq=35236 running=3193ms runnable=6ms h=android.os.Handler c=kotlinx.coroutines.internal.DispatchedContinuation)
10-10 22:05:08.196  7012  7012 W InputEventReceiver: App Input: 2272ms before dispatchInputEvent (MotionEvent: event_seq=14161, seq=632848, action=ACTION_DOWN)
10-10 22:05:08.197  7012  7012 W InputEventReceiver: App Input: 2180ms before dispatchInputEvent (MotionEvent: event_seq=14163, seq=632851, action=ACTION_UP)
10-10 22:05:08.198  7012  7012 W Looper  : Slow Looper main: MotionEvent is 1225ms late (event_seq=14165, action=ACTION_DOWN) because of 1 msg, msg 1 took 3882ms (seq=35236 running=3193ms runnable=6ms h=android.os.Handler c=kotlinx.coroutines.internal.DispatchedContinuation)
10-10 22:05:08.198  7012  7012 W InputEventReceiver: App Input: 1225ms before dispatchInputEvent (MotionEvent: event_seq=14165, seq=632855, action=ACTION_DOWN)
10-10 22:05:08.201  7012  7012 W InputEventReceiver: App Input: 1113ms before dispatchInputEvent (MotionEvent: event_seq=14169, seq=632864, action=ACTION_UP)
10-10 22:05:08.240  7012  7012 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.240  7012  7012 I chatty  : uid=10190(net.bible.android.activity) identical 1 line
10-10 22:05:08.240  7012  7012 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.240  7012  7012 D CurrentPage: Set current doc to KJVA
10-10 22:05:08.241  7012  7012 W Slf4jAndroidLogger: JSword Versification mapper failed to map Intro.NT.1.1 from KJV to KJVA [VersificationConverter:convertVerseStrictly:95] Thread[main,5,main]
10-10 22:05:08.241  7012  7012 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.241  7012  7012 D BibleView[4] WIN: updateText, isVisible: true
10-10 22:05:08.241  7012  7012 D BibleView[4] WIN: Loading OSIS xml in background
10-10 22:05:08.241  7012  7012 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: updateText 145277995 java.lang.Exception
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.control.page.window.Window.updateText(Window.kt:181)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.control.BibleContentManager.updateText(BibleContentManager.kt:56)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.control.BibleContentManager.updateText$default(BibleContentManager.kt:43)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.control.BibleContentManager.updateText(Unknown Source:3)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.control.PassageChangeMediator.onCurrentPageChanged(PassageChangeMediator.java:60)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.control.page.CurrentPageManager.setCurrentDocument(CurrentPageManager.kt:168)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.view.activity.page.MainBibleActivity.setCurrentDocument(MainBibleActivity.kt:1014)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.view.activity.page.MainBibleActivity.menuForDocs$lambda-31(MainBibleActivity.kt:1005)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.view.activity.page.MainBibleActivity.$r8$lambda$Tr3rGTkdGxjzoLf0s1QcLnDULkw(Unknown Source:0)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at net.bible.android.view.activity.page.MainBibleActivity$$ExternalSyntheticLambda13.onMenuItemClick(Unknown Source:4)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.widget.AdapterView.performItemClick(Unknown Source:14)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.widget.AbsListView.performItemClick(Unknown Source:192)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.widget.AbsListView$PerformClick.run(Unknown Source:60)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.widget.AbsListView$3.run(Unknown Source:46)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.os.Handler.handleCallback(Unknown Source:2)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.os.Looper.loop(Unknown Source:242)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at android.app.ActivityThread.main(Unknown Source:98)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-10 22:05:08.242  7012  7012 D BibleView[4] WIN: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
10-10 22:05:08.242  7012  7052 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.242  7012  7012 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.242  7012  7052 D BibleView[4] WIN: Loading document:KJVA key:NT Intro
10-10 22:05:08.242  7012  7052 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.242  7012  7012 I CommonUtils: getWholeChapter (Key) Intro.NT.1.1
10-10 22:05:08.242  7012  7052 D net.bible.service.sword.SwordContentFacade: Using standard JSword to fetch document data
10-10 22:05:08.255  7012  7012 D BibleView[4]: Focus changed so start/stop scroll true
10-10 22:05:08.258  7012  7012 D BibleFrame[4]: updating padding for Window[4]: 0 0
10-10 22:05:08.258  7012  7012 D SplitBibleArea: rebuildRestoreButtons
10-10 22:05:08.258  7012  7012 D ForceDarkHelper: updateByCheckExcludeList: pkg: net.bible.android.activity activity: net.bible.android.view.activity.page.MainBibleActivity@a81dd38
10-10 22:05:08.262  7012  7012 I chatty  : uid=10190(net.bible.android.activity) identical 8 lines
10-10 22:05:08.262  7012  7012 D ForceDarkHelper: updateByCheckExcludeList: pkg: net.bible.android.activity activity: net.bible.android.view.activity.page.MainBibleActivity@a81dd38
10-10 22:05:08.263  7012  7012 D SplitBibleArea: toggleWindowButtonVisibility
10-10 22:05:08.398  7012  7052 I ndroid.activit: Waiting for a blocking GC Alloc
10-10 22:05:08.435  7012  7052 I ndroid.activit: WaitForGcToComplete blocked Alloc on HeapTrim for 36.881ms
10-10 22:05:08.435  7012  7052 I ndroid.activit: Starting a blocking GC Alloc
10-10 22:05:08.566  7012  7012 I net.bible.android.view.activity.page.MainBibleActivity: onPause:net.bible.android.view.activity.page.MainBibleActivity@a81dd38
10-10 22:05:08.567  7012  9103 I Process : Sending signal. PID: 7012 SIG: 9
```

**Comment by tuomas2** [comment]
Real issue is that NT intro seem to try to load whole NT into bible view (JSword issue?).

Show "Page too large to load" instead of this. Also show spinner already when loading content from JSword (which does not take forever).

**Comment by tuomas2** [comment]
I don't think there is any NT intro even in the document (at least BibleTime does not show anything)

**Comment by tuomas2** [comment]
Let's try to hide those intro books alltogether (until someone complains :-) )
