### ISSUE TITLE
Crash in Search / SearchIndex (Android 5)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1873]
https://support.andbible.org/scp/tickets.php?id=935

```
10-16 07:53:32.386  7173  7173 E AndroidRuntime: Process: net.bible.android.activity, PID: 7173
10-16 07:53:32.386  7173  7173 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.search.SearchIndex}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.crosswire.jsword.index.IndexManager.isIndexed(org.crosswire.jsword.book.Book)' on a null object reference
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:181)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6134)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.crosswire.jsword.index.IndexManager.isIndexed(org.crosswire.jsword.book.Book)' on a null object reference
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at net.bible.service.sword.SwordDocumentFacade.hasIndex(SwordDocumentFacade.kt:216)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at net.bible.android.view.activity.search.SearchIndex.onCreate(SearchIndex.kt:70)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6374)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
10-16 07:53:32.386  7173  7173 E AndroidRuntime: 	... 10 more
```

**Comment by tuomas2** [comment]
Also https://support.andbible.org/scp/tickets.php?id=1056

This is highly related to #1875 (same root cause)

**Comment by tuomas2** [comment]
```
11-19 12:16:04.522 27216 27216 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.crosswire.jsword.index.query.QueryDecorator.decorateAllWords(java.lang.String)' on a null object reference
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at org.crosswire.jsword.index.search.SearchType$2.decorate(SearchType.java:48)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at net.bible.android.control.search.SearchControl.decorateSearchString(SearchControl.kt:107)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search.decorateSearchString(Search.kt:232)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search.onSearch(Search.kt:214)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search.onCreate$lambda-0(Search.kt:115)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search.$r8$lambda$HGn9rGOVhaD81odVo6celHWnVU8(Search.kt)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at net.bible.android.view.activity.search.Search$$ExternalSyntheticLambda3.onEditorAction(Unknown Source)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at android.widget.TextView.onEditorAction(TextView.java:5355)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6134)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-19 12:16:04.522 27216 27216 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```
