### ISSUE TITLE
Error in restoring database (Permission denied)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1899]
Need to check `app/src/main/res/xml/file_paths.xml`

https://support.andbible.org/scp/tickets.php?id=960

```
10-23 15:05:54.983  6352  6352 E InstallZip: Error occurred
10-23 15:05:54.983  6352  6352 E InstallZip: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.alphainventor.filemanager/cache/SMB/0/-2079088156/modules.zip: open failed: EACCES (Permission denied)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at libcore.io.IoBridge.open(IoBridge.java:487)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:676)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at net.bible.android.view.activity.installzip.InstallZip$installZip$zh$1.invoke(InstallZip.kt:273)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at net.bible.android.view.activity.installzip.InstallZip$installZip$zh$1.invoke(InstallZip.kt:272)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at net.bible.android.view.activity.installzip.ZipHandler$checkZipFile$2.invokeSuspend(InstallZip.kt:85)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-23 15:05:54.983  6352  6352 E InstallZip: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at libcore.io.Posix.open(Native Method)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-23 15:05:54.983  6352  6352 E InstallZip: 	at libcore.io.IoBridge.open(IoBridge.java:473)
10-23 15:05:54.983  6352  6352 E InstallZip: 	... 12 more
```

```
10-23 15:12:53.328  6352  6368 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
10-23 15:12:53.328  6352  6368 E AndroidRuntime: Process: net.bible.android.activity, PID: 6352
10-23 15:12:53.328  6352  6368 E AndroidRuntime: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.alphainventor.filemanager/cache/SMB/0/-2079088156/andBibleDatabase.db: open failed: EACCES (Permission denied)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:487)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:676)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at net.bible.android.view.activity.StartupActivity$onActivityResult$3$1.invokeSuspend(StartupActivity.kt:354)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at libcore.io.Posix.open(Native Method)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:473)
10-23 15:12:53.328  6352  6368 E AndroidRuntime: 	... 10 more
10-23 15:12:53.383  6352  6352 E ActivityBase: closeKeyboard: java.lang.NullPointerException
10-23 15:12:53.742  6352  6352 E WindowManager: 
10-23 15:12:53.742  6352  6352 E WindowManager: android.view.WindowLeaked: Activity net.bible.android.activity.StartupActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{30d18f6 V.E...... R......D 0,0-864,174} that was originally added here
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:462)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:306)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.app.Dialog.show(Dialog.java:325)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at net.bible.android.view.util.Hourglass$show$2.invokeSuspend(Hourglass.kt:44)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:815)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:104)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.os.Looper.loop(Looper.java:207)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5765)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
10-23 15:12:53.742  6352  6352 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
10-23 15:13:00.416  6875  6875 E MultiWindowProxy: getServiceInstance failed!

```

**Comment by tuomas2** [comment]
Looks like a bug in com.alphainventor.filemanager file picker app

**Comment by tuomas2** [comment]
But crashing on our end is not nice. Should be fixed and report error to user.
