### ISSUE TITLE
Crash when starting search action: currentActivity must not be null

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1921]
```
10-29 07:05:21.303 19056 19056 E AndroidRuntime: FATAL EXCEPTION: main
10-29 07:05:21.303 19056 19056 E AndroidRuntime: Process: net.bible.android.activity, PID: 19056
10-29 07:05:21.303 19056 19056 E AndroidRuntime: java.lang.NullPointerException: getInstance().currentActivity must not be null
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at net.bible.android.control.search.SearchControl.getSearchIntent(SearchControl.kt:71)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at net.bible.android.view.activity.page.MenuCommandHandler.handleMenuRequest(MenuCommandHandler.kt:165)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onCreate$lambda-0(MainBibleActivity.kt:265)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.$r8$lambda$PPSOLU5URN8gHHSoS7uRQZA2Wss(Unknown Source:0)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity$$ExternalSyntheticLambda14.onNavigationItemSelected(Unknown Source:2)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:217)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.view.View.performClick(View.java:7156)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7129)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.view.View.access$3500(View.java:803)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27543)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:264)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7581)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-29 07:05:21.303 19056 19056 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=981
