### ISSUE TITLE
App crash when turning on device after not used since last day

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1929]
https://support.andbible.org/scp/tickets.php?id=1014

**Describe the bug**
AB crashed after turning on device in the morning.

**To me it seems it may have been an Android hiccup and not AB bug according to log.**

**Bug was found on And Bible version**
Build 615

**To Reproduce**
Unsure, used app last day, and crashed when turning on tablet in the morning. According to log it seems it hasn't crashed right away though.

**Smartphone (please complete the following information):**
Device info:
And Bible version: 4.0.615#80fda8474 standard release (built 21/10/21 17:41:48)
Android version: 5.1.1
Android SDK version: 22
Manufacturer: samsung
Model: SM-T330NU
Storage Mb free: 1054
WebView version: 95.0.4638.74
SQLITE version: 3.8.6
Used heap memory in Mb: 12
Max heap memory in Mb: 128

**Logs**
```
11-06 05:04:26.472  8554  8554 I CommonUtils: getWholeChapter (Key) Ps.125.3
11-06 05:08:36.446  8554  8554 W art     : Verification of java.lang.Object net.bible.android.view.activity.page.BibleView.evaluateJavascriptAsync(java.lang.String, kotlin.coroutines.Continuation) took 323.897ms
11-06 05:08:36.486  8554  8554 I art     : Rejecting re-init on previously-failed class java.lang.Class<net.bible.android.view.activity.page.BibleView$ActionModeCallback2>
11-06 05:08:36.496  8554  8554 I art     : Rejecting re-init on previously-failed class java.lang.Class<net.bible.android.view.activity.page.BibleView$ActionModeCallback2>
11-06 05:08:36.516  8554  8554 E WebViewFactory: Failed to list WebView package libraries for loadNativeLibrary
11-06 05:08:36.516  8554  8554 E WebViewFactory: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
11-06 05:08:36.516  8554  8554 E WebViewFactory: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:334)
11-06 05:08:36.516  8554  8554 E WebViewFactory: 	at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:282)
11-06 05:08:36.516  8554  8554 E WebViewFactory: 	at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:397)
```

Followed soon by:
```
11-06 05:08:36.526  8554  8554 E WebViewFactory: Chromium WebView package does not exist
11-06 05:08:36.526  8554  8554 E WebViewFactory: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:167)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:146)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.getFactory(WebView.java:2202)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2197)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2256)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.view.View.<init>(View.java:3843)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.view.View.<init>(View.java:3954)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.view.ViewGroup.<init>(ViewGroup.java:513)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:553)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:498)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:481)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:468)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:458)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at net.bible.android.view.activity.page.BibleView.<init>(BibleView.kt:194)
11-06 05:08:36.526  8554  8554 E WebViewFactory: 	at net.bible.android.view.activity.page.BibleViewFactory.getOrCreateBibleView(BibleViewFactory.kt:66)
```

And:
```
11-06 05:08:36.566  8554  8554 E AndroidRuntime: FATAL EXCEPTION: main
11-06 05:08:36.566  8554  8554 E AndroidRuntime: Process: net.bible.android.activity, PID: 8554
11-06 05:08:36.566  8554  8554 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3139)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3238)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6862)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:174)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.getFactory(WebView.java:2202)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2197)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2256)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.view.View.<init>(View.java:3843)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.view.View.<init>(View.java:3954)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.view.ViewGroup.<init>(ViewGroup.java:513)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:553)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:498)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:481)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:468)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:458)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.<init>(BibleView.kt:194)
11-06 05:08:36.566  8554  8554 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleViewFactory.getOrCreateBibleView(BibleViewFactory.kt:66)
```

**Comment by tuomas2** [comment]
I suppose this is not happening every day anyway?

**Comment by timbze** [comment]
> I suppose this is not happening every day anyway?

Don't think so. I asked user to report if he has the error again.

**Comment by timbze** [comment]
Closing as stale, and likely not AB related.
