### ISSUE TITLE
Crash / IllegalStateException: Already resumed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1940]
```
11-07 12:08:06.756  6546  6546 E AndroidRuntime: FATAL EXCEPTION: main
11-07 12:08:06.756  6546  6546 E AndroidRuntime: Process: net.bible.android.activity, PID: 6546
11-07 12:08:06.756  6546  6546 E AndroidRuntime: java.lang.IllegalStateException: Already resumed
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity$showStableNotice$2$d$2.onClick(MainBibleActivity.kt:412)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5268)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
11-07 12:08:06.756  6546  6546 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

https://support.andbible.org/scp/tickets.php?id=1018

**Comment by tuomas2** [comment]
Duplicate of #1760
