### ISSUE TITLE
Export modules zip to local store crashed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1949]
https://support.andbible.org/scp/tickets.php?id=1046

```
11-14 11:23:40.499  1438  1468 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
11-14 11:23:40.499  1438  1468 E AndroidRuntime: Process: net.bible.android.activity, PID: 1438
11-14 11:23:40.499  1438  1468 E AndroidRuntime: java.io.FileNotFoundException: Error downloading file: modules.zip
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1494)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.backupModulesToUri(BackupControl.kt:280)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.access$backupModulesToUri(BackupControl.kt:73)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$backupModulesViaIntent$2.invokeSuspend(BackupControl.kt:332)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-14 11:23:40.499  1438  1468 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by tuomas2** [comment]
Can't reproduce.

**Comment by tuomas2** [comment]
Asked if this reproduces to the user. @alerque

**Comment by meichthys** [comment]
Also cannot reproduce (although i don't have the details in the support.andbible ticket).
