### ISSUE TITLE
Error in showing module info when conf is malformed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1951]
https://support.andbible.org/scp/tickets.php?id=1045

doc probably shown in screenshot (probably RusCARS).

```
11-14 16:09:25.290 12074 12074 E AndroidRuntime: FATAL EXCEPTION: main
11-14 16:09:25.290 12074 12074 E AndroidRuntime: Process: net.bible.android.activity, PID: 12074
11-14 16:09:25.290 12074 12074 E AndroidRuntime: java.lang.IllegalArgumentException: invalid: 4.1.
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at org.crosswire.common.util.Version.<init>(Version.java:69)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.showAbout(CommonUtils.kt:749)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at net.bible.android.view.activity.base.DocumentSelectionBase$handleAbout$1.invokeSuspend(DocumentSelectionBase.kt:514)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:815)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:194)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5624)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
11-14 16:09:25.290 12074 12074 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

```

**Comment by tuomas2** [comment]
Duplicate of #1955
