### ISSUE TITLE
Overwriting backup to onedrive crashes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1962]
```
11-25 12:16:20.009 12688 29887 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
11-25 12:16:20.009 12688 29887 E AndroidRuntime: Process: net.bible.android.activity, PID: 12688
11-25 12:16:20.009 12688 29887 E AndroidRuntime: kotlin.io.FileAlreadyExistsException: /data/user/0/net.bible.android.activity/databases/andBibleDatabase.db -> /data/user/0/net.bible.android.activity/files/backup/andBibleDatabase.db: The destination file already exists.
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:224)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlin.io.FilesKt.copyTo$default(Unknown Source:0)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.backupDatabaseViaSendIntent(BackupControl.kt:114)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.access$backupDatabaseViaSendIntent(BackupControl.kt:73)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$backupDatabaseViaSendIntent$1.invokeSuspend(Unknown Source:12)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
11-25 12:16:20.009 12688 29887 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

https://support.andbible.org/scp/tickets.php?id=1072

**Comment by tuomas2** [comment]
> This crash happened when I tried to back up database to onedrive for the second time.

**Comment by tuomas2** [comment]
Reproduced it with google drive too
