### ISSUE TITLE
MainBibleActivity startup NullPointerException

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1964]
https://support.andbible.org/scp/tickets.php?id=1083

```
11-25 14:48:42.885 27899 27925 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
11-25 14:48:42.885 27899 27925 E AndroidRuntime: Process: net.bible.android.activity, PID: 27899
11-25 14:48:42.885 27899 27925 E AndroidRuntime: java.lang.NullPointerException
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity$Companion.getMainBibleActivity(MainBibleActivity.kt:1501)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea.updateRestoreButtons(SplitBibleArea.kt:554)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea.access$updateRestoreButtons(SplitBibleArea.kt:107)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea$onEvent$1$1.invokeSuspend(SplitBibleArea.kt:418)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:250)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7803)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-25 14:48:42.885 27899 27925 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by tuomas2** [comment]
asked extra info

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1221
