### ISSUE TITLE
HistoryItem table not properly migrated

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1972]
https://support.andbible.org/scp/tickets.php?id=1092

```
12-02 22:57:41.753  1440  1501 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
12-02 22:57:41.753  1440  1501 E AndroidRuntime: Process: net.bible.android.activity, PID: 1440
12-02 22:57:41.753  1440  1501 E AndroidRuntime: java.lang.IllegalStateException: Migration didn't properly handle: HistoryItem(net.bible.android.database.WorkspaceEntities.HistoryItem).
12-02 22:57:41.753  1440  1501 E AndroidRuntime:  Expected:
12-02 22:57:41.753  1440  1501 E AndroidRuntime: TableInfo{name='HistoryItem', columns={createdAt=Column{name='createdAt', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, document=Column{name='document', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, anchorOrdinal=Column{name='anchorOrdinal', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0, defaultValue='NULL'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, key=Column{name='key', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, yOffsetRatio=Column{name='yOffsetRatio', type='REAL', affinity='4', notNull=false, primaryKeyPosition=0, defaultValue='null'}, windowId=Column{name='windowId', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[ForeignKey{referenceTable='Window', onDelete='CASCADE', onUpdate='NO ACTION', columnNames=[windowId], referenceColumnNames=[id]}], indices=[Index{name='index_HistoryItem_windowId', unique=false, columns=[windowId]}]}
12-02 22:57:41.753  1440  1501 E AndroidRuntime:  Found:
12-02 22:57:41.753  1440  1501 E AndroidRuntime: TableInfo{name='HistoryItem', columns={createdAt=Column{name='createdAt', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, document=Column{name='document', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, anchorOrdinal=Column{name='anchorOrdinal', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0, defaultValue='NULL'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, key=Column{name='key', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, yOffsetRatio=Column{name='yOffsetRatio', type='REAL', affinity='4', notNull=false, primaryKeyPosition=0, defaultValue='null'}, windowId=Column{name='windowId', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[ForeignKey{referenceTable='Window_old', onDelete='CASCADE', onUpdate='NO ACTION', columnNames=[windowId], referenceColumnNames=[id]}], indices=[Index{name='index_HistoryItem_windowId', unique=false, columns=[windowId]}]}
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:103)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at net.bible.android.database.SwordDocumentInfoDao_Impl.getKnownInstalled(SwordDocumentInfoDao_Impl.java:254)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at net.bible.android.view.activity.StartupActivity.getPreviousInstallDetected(StartupActivity.kt:80)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at net.bible.android.view.activity.StartupActivity.showFirstLayout(StartupActivity.kt:246)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at net.bible.android.view.activity.StartupActivity.access$showFirstLayout(StartupActivity.kt:75)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at net.bible.android.view.activity.StartupActivity$postBasicInitialisationControl$2.invokeSuspend(StartupActivity.kt:227)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8049)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
12-02 22:57:41.753  1440  1501 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```

**Comment by tuomas2** [comment]
To make fixing faster, Could you send your database via Backup & Restore > Share or Backup app Database to... -> choose yor email app and send it to help.andbible@gmail.com. Or if you prefer personally (not to the developer team), you can also send it to tuomas.airaksinen@gmail.com. Crash dialog should allow also doing this.

**Comment by tuomas2** [comment]
asked user db to ease debugging

**Comment by tuomas2** [comment]
migration has been from db version 10, so jumping from 3.2 to 4.0. (before workspaces feature)

**Comment by tuomas2** [comment]
Another: https://support.andbible.org/scp/tickets.php?id=1254
