### ISSUE TITLE
Crash when creating index

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1986]
https://support.andbible.org/scp/tickets.php?id=1138

> Opened app and attemted search/find. If no index, crashes when attempting to build index. If index exixts, crash affter entering search terms and clicking to find. Crashes on all installed bible versions: KJV, NET, WEB, NASB, GWN

Device info:
And Bible version: 4.0.622#4335f47a1 standard release (built 02/12/21 19:07:34)
Android version: 11
Android SDK version: 30
Manufacturer: samsung
Model: SM-G781U
Storage Mb free: 68673
WebView version: 96.0.4664.104
SQLITE version: 3.28.0
Used heap memory in Mb: 15
Max heap memory in Mb: 256

```
12-16 05:55:24.675  3747 14315 E AndroidRuntime: FATAL EXCEPTION: Thread-11
12-16 05:55:24.675  3747 14315 E AndroidRuntime: Process: net.bible.android.activity, PID: 3747
12-16 05:55:24.675  3747 14315 E AndroidRuntime: java.lang.ExceptionInInitializerError
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.InstalledIndex.instance(InstalledIndex.java:60)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.analysis.LuceneAnalyzer.<init>(LuceneAnalyzer.java:51)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneIndex.<init>(LuceneIndex.java:209)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneIndexManager.scheduleIndexCreation(LuceneIndexManager.java:143)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at net.bible.service.sword.index.IndexCreator.scheduleIndexCreation$lambda-0(IndexCreator.kt:39)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at net.bible.service.sword.index.IndexCreator.$r8$lambda$-1e-uH0HMWgsGY-Mwz0MvidNMDA(Unknown Source:0)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at net.bible.service.sword.index.IndexCreator$$ExternalSyntheticLambda0.run(Unknown Source:2)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at java.util.Properties.loadConvert(Properties.java:576)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at java.util.Properties.load0(Properties.java:391)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at java.util.Properties.load(Properties.java:337)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.common.util.PropertyMap.load(PropertyMap.java:108)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.common.util.NetUtil.loadProperties(NetUtil.java:641)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.InstalledIndex.<init>(InstalledIndex.java:126)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.InstalledIndex.<clinit>(InstalledIndex.java:200)
12-16 05:55:24.675  3747 14315 E AndroidRuntime: 	... 8 more
12-16 05:55:24.677  3747  3747 I ProgressActivityBase: Job finished:Creating index. Processing KJV
```

**Comment by tuomas2** [comment]
```
12-16 05:56:25.008 13902 14509 E AndroidRuntime: java.lang.ExceptionInInitializerError
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.InstalledIndex.instance(InstalledIndex.java:60)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.analysis.LuceneAnalyzer.<init>(LuceneAnalyzer.java:51)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneIndex.find(LuceneIndex.java:292)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.query.BaseQuery.find(BaseQuery.java:50)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.query.AndQuery.find(AndQuery.java:59)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneSearcher.search(LuceneSearcher.java:96)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneSearcher.search(LuceneSearcher.java:83)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.book.basic.AbstractBook.find(AbstractBook.java:127)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.book.basic.AbstractBook.find(AbstractBook.java:112)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.search(SwordContentFacade.kt:336)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at net.bible.android.control.search.SearchControl.getSearchResults(SearchControl.kt:126)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at net.bible.android.view.activity.search.SearchResults$fetchSearchResults$2.invokeSuspend(SearchResults.kt:123)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at java.util.Properties.loadConvert(Properties.java:576)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at java.util.Properties.load0(Properties.java:391)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at java.util.Properties.load(Properties.java:337)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.common.util.PropertyMap.load(PropertyMap.java:108)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.common.util.NetUtil.loadProperties(NetUtil.java:641)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.InstalledIndex.<init>(InstalledIndex.java:126)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.InstalledIndex.<clinit>(InstalledIndex.java:200)
12-16 05:56:25.008 13902 14509 E AndroidRuntime: 	... 18 more
```
