### ISSUE TITLE
Android 12: crash with speaking

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1990]
```
021-12-16 23:15:54.464 9005-9005/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.bible.android.activity.debug, PID: 9005
    java.lang.SecurityException: listen
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
        at android.telephony.TelephonyRegistryManager.listenFromListener(TelephonyRegistryManager.java:250)
        at android.telephony.TelephonyManager.listen(TelephonyManager.java:5999)
        at net.bible.android.control.event.phonecall.PhoneCallMonitor.startMonitoring(PhoneCallMonitor.java:65)
        at net.bible.android.control.event.phonecall.PhoneCallMonitor.ensureMonitoringStarted(PhoneCallMonitor.java:43)
        at net.bible.service.device.speak.TextToSpeechServiceManager.stopIfPhoneCall(TextToSpeechServiceManager.kt:359)
        at net.bible.service.device.speak.TextToSpeechServiceManager.onInitListener$lambda-0(TextToSpeechServiceManager.kt:184)
        at net.bible.service.device.speak.TextToSpeechServiceManager.$r8$lambda$oswUJehTvHcoEehYf6D3bLWyWws(Unknown Source:0)
        at net.bible.service.device.speak.TextToSpeechServiceManager$$ExternalSyntheticLambda1.onInit(Unknown Source:2)
        at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$TextToSpeech(TextToSpeech.java:890)
        at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda17.run(Unknown Source:4)
        at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:899)
        at android.speech.tts.TextToSpeech.access$900(TextToSpeech.java:79)
        at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2280)
        at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2240)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.telephony.TelephonyPermissions.enforceCarrierPrivilege(TelephonyPermissions.java:634)
        at com.android.internal.telephony.TelephonyPermissions.checkReadPhoneState(TelephonyPermissions.java:149)
        at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadPhoneState(TelephonyPermissions.java:94)
        at com.android.server.TelephonyRegistry.checkListenerPermission(TelephonyRegistry.java:3093)
        at com.android.server.TelephonyRegistry.listen(TelephonyRegistry.java:1024)
```

**Comment by tuomas2** [comment]
we're using deprecated API https://developer.android.com/reference/android/telephony/PhoneStateListener

**Comment by tuomas2** [comment]
in PhoneCallMonitor.java.
