### ISSUE TITLE
Index creation fails with Android 6 (M)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#201]
```
01-06 01:02:01.338 10012-10066/net.bible.android.activity E/AndroidRuntime: FATAL EXCEPTION: Thread-333
    Process: net.bible.android.activity, PID: 10012
    java.lang.VerifyError: Rejecting class org.apache.lucene.index.DocumentsWriter because it failed compile-time verification (declaration of 'org.apache.lucene.index.DocumentsWriter' appears in /data/app/net.bible.android.activity-2/base.apk:classes2.dex)
        at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:158)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:926)
        at org.crosswire.jsword.index.lucene.LuceneIndex.<init>(LuceneIndex.java:203)
        at org.crosswire.jsword.index.lucene.LuceneIndexManager.scheduleIndexCreation(LuceneIndexManager.java:143)
        at net.bible.service.sword.index.IndexCreator$1.run(IndexCreator.java:46)
        at java.lang.Thread.run(Thread.java:818)

```

**Comment by tuomas2** [comment]
This was reported for version 2.13.264 on Play Console. I could reproduce it in emulator with 3.0.272-rc with debug build, but not with production build. So assuming this is OK by now.
