### ISSUE TITLE
Crash - ArrayIndexOutOfBoundsException (in loading general book)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2038]
And Bible version: 4.0.628#7989284a7 standard release (built 18/12/21 21:34:32)
Android version: 9
Android SDK version: 28
Manufacturer: asus
Model: ASUS_X017DA
Storage Mb free: 695
WebView version: 96.0.4664.104
SQLITE version: 3.22.0
Used heap memory in Mb: 5
Max heap memory in Mb: 256

https://support.andbible.org/scp/tickets.php?id=1177

```
01-01 00:49:23.261 10584 10606 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Index out of range (Given 0, Max 0).
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at org.crosswire.jsword.passage.AbstractPassage.getVerseAt(AbstractPassage.java:377)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at org.crosswire.jsword.passage.KeyUtil.getVerse(KeyUtil.java:80)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.ZVerseBackend.getRawTextLength(ZVerseBackend.java:170)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.ZVerseBackend.contains(ZVerseBackend.java:156)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.SwordBook.contains(SwordBook.java:139)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.bookContainsAnyOf(SwordContentFacade.kt:347)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.readOsisFragment(SwordContentFacade.kt:84)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.CurrentGeneralBookPage.getCurrentPageContent(CurrentGeneralBookPage.kt:117)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invokeSuspend(Window.kt:239)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:8)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:4)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.window.Window.fetchDocument(Window.kt:234)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.window.Window.access$fetchDocument(Window.kt:46)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$updateText$1.invokeSuspend(Window.kt:188)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
01-01 00:49:23.261 10584 10606 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by tuomas2** [comment]
Asked user further info
