### ISSUE TITLE
Using WebView from more than one process at once with the same data directory is not supported

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2060]
https://support.andbible.org/scp/tickets.php?id=1217

```
01-14 22:06:36.868 28743 28743 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process net.bible.android.activity (pid 28743), lock owner net.bible.android.activity (pid 16042)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4022)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process net.bible.android.activity (pid 28743), lock owner net.bible.android.activity (pid 16042)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle.apk-stable-457708233:27)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at jz0.h(chromium-TrichromeWebViewGoogle.apk-stable-457708233:40)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at jz0.b(chromium-TrichromeWebViewGoogle.apk-stable-457708233:20)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at jz0.j(chromium-TrichromeWebViewGoogle.apk-stable-457708233:2)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.h(chromium-TrichromeWebViewGoogle.apk-stable-457708233:2)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.apk-stable-457708233:14)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:443)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:363)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:345)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:332)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:322)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.<init>(BibleView.kt:193)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleViewFactory.getOrCreateBibleView(BibleViewFactory.kt:65)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.BibleFrame.build(BibleFrame.kt:144)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.BibleFrame.<init>(BibleFrame.kt:130)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea.updateWindows(SplitBibleArea.kt:213)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.SplitBibleArea.update(SplitBibleArea.kt:165)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.DocumentViewManager.buildWebViews(DocumentViewManager.kt:78)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.DocumentViewManager.buildView(DocumentViewManager.kt:84)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.screen.DocumentViewManager.buildView$default(DocumentViewManager.kt:83)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:234)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8282)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8262)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
01-14 22:06:36.868 28743 28743 E AndroidRuntime: 	... 12 more

```

**Comment by tuomas2** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=558377#c142

**Comment by timbze** [comment]
Is there any chance this is related to #1591 or that fixing that issue might have fixed this?

**Comment by tuomas2** [comment]
> Is there any chance this is related to #1591 or that fixing that issue might have fixed this?

Hmm, I can't see how it would be related.
