### ISSUE TITLE
Compare multiple verses crash (beta module and LXX versification)

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2074]
**Describe the bug**
I don't know what's the cause of this but I found one consistent way to reproduce.

**To Reproduce**
1. Go to Psalm 89 in KJV
2. Select the word "anointed" in v20 up to the word "not" in v22 (see screenshot below)
3. Press "Compare" in the popup context menu
4. Crash

**Bug was found on And Bible version**
Build 633

This user bug report is 630, but I reproduced in 633
https://support.andbible.org/scp/tickets.php?id=1236

![Screenshot from 2022-01-26 07-01-50](https://user-images.githubusercontent.com/35117769/151167632-988d43b8-295d-4b18-92c9-577f4077e7e1.png)

**Comment by bvahedy** [comment]
@timbze, I'm on 631 build and can't reproduce this.

**Comment by tuomas2** [comment]
Did not crash for me either, just tried (633)

**Comment by tuomas2** [comment]
```
01-23 22:18:56.956 14972 14994 E AndroidRuntime: net.bible.service.common.ParseException: Parsing error
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.readXmlTextStandardJSwordMethod(SwordContentFacade.kt:116)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.readOsisFragment(SwordContentFacade.kt:89)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.CurrentCommentaryPage.getCurrentPageContent(CurrentCommentaryPage.kt:73)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invokeSuspend(Window.kt:239)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:8)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$fetchDocument$2.invoke(Unknown Source:4)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.window.Window.fetchDocument(Window.kt:234)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.window.Window.access$fetchDocument(Window.kt:46)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.android.control.page.window.Window$updateText$1.invokeSuspend(Window.kt:188)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.passage.RangedPassage$VerseRangeIterator.splitNext(RangedPassage.java:464)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.passage.RangedPassage$VerseRangeIterator.next(RangedPassage.java:443)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.passage.RangedPassage$VerseRangeIterator.next(RangedPassage.java:401)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.passage.AbstractPassage.hasRanges(AbstractPassage.java:324)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.book.basic.AbstractPassageBook.getOsisIterator(AbstractPassageBook.java:93)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.book.BookData.getOsisContent(BookData.java:195)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at org.crosswire.jsword.book.BookData.getOsisFragment(BookData.java:120)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	at net.bible.service.sword.SwordContentFacade.readXmlTextStandardJSwordMethod(SwordContentFacade.kt:108)
01-23 22:18:56.956 14972 14994 E AndroidRuntime: 	... 17 more
```

**Comment by tuomas2** [comment]
must depend on installed bible docs

**Comment by timbze** [comment]
> Did not crash for me either, just tried (633)

Weird, crashes for me every time

**Comment by tuomas2** [comment]
@timbze you could either debug that function to figure out which module causes the crash or you could give list of your installed bible docs, so I can debug.

**Comment by timbze** [comment]
The problem is LXX module from Crosswire beta repository. It can not be downloaded in AB now, but I'm not sure what changes you make for production, I guess it was downloadable before.

Module LXX version 2.5 has `KJV versification`, but 2.7 shows `LXX versification`. I don't know if `LXX versification` is even valid or if that's a bug in the beta module.

I get this in my log:
```
01-26 06:56:25.113 23429 25751 W Slf4jAndroidLogger: JSword Versification mapper failed to map Ps.89.22 from KJV to LXX [VersificationConverter:convertVerseStrictly:95] Thread[DefaultDispatcher-worker-1,5,main]
```

**Comment by timbze** [comment]
> 2\. Select the word "anointed" in v20 up to the word "not" in v22 (see screenshot below)

BTW I found that I can simply share v20 to 22 (doesn't have to be exact words) and it reproduces every time.

**Comment by timbze** [comment]
LXX is [valid versification](https://wiki.crosswire.org/Alternate_Versification) supported in libsword 1.7.2+
![Screenshot from 2022-01-31 17-13-37](https://user-images.githubusercontent.com/35117769/151888528-cf679d02-6087-45b0-b3d4-597260f0aa64.png)

**Comment by tuomas2** [comment]
Hmm, nobody told me that there are new versifications out there... Should implement in JSword then and meanwhile drop support for modules that require 1.7.2.

**Comment by tuomas2** [comment]
There seem to be total 6 new versifications that we do not yet support: 

```
1.7.2
LXX – for the Greek LXX & translations of the LXX
Orthodox – based on the LXX v11n, but using a different book order and fewer books
SynodalProt – the ParaText Synodal Protestant v11n as used by IBT for Bibles containing protocanonical books only
1.8.0
French Bible versifications[1]:

Calvin – French Bible d'Olivétan and followers, 1560+ Bible de Genève, 1707-1855, Bible D. Martin, Bible F. Ostervald...
Darby_fr – French Bibles by J.N. Darby
Segond – French Bibles L. Segond 1880, 1910, 1978, 2002 (NBS), 2007 (SG21)
```

**Comment by tuomas2** [comment]
As mentioned on #2074 issue was not that JSword would not support LXX (or anything else).
