### ISSUE TITLE
java.lang.IllegalStateException: Cannot perform this action on a sealed instance.

### ISSUE THREAD

**Issue by noorumapped** [AndBible/and-bible#2075]
Hello, everyone. I'm in a bad situation. I'm getting this error in pre-lauch report when submitting android mobile app and have looked everywhere on the internet but haven't found a solution. I'm not sure how to correct this error. Our application is written in react-native.

**Error in Pre-launch report:**
FATAL EXCEPTION: main
Process: com.nuba.mobile.android, PID: 18007
java.lang.IllegalStateException: Cannot perform this action on a sealed instance.
	at android.view.accessibility.AccessibilityNodeInfo.enforceNotSealed(AccessibilityNodeInfo.java:2992)
	at android.view.accessibility.AccessibilityNodeInfo.setSource(AccessibilityNodeInfo.java:818)
	at android.view.accessibility.AccessibilityNodeInfo.setSource(AccessibilityNodeInfo.java:795)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:3008)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:7897)
	at android.view.View.createAccessibilityNodeInfo(View.java:7883)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1051)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:876)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:199)
	at android.view.AccessibilityInteractionController.-wrap1(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1225)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**They tested it on this device for example.**
<img width="980" alt="Screen Shot 2022-01-26 at 4 15 52 PM" src="https://user-images.githubusercontent.com/86007357/151248205-11e8e887-a644-462d-870f-3c56dcf5e31a.png">

**I have attached the logcat**
[logcat-2.txt](https://github.com/AndBible/and-bible/files/7945662/logcat-2.txt)

**Comment by timbze** [comment]
@noorumapped is this related to AndBible at all? I can not yet see how

**Comment by noorumapped** [comment]
not sure. if this is aright category it in but i need help with this issue :(

**Comment by noorumapped** [comment]
@timbze

**Comment by timbze** [comment]
@noorumapped this repo is a Bible app. We don't fix other people's apps

**Comment by tuomas2** [comment]
how can we help you?
