### ISSUE TITLE
Crash: "Comparison method violates its general contract!"

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2119]
https://support.andbible.org/scp/tickets.php?id=1297
```
02-20 20:54:00.105 11060 11060 E AndroidRuntime: FATAL EXCEPTION: main
02-20 20:54:00.105 11060 11060 E AndroidRuntime: Process: net.bible.android.activity, PID: 11060
02-20 20:54:00.105 11060 11060 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at java.util.TimSort.mergeHi(TimSort.java:899)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at java.util.TimSort.mergeAt(TimSort.java:516)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at java.util.TimSort.mergeCollapse(TimSort.java:441)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:245)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1424)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:2557)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:1073)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at kotlin.collections.CollectionsKt.sortedWith(Unknown Source:0)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.control.document.DocumentControl.getCommentariesForVerse(DocumentControl.kt:1043)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.updateActions(MainBibleActivity.kt:863)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.updateToolbar(MainBibleActivity.kt:1221)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.toggleFullScreen(MainBibleActivity.kt:1041)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.setFullScreen(MainBibleActivity.kt:1033)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleGestureListener.onScroll(BibleGestureListener.kt:126)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:728)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at androidx.core.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView._init_$lambda-0(BibleView.kt:255)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.$r8$lambda$oIMPS4KUIqxnDebkjXj0yfkU5tc(Unknown Source:0)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$$ExternalSyntheticLambda0.onTouch(Unknown Source:2)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14383)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3145)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2816)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:508)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1875)
02-20 20:54:00.105 11060 11060 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4242)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:466)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:14661)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6289)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6076)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5531)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5588)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5554)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5706)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5562)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5763)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5535)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5588)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5554)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5562)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5535)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8415)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8366)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8326)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8543)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:241)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:217)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8495)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8582)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:819)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8087)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-20 20:54:00.106 11060 11060 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=1559
> I was not aware the app had closed.
I simply went back to use it and this process was initiated.
I have no more information that can help you.
