### ISSUE TITLE
MainBibleActivity was created second time! (after search activity)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2131]
https://support.andbible.org/scp/tickets.php?id=1344

Crash screenshot from find activity.

```
03-13 15:13:52.515 21030 21030 E AndroidRuntime: FATAL EXCEPTION: main
03-13 15:13:52.515 21030 21030 E AndroidRuntime: Process: net.bible.android.activity, PID: 21030
03-13 15:13:52.515 21030 21030 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.RuntimeException: MainBibleActivity was created second time!
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: Caused by: java.lang.RuntimeException: MainBibleActivity was created second time!
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:208)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7963)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7952)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
03-13 15:13:52.515 21030 21030 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
```

**Comment by tuomas2** [comment]
asking more info from user

**Comment by tuomas2** [comment]
Again: https://support.andbible.org/scp/tickets.php?id=1416

This time a bit more info, like Android version (8.0).

**Comment by tuomas2** [comment]
Probaly this too, though logcat does not reveal the crash https://support.andbible.org/scp/tickets.php?id=1411
Screenshot shows that it's after search.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1444

**Comment by tuomas2** [comment]
> When I wanted to exit the "search" (I searched for a word), it crashed. Anyway, it's good to use. It is extremely useful.
> It would be nice if there were also Hungarian comments.
> Thanks.

https://support.andbible.org/scp/tickets.php?id=1521

Reported on 649. Logcat reveals that it is this issue.

**Comment by timbze** [comment]
I think this relates to Android Memory Management killing (or suspending) the process while the search screen is open, this is not the same as user manually removing process in task screen. The log (in the latest link) seems to support that as well, the log starts with search screen open.

My guess is something like this happens.
1. User is in search screen and presses home to get out of it
2. Android Memory Management kills (suspends) process
3. User opens AB and it opens in search screen
4. Some unknown sequence of events here causes the issue
