### ISSUE TITLE
Unable to stop service ...ForegroundService

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2135]
https://support.andbible.org/scp/tickets.php?id=1334

```
03-10 09:07:45.265 28569 28569 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService@697ea50: kotlin.UninitializedPropertyAccessException: lateinit property windowControl has not been initialized
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4825)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.access$2000(ActivityThread.java:301)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2201)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8625)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: Caused by: kotlin.UninitializedPropertyAccessException: lateinit property windowControl has not been initialized
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at net.bible.service.common.CommonUtilsBase.getWindowControl(CommonUtils.kt:174)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.prepareForDestruction(CommonUtils.kt:929)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService.onDestroy(TextToSpeechNotificationManager.kt:109)
03-10 09:07:45.265 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4805)
```

**Comment by tuomas2** [comment]
Again: https://support.andbible.org/scp/tickets.php?id=1348

> Good day, The application crashed a few times when I was setting up the Bible text monitoring function.

**Comment by timbze** [comment]
One more: https://support.andbible.org/scp/tickets.php?id=1388

I'm seeing this a bit further up before the crash. It looks like there's some code that is doing UI things on non-ui thread which may be the cause of the crash
```
04-13 08:58:16.746 23315 23419 I BibleView[1]: TaskQueue Adding runnable to queue
04-13 08:58:16.838 23315 23443 I WindowSync: synchronizeWindows Window[1]...
04-13 08:58:16.839 23315 23443 E ViewRootImpl: Accessibility content change on non-UI thread. Future Android versions will throw an exception.
04-13 08:58:16.839 23315 23443 E ViewRootImpl: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1409

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1404

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=1432

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1436
