### ISSUE TITLE
java.lang.IllegalStateException: Already resumed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2139]
https://support.andbible.org/scp/tickets.php?id=1358

```
03-24 09:51:17.834 17066 17066 E AndroidRuntime: FATAL EXCEPTION: main
03-24 09:51:17.834 17066 17066 E AndroidRuntime: Process: net.bible.android.activity, PID: 17066
03-24 09:51:17.834 17066 17066 E AndroidRuntime: java.lang.IllegalStateException: Already resumed
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at net.bible.android.view.activity.StartupActivity$checkWebView$2$dlgBuilder$1.onClick(StartupActivity.kt:173)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6739)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
03-24 09:51:17.834 17066 17066 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tuomas2** [comment]
Duplicate of https://github.com/AndBible/and-bible/issues/3202
