### ISSUE TITLE
MyBible index creation fails

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2149]
I only found one issue with the myBible modules so far. The index creation for the search function fails. Index creation works for a myBible module that was manually converted using BibleMultiConverter and CrossWire Tools to a supported format (zip). Logcat attached. [logcat.txt.gz](https://github.com/AndBible/and-bible/files/8514224/logcat.txt.gz)

_Originally posted by @youphyun in https://github.com/AndBible/and-bible/issues/1473#issuecomment-1102775303_

**Comment by tuomas2** [comment]
@youphyun which module did it fail with? I have tested module creation and it works with some modules.

**Comment by tuomas2** [comment]
TODO: handle MyBible document tags properly in OsisToCanonicalTextSaxHandler.kt. I think that is being used for search indexing (if I remember correctly, I could be wrong...)

**Comment by youphyun** [comment]
I will send the module to your personal e-mail because of copyright.

**Comment by tuomas2** [comment]
```
05-01 10:47:45.553 16030 16030 E AndroidRuntime: Caused by: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/net.bible.android.activity/databases/andBibleDatabase.db' of size 2097152 due to error -12.
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.CursorWindow.nativeCreate(Native Method)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.CursorWindow.<init>(CursorWindow.java:139)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.CursorWindow.<init>(CursorWindow.java:120)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:231)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:270)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.database.BooleanSettingDao_Impl.byKey(BooleanSettingDao_Impl.java:103)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.database.BooleanSettingDao$DefaultImpls.get(Settings.kt:58)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.database.BooleanSettingDao_Impl.get(BooleanSettingDao_Impl.java:127)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.service.common.CommonUtils$AndBibleSettings.getBoolean(CommonUtils.kt:284)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.view.activity.base.ActivityBase.refreshScreenKeepOn(ActivityBase.kt:324)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.view.activity.base.ActivityBase.onCreate(ActivityBase.kt:100)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.view.activity.base.ActivityBase.onCreate(ActivityBase.kt:68)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at net.bible.android.view.activity.search.SearchIndex.onCreate(SearchIndex.kt:64)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7994)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7978)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
05-01 10:47:45.553 16030 16030 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
```

**Comment by tuomas2** [comment]
@youphyun try this https://github.com/AndBible/and-bible/releases/tag/build-643.2 (APK build will finish in ~10 minutes).
