### ISSUE TITLE
MyBible module crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2181]
https://support.andbible.org/scp/tickets.php?id=1496

```
06-15 16:39:03.395 10945 10945 E AndroidRuntime: Process: net.bible.android.activity, PID: 10945
06-15 16:39:03.395 10945 10945 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7811)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:515)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.service.sword.SqliteVerseBackendState.getBookMetaData(MyBibleBook.kt:128)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.service.sword.MyBibleBookKt.addMyBibleBook(MyBibleBook.kt:394)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.service.sword.MyBibleBookKt.addMyBibleBook$default(MyBibleBook.kt:391)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.service.sword.MyBibleBookKt.addManuallyInstalledMyBibleBooks(MyBibleBook.kt:420)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.service.common.CommonUtils.initializeApp(CommonUtils.kt:905)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.android.view.activity.base.ActivityBase.onCreate(ActivityBase.kt:91)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:214)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7955)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7944)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
06-15 16:39:03.395 10945 10945 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
```

**Comment by tuomas2** [comment]
asked module file for debugging
