### ISSUE TITLE
Crash in find all occurrences

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2211]
https://support.andbible.org/scp/tickets.php?id=1542

```
07-31 11:08:20.519 13976 13976 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.lucene.search.Searcher.search(org.apache.lucene.search.Query, org.apache.lucene.search.Collector)' on a null object reference
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneIndex.find(LuceneIndex.java:331)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.index.query.BaseQuery.find(BaseQuery.java:50)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.index.query.AndQuery.find(AndQuery.java:59)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneSearcher.search(LuceneSearcher.java:96)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.index.lucene.LuceneSearcher.search(LuceneSearcher.java:83)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.book.basic.AbstractBook.find(AbstractBook.java:127)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.crosswire.jsword.book.basic.AbstractBook.find(AbstractBook.java:112)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.checkStrongs(LinkControl.kt:270)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.showAllOccurrences(LinkControl.kt:242)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.openLink(BibleView.kt:841)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$BibleViewClient.shouldOverrideUrlLoading(BibleView.kt:876)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:46)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:339)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:186)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:334)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8399)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
07-31 11:08:20.519 13976 13976 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```

**Comment by timbze** [comment]
Duplicate of #2099 I think. But at least here we have the step that leads to the issue. If it's from "find all occurrences" maybe it's trying to search in a document without Strongs support or something...

**Comment by tuomas2** [comment]
> This issue is occuring regularly. Not able use the word search as the app closes as search is initiated

**Comment by tuomas2** [comment]
Duplicate of #2099
