### ISSUE TITLE
After downloading update to a document, crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2215]
https://support.andbible.org/scp/tickets.php?id=1549

```
08-05 08:11:42.064 20319 20319 E AndroidRuntime: java.lang.ExceptionInInitializerError
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.common.config.ChoiceFactory.getDataMap(ChoiceFactory.java:81)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.jsword.book.Defaults.refreshBooks(Defaults.java:459)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.jsword.book.Defaults$DefaultsBookListener.bookAdded(Defaults.java:545)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.jsword.book.AbstractBookList.fireBooksChanged(AbstractBookList.java:80)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.jsword.book.Books.addBook(Books.java:137)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.SwordBookDriver.registerNewBook(SwordBookDriver.java:239)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.jsword.book.install.sword.AbstractSwordInstaller.install(AbstractSwordInstaller.java:272)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at net.bible.service.download.DownloadManager.installBook(DownloadManager.kt:122)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at net.bible.service.download.RepoBase.downloadDocument(Repositories.kt:41)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at net.bible.android.control.download.DownloadQueue$addDocumentToDownloadQueue$2.invokeSuspend(DownloadQueue.kt:64)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.common.util.ClassUtil.forName(ClassUtil.java:53)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.common.util.PluginUtil.getImplementorsMap(PluginUtil.java:108)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	at org.crosswire.common.config.ChoiceFactory.<clinit>(ChoiceFactory.java:98)
08-05 08:11:42.064 20319 20319 E AndroidRuntime: 	... 18 more
```

**Comment by tuomas2** [comment]
User reported noticing this issue just once
