### ISSUE TITLE
Selection bug (Chinese)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2216]
https://support.andbible.org/scp/tickets.php?id=1554

> Tried to copy part of a verse in a Chinese edition. When I couldn't alter the size of the selection,  I tapped a nearby verse to exit the selection,  only to see the selection size change to sort of reflect my initial actions. I either tapped again or tried to change the selection size and the app crashed. 

```
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-5
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: Process: net.bible.android.activity, PID: 15316
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: java.lang.NullPointerException
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.createProcessTextIntent(BibleView.kt:403)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.createProcessTextIntentForResolveInfo(BibleView.kt:418)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.onPrepareActionMenu(BibleView.kt:459)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.access$onPrepareActionMenu(BibleView.kt:191)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$ActionModeCallback2.onPrepareActionMode(BibleView.kt:517)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:3061)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:157)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$onPrepareActionMenu$4$1.invokeSuspend(BibleView.kt:490)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> 08-08 10:49:09.293 15316 15401 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 
```

**Comment by timbze** [comment]
Another occurrence from support: https://support.andbible.org/scp/tickets.php?id=3442

Same NPE while the selection action menu is opening:

```
java.lang.NullPointerException
at net.bible.android.view.activity.page.BibleView.createProcessTextIntent(BibleView.kt:475)
at net.bible.android.view.activity.page.BibleView.createProcessTextIntentForResolveInfo(BibleView.kt:493)
at net.bible.android.view.activity.page.BibleView.onPrepareActionMenu(BibleView.kt:560)
```

This report is on an old build: **5.0.832** F-Droid (built 23/09/24), realme RMX2193, Android 11. The user was selecting text in John 15 KJV.

`createProcessTextIntent()` still uses `currentSelectionText!!` in current code, so the crash is likely still valid even though this particular dump is from 832.
