### ISSUE TITLE
Adding notes to an existing study note...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2218]
1) Create a new study note through the main menu.
2) try to tap on the + icon to add a note.

The app crashes.

See: https://support.andbible.org/scp/tickets.php?id=1572

**Comment by tuomas2** [comment]
```
08-19 21:54:50.610 29305 29305 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.navigation.GridChoosePassageChapter}: java.lang.ClassCastException: net.bible.service.sword.StudyPadKey cannot be cast to org.crosswire.jsword.passage.Verse
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: Caused by: java.lang.ClassCastException: net.bible.service.sword.StudyPadKey cannot be cast to org.crosswire.jsword.passage.Verse
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at net.bible.android.view.activity.navigation.GridChoosePassageChapter.getBibleChaptersButtonInfo(GridChoosePassageChapter.kt:109)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at net.bible.android.view.activity.navigation.GridChoosePassageChapter.onCreate(GridChoosePassageChapter.kt:89)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8270)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
08-19 21:54:50.610 29305 29305 E AndroidRuntime: 	... 12 more

```

**Comment by tuomas2** [comment]
Can't follow the instructions to reproduce i.e. can't reproduce. Can you make instructions a bit more specific?

**Comment by timbze** [comment]
I was able to reproduce by
1. Add a note to study pad
2. Click the Bible icon on the bottom right of the note to add a reference link
3. In the "Enter Bible reference" dialog, tap the "index finger" icon next to the "x for close" icon
4. Book chooser opens, click any book
5. -> Crash

**Comment by bvahedy** [comment]
Thanks Timmy for added instruction.
