### ISSUE TITLE
Error in "Easy setup"

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2260]
```
E/DownloadQueue: Error downloading StrongsGreek
    java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
        at androidx.collection.ArraySet.freeArrays(ArraySet.java:222)
        at androidx.collection.ArraySet.add(ArraySet.java:387)
        at net.bible.service.device.ProgressNotificationManager$initialise$1.workProgressed(ProgressNotificationManager.kt:73)
        at org.crosswire.common.progress.JobManager.fireWorkProgressed(JobManager.java:154)
        at org.crosswire.common.progress.Job.beginJob(Job.java:87)
        at org.crosswire.common.progress.Job.beginJob(Job.java:68)
        at org.crosswire.jsword.book.install.sword.AbstractSwordInstaller.install(AbstractSwordInstaller.java:246)
        at net.bible.service.download.DownloadManager.installBook(DownloadManager.kt:121)
        at net.bible.service.download.RepoBase.downloadDocument(Repositories.kt:40)
        at net.bible.android.control.download.DownloadQueue$addDocumentToDownloadQueue$2.invokeSuspend(DownloadQueue.kt:63)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/Dialogs: showErrorMesage message:An error has occurred

```

Happened in emulator, in API 33

**Comment by tuomas2** [comment]
Not a crash, just error message. Then re-tried downloading greek module and it worked.
