### ISSUE TITLE
Alpha: crash in search results

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2341]
Reproduce
1. Search and get into search results
2. Press home
3. Open lots of apps till Android memory closes AB 
4. Open AB - > crash 

https://support.andbible.org/scp/tickets.php?id=1659

```
11-04 10:32:59.519 27883 27883 E AndroidRuntime: FATAL EXCEPTION: main
11-04 10:32:59.519 27883 27883 E AndroidRuntime: Process: net.bible.android.activity, PID: 27883
11-04 10:32:59.519 27883 27883 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property originalSearchString has not been initialized
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at net.bible.android.control.search.SearchControl$Companion.getOriginalSearchString(SearchControl.kt:226)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at net.bible.android.view.activity.search.SearchItemAdapter.getView(SearchItemAdapter.kt:113)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2398)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2067)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:793)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.ListView.fillFromTop(ListView.java:855)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1810)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2195)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.View.layout(View.java:23143)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3681)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3140)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8649)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:780)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-04 10:32:59.519 27883 27883 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by timbze** [comment]
I feel like there have been similar versions of this bug for quite some time. I'm guessing it exists in stable too but haven't checked.

**Comment by tuomas2** [comment]
I also think so but this one is crashing in code that is in alpha only.
