### ISSUE TITLE
Crash when switching workspace

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2352]
https://support.andbible.org/scp/tickets.php?id=1664

```
11-10 13:15:34.561 17896 17896 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=94, result=-1, data=Intent { cmp=net.bible.android.activity/net.bible.android.view.activity.workspaces.WorkspaceSelectorActivity (has extras) }} to activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5590)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8653)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at org.crosswire.jsword.book.sword.SwordGenBook.getKey(SwordGenBook.java:202)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at net.bible.service.history.HistoryManager.restoreFrom(HistoryManager.kt:102)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at net.bible.android.control.page.window.WindowRepository.loadFromDb(WindowRepository.kt:408)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.setCurrentWorkspaceId(MainBibleActivity.kt:695)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onActivityResult(MainBibleActivity.kt:1310)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
11-10 13:15:34.561 17896 17896 E AndroidRuntime: 	... 11 more
```

**Comment by tuomas2** [comment]
Document was just upgraded via download manager. Related: 
- #2347
- #2215
