### ISSUE TITLE
Crash when pausing from workspace selector

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2417]
- Have at at least 2 workspaces.
- Go to workspace selector
- delete current workspace
- save
-> crash

https://support.andbible.org/scp/tickets.php?id=1720

```
12-14 23:40:56.702 30384 30384 I WinRepository: saveIntoDb
12-14 23:40:56.708 30384 30384 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-14 23:40:56.712 30384 30384 E AndroidRuntime: FATAL EXCEPTION: main
12-14 23:40:56.712 30384 30384 E AndroidRuntime: Process: net.bible.android.activity, PID: 30384
12-14 23:40:56.712 30384 30384 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {net.bible.android.activity/net.bible.android.view.activity.workspaces.WorkspaceSelectorActivity}: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: #################################################################
12-14 23:40:56.712 30384 30384 E AndroidRuntime: Error Code : 787 (SQLITE_CONSTRAINT_FOEIGNKEY)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: Caused By : Abort due to constraint violation.
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	(FOREIGN KEY constraint failed (code 787))
12-14 23:40:56.712 30384 30384 E AndroidRuntime: #################################################################
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4126)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4092)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4066)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4040)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(Unknown Source:0)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1717)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: #################################################################
12-14 23:40:56.712 30384 30384 E AndroidRuntime: Error Code : 787 (SQLITE_CONSTRAINT_FOEIGNKEY)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: Caused By : Abort due to constraint violation.
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	(FOREIGN KEY constraint failed (code 787))
12-14 23:40:56.712 30384 30384 E AndroidRuntime: #################################################################
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:953)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:97)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at net.bible.android.database.WorkspaceDao_Impl.insertHistoryItems(WorkspaceDao_Impl.java:1494)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at net.bible.android.database.WorkspaceDao$DefaultImpls.updateHistoryItems(WorkspaceDao.kt:109)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at net.bible.android.database.WorkspaceDao_Impl.updateHistoryItems(WorkspaceDao_Impl.java:1566)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at net.bible.android.control.page.window.WindowRepository.saveIntoDb(WindowRepository.kt:342)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at net.bible.android.view.activity.base.ActivityBase.onPause(ActivityBase.kt:214)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7408)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1414)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4115)
12-14 23:40:56.712 30384 30384 E AndroidRuntime: 	... 11 more

```

**Comment by tuomas2** [comment]
667 prod version

**Comment by tuomas2** [comment]
also https://support.andbible.org/scp/tickets.php?id=1719
