### ISSUE TITLE
Calc crashes when starting to speak

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2477]
https://support.andbible.org/scp/tickets.php?id=1767
```
01-18 10:42:12.027  6266  6266 E AndroidRuntime: FATAL EXCEPTION: main
01-18 10:42:12.027  6266  6266 E AndroidRuntime: Process: com.app.calculator, PID: 6266
01-18 10:42:12.027  6266  6266 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2155)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.app.ActivityThread.access$2900(ActivityThread.java:315)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8751)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
01-18 10:42:12.027  6266  6266 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by bvahedy** [comment]
Verified fixed in 677 build.
