### ISSUE TITLE
Setting up Kindle Android 5 for sync not working

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2620]
**Describe the bug**
The signin screen never shows up. I do have Play services but not sure that it's working 100% (Play store and Gmail do work)

**Bug was found on AndBible version**
Build alpha-686.8

**Note:**
I do have 2 Google accounts on the tablet

I don't know if below error indicates that it's trying to use the wrong Google account on my tablet, or why I am not getting the selector to select which Google account I want to use.

**Log**:
```
06-10 08:42:43.272 11624 11644 E GoogleDrive: Error signing in
06-10 08:42:43.272 11624 11644 E GoogleDrive: com.google.android.gms.common.api.ApiException: 10: Caller not whitelisted to call this API.
06-10 08:42:43.272 11624 11644 E GoogleDrive: 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(SourceFile:0)
06-10 08:42:43.272 11624 11644 E GoogleDrive: 	at com.google.android.gms.internal.auth-api.zbau.zbb(SourceFile)
06-10 08:42:43.272 11624 11644 E GoogleDrive: 	at com.google.android.gms.internal.auth-api.zbx.zba(SourceFile)
06-10 08:42:43.272 11624 11644 E GoogleDrive: 	at com.google.android.gms.internal.auth-api.zbb.onTransact(SourceFile)
06-10 08:42:43.272 11624 11644 E GoogleDrive: 	at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by tuomas2** [comment]
I also tried on Android 5 device (Samsung tablet) and getting this message in log:
```
06-10 18:58:46.306  8224  8964 W GoogleApiManager: com.google.android.gms.internal.auth-api.zbaz could not execute call because it requires feature (auth_api_credentials_begin_sign_in, 8).
```

**Comment by tuomas2** [comment]
And Android 6 (Sony device) fails with ApiException: 8 

```
06-10 12:38:28.280 28203 28270 E GoogleDrive: Error signing in
06-10 12:38:28.280 28203 28270 E GoogleDrive: com.google.android.gms.common.api.ApiException: 8: 
06-10 12:38:28.280 28203 28270 E GoogleDrive: 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(SourceFile:0)
06-10 12:38:28.280 28203 28270 E GoogleDrive: 	at com.google.android.gms.internal.auth-api.zbau.zbb(SourceFile)
06-10 12:38:28.280 28203 28270 E GoogleDrive: 	at com.google.android.gms.internal.auth-api.zbx.zba(SourceFile)
06-10 12:38:28.280 28203 28270 E GoogleDrive: 	at com.google.android.gms.internal.auth-api.zbb.onTransact(SourceFile)
06-10 12:38:28.280 28203 28270 E GoogleDrive: 	at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by tuomas2** [comment]
I have now applied for official google drive permission, and even if it is not yet granted, non-whitelisted people can already use it. I just tried it with one account that is not listed.

**Comment by tuomas2** [comment]
I have a feeling that we might not get all older devices work with Google Drive sync. If that is the case, we can hide the feature from those devices.

**Comment by tuomas2** [comment]
I have successfully tried it on Android 8+ devices. Android 7 coudn't test yet.

**Comment by timbze** [comment]
Don't think we need to put any more effort into supporting such old devices.
