### ISSUE TITLE
Sync issue: UNIQUE constraint failed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2701]
https://support.andbible.org/scp/tickets.php?id=1997
```
08-06 10:53:22.466 30631  1309 E DeviceSync: downloadAndApplyNewPatches failed due to error
08-06 10:53:22.466 30631  1309 E DeviceSync: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: SyncStatus.sourceDevice, SyncStatus.patchNumber (code 1555)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:826)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at io.requery.android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:798)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at io.requery.android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:93)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:85)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at net.bible.android.database.SyncDao_Impl.addStatuses(SyncDao_Impl.java:159)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at net.bible.service.cloudsync.CloudSync$downloadAndApplyNewPatches$2.invokeSuspend(CloudSync.kt:500)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
08-06 10:53:22.466 30631  1309 E DeviceSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by tuomas2** [comment]
Cause: patch file "260.2.sqlite3.gz" from the save device is in drive 2 times. Same amount of bytes.

**Comment by tuomas2** [comment]
Why file is added twice in the first place? createAndUploadNewPatch must have crashed in upload phase such a way that patch file is successfully transferred. In that case next sync will create (possibly) another patch file with same content.
