### ISSUE TITLE
Crash probably in startup

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2774]
```
   Caused by: net.bible.service.db.DataBaseNotReady
                                                                                                    	at net.bible.service.db.DatabaseContainer$Companion.getInstance(DatabaseContainer.kt:262)
                                                                                                    	at net.bible.service.download.DownloadManager.getCustomRepositoryDao(DownloadManager.kt:48)
                                                                                                    	at net.bible.service.download.DownloadManager.refreshInstallManager(DownloadManager.kt:54)
                                                                                                    	at net.bible.service.download.DownloadManager.<init>(DownloadManager.kt:74)
                                                                                                    	at net.bible.android.view.activity.download.DownloadActivity.<init>(DownloadActivity.kt:104)
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2060
