### ISSUE TITLE
Issue migrating ReadingPlan table

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2791]
https://support.andbible.org/scp/tickets.php?id=2065

```
08-31 12:18:25.136  1829  1829 E AndroidRuntime: FATAL EXCEPTION: main
08-31 12:18:25.136  1829  1829 E AndroidRuntime: Process: net.bible.android.activity, PID: 1829
08-31 12:18:25.136  1829  1829 E AndroidRuntime: android.database.sqlite.SQLiteException: no such column: _id (code 1 SQLITE_ERROR): , while compiling: INSERT INTO ReadingPlanMap SELECT _id, randomblob(16) FROM readingplan
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1074)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:679)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2086)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2008)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.kt:246)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.database.migrations.DatabaseSplitMigrations.readingPlanDb(DatabaseSplitMigrations.kt:166)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.database.migrations.DatabaseSplitMigrations.migrateAll(DatabaseSplitMigrations.kt:47)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.service.db.DatabaseContainer.migrateOldDatabaseIfNeeded(DatabaseContainer.kt:96)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.service.db.DatabaseContainer.<init>(DatabaseContainer.kt:73)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.service.db.DatabaseContainer$Companion.getInstance(DatabaseContainer.kt:264)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromInputStream$2$1$1.invokeSuspend(BackupControl.kt:199)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromInputStream$2$1$1.invoke(BackupControl.kt:0)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromInputStream$2$1$1.invoke(BackupControl.kt:0)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromInputStream$2.invokeSuspend(BackupControl.kt:183)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromInputStream$2.invoke(BackupControl.kt:0)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromInputStream$2.invoke(BackupControl.kt:0)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.restoreOldMonolithicDatabaseFromInputStream(BackupControl.kt:159)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl.access$restoreOldMonolithicDatabaseFromInputStream(BackupControl.kt:100)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at net.bible.android.control.backup.BackupControl$restoreOldMonolithicDatabaseFromFileInputStreamWithUI$2.invokeSuspend(BackupControl.kt:710)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
08-31 12:18:25.136  1829  1829 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by tuomas2** [comment]
- [x] clean up temporary tables before creating them (could be there if migration has failed previous time)

**Comment by tuomas2** [comment]
Need users db to investigate this further.

**Comment by tuomas2** [comment]
Tested with  user-provided DB but could not reproduce (db was migrated successfully).

**Comment by tuomas2** [comment]
Asking user if issue still exists

**Comment by tuomas2** [comment]
No reply -> closing
