### ISSUE TITLE
App Background Issue

### ISSUE THREAD

**Issue by GauravCreed** [AndBible/and-bible#280]
Hi @alerque 

it is a great app when i install,i found small bug.
When i open and spend some time on app, after the app is on background stack and then open some other app installed in device, now there is a bug.

on recent task get back to app there is error on app like
![device-2019-02-06-152148](https://user-images.githubusercontent.com/13447384/52333352-0a81a000-2a23-11e9-80f0-ea9de6d79b51.png)

Logcat like...
`Error getting versification for Book
                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'org.crosswire.jsword.versification.Versification org.crosswire.jsword.book.basic.AbstractPassageBook.getVersification()' on a null object reference
                                                      at net.bible.android.control.page.VersePage.getVersification(VersePage.java:41)
                                                      at net.bible.android.control.page.CurrentBiblePage.GetKey(CurrentBiblePage.java:173)
                                                      at net.bible.android.control.page.CurrentBiblePage.getSingleKey(CurrentBiblePage.java:159)
                                                      at net.bible.android.control.document.DocumentControl.getRequiredVerseSuggestions(DocumentControl.java:172)
                                                      at net.bible.android.control.document.DocumentControl.getSuggestedCommentaries(DocumentControl.java:138)
                                                      at net.bible.android.view.activity.page.actionbar.CommentaryActionBarButton.getDocumentSuggested(CommentaryActionBarButton.java:28)
                                                      at net.bible.android.view.activity.base.actionbar.QuickDocumentChangeToolbarButton.update(QuickDocumentChangeToolbarButton.java:47)
                                                      at net.bible.android.view.activity.base.actionbar.QuickActionButton.update(QuickActionButton.java:56)
                                                      at net.bible.android.view.activity.page.actionbar.BibleActionBarManager$2.run(BibleActionBarManager.java:90)
                                                      at android.app.Activity.runOnUiThread(Activity.java:6282)
                                                      at net.bible.android.view.activity.base.CurrentActivityHolder.runOnUiThread(CurrentActivityHolder.java:72)
                                                      at net.bible.android.view.activity.page.actionbar.BibleActionBarManager.updateButtons(BibleActionBarManager.java:84)
                                                      at net.bible.android.view.activity.base.CustomTitlebarActivityBase.updateActionBarButtons(CustomTitlebarActivityBase.java:114)
                                                      at net.bible.android.view.activity.page.MainBibleActivity.onEventMainThread(MainBibleActivity.java:626)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
                                                      at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:433)
                                                      at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
                                                      at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
                                                      at de.greenrobot.event.EventBus.post(EventBus.java:263)
                                                      at net.bible.android.control.PassageChangeMediator.contentChangeFinished(PassageChangeMediator.java:91)
                                                      at net.bible.android.control.BibleContentManager$UpdateMainTextTask.onPostExecute(BibleContentManager.java:77)
                                                      at net.bible.android.control.BibleContentManager$UpdateMainTextTask.onPostExecute(BibleContentManager.java:68)
                                                      at android.os.AsyncTask.finish(AsyncTask.java:695)
                                                      at android.os.AsyncTask.access$600(AsyncTask.java:180)
                                                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                                                      at android.os.Handler.dispatchMessage(Handler.java:106)
                                                      at android.os.Looper.loop(Looper.java:193)
                                                      at android.app.ActivityThread.main(ActivityThread.java:6762)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)`

**Comment by bvahedy** [comment]
Can you tell us what device and language you are using. And what app did you switch to when you put andbible in the background?

**Comment by GauravCreed** [comment]
Hi

I am using Redmi MI A1 device with OS 9.0,

Yes exacteally  i open my app and refar then put in background, then after spend some time on other app , then get back to my bible app, at that time i get this error.

Thanks.

**Comment by bvahedy** [comment]
Tuomas,  can you reproduce this issue, or can you tell from the code why
it's happening?

**Comment by tuomas2** [comment]
I'll try to figure out. Provided stack trace will probably help.

**Comment by GauravCreed** [comment]
Hey

Here is stack trace what you need ...


`Error getting versification for Book
                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'org.crosswire.jsword.versification.Versification org.crosswire.jsword.book.basic.AbstractPassageBook.getVersification()' on a null object reference
                                                        at net.bible.android.control.page.VersePage.getVersification(VersePage.java:41)
                                                        at net.bible.android.control.page.CurrentBiblePage.GetKey(CurrentBiblePage.java:173)
                                                        at net.bible.android.control.page.CurrentBiblePage.getSingleKey(CurrentBiblePage.java:159)
                                                        at net.bible.android.control.document.DocumentControl.getRequiredVerseSuggestions(DocumentControl.java:172)
                                                        at net.bible.android.control.document.DocumentControl.getSuggestedCommentaries(DocumentControl.java:138)
                                                        at net.bible.android.view.activity.page.actionbar.CommentaryActionBarButton.getDocumentSuggested(CommentaryActionBarButton.java:28)
                                                        at net.bible.android.view.activity.base.actionbar.QuickDocumentChangeToolbarButton.update(QuickDocumentChangeToolbarButton.java:47)
                                                        at net.bible.android.view.activity.base.actionbar.QuickActionButton.update(QuickActionButton.java:56)
                                                        at net.bible.android.view.activity.page.actionbar.BibleActionBarManager$2.run(BibleActionBarManager.java:90)
                                                        at android.app.Activity.runOnUiThread(Activity.java:6282)
                                                        at net.bible.android.view.activity.base.CurrentActivityHolder.runOnUiThread(CurrentActivityHolder.java:72)
                                                        at net.bible.android.view.activity.page.actionbar.BibleActionBarManager.updateButtons(BibleActionBarManager.java:84)
                                                        at net.bible.android.view.activity.base.CustomTitlebarActivityBase.updateActionBarButtons(CustomTitlebarActivityBase.java:114)
                                                        at net.bible.android.view.activity.page.MainBibleActivity.onEventMainThread(MainBibleActivity.java:626)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
                                                        at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:433)
                                                        at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
                                                        at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
                                                        at de.greenrobot.event.EventBus.post(EventBus.java:263)
                                                        at net.bible.android.control.PassageChangeMediator.contentChangeFinished(PassageChangeMediator.java:91)
                                                        at net.bible.android.control.BibleContentManager$UpdateMainTextTask.onPostExecute(BibleContentManager.java:77)
                                                        at net.bible.android.control.BibleContentManager$UpdateMainTextTask.onPostExecute(BibleContentManager.java:68)
                                                        at android.os.AsyncTask.finish(AsyncTask.java:695)
                                                        at android.os.AsyncTask.access$600(AsyncTask.java:180)
                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                                                        at android.os.Handler.dispatchMessage(Handler.java:106)
                                                        at android.os.Looper.loop(Looper.java:193)
                                                        at android.app.ActivityThread.main(ActivityThread.java:6762)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by GauravCreed** [comment]
Here is lot more for fixing bug...

![error code](https://user-images.githubusercontent.com/13447384/52469941-dccb6100-2bb2-11e9-8ba1-bf7f1dfa8aa7.PNG)


This is UpdateTextTask AsyncTask to getting text from KJV Bible,
I hope it will help you to resolve issue.


Thanks.

**Comment by tuomas2** [comment]
@GauravCreed if you are developer, why not try to make pull request to fix this?  :)

**Comment by GauravCreed** [comment]
@tuomas2 

I am trying to resolve this issue since last one week, but i am not able to resolve this then after open this  issue in your repo.

**Comment by tuomas2** [comment]
@GauravCreed Stack trace reveals that you are using some rather old version (DocumentControl.java does not exist and has been replaced by DocumentControl.kt). Could you specify which one and test if the issue still exists on the latest version?

**Comment by tuomas2** [comment]
Please re-open if this is reproducible with the latest version.
