### ISSUE TITLE
Crash in requestMoreToEnd (epub)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2831]
https://support.andbible.org/scp/tickets.php?id=2088

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
at net.bible.android.control.page.CachedKeyPage.getCachedGlobalKeyList(CachedKeyPage.kt:59)
at net.bible.android.control.page.CachedKeyPage.findIndexOf(CachedKeyPage.kt:101)
at net.bible.android.control.page.CachedKeyPage.getKeyPlus(CachedKeyPage.kt:87)
at net.bible.android.view.activity.page.BibleView.requestMoreToEnd(BibleView.kt:1866)
at net.bible.android.view.activity.page.BibleJavascriptInterface.requestMoreToEnd(BibleJavascriptInterface.kt:133)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loopOnce(Looper.java:186)
at android.os.Looper.loop(Looper.java:313)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by tuomas2** [comment]
Can't reproduce
