### ISSUE TITLE
TTS fails due to Service.startForeground() not allowed due to mAllowStartForeground false

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2843]
https://support.andbible.org/scp/tickets.php?id=2097

```
09-06 17:38:23.381 17634 17634 E AndroidRuntime: java.lang.RuntimeException: Unable to start service net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService@a353fef with Intent { act=action_start_service cmp=net.bible.android.activity/net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service net.bible.android.activity/net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4673)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service net.bible.android.activity/net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Parcel.readParcelable(Parcel.java:4778)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6079)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:743)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService.start(TextToSpeechNotificationManager.kt:101)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService.onStartCommand(TextToSpeechNotificationManager.kt:84)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
09-06 17:38:23.381 17634 17634 E AndroidRuntime: 	... 9 more
```

**Comment by tuomas2** [comment]
https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows
