### ISSUE TITLE
Crash in optimizing epub

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2869]
https://support.andbible.org/scp/tickets.php?id=2102

```
09-17 10:07:34.645 13128 13128 E AndroidRuntime: FATAL EXCEPTION: main
09-17 10:07:34.645 13128 13128 E AndroidRuntime: Process: net.bible.android.activity, PID: 13128
09-17 10:07:34.645 13128 13128 E AndroidRuntime: java.lang.NullPointerException
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.service.sword.epub.EpubBackendState.fileForOriginalId(EpubBackendState.kt:123)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.service.sword.epub.EpubOptimizationKt.readOriginal(EpubOptimization.kt:41)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.service.sword.epub.EpubOptimizationKt.optimizeEpub(EpubOptimization.kt:230)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.service.sword.epub.EpubBackendState.<init>(EpubBackendState.kt:204)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.service.sword.epub.EpubBookKt.addEpubBook(EpubBook.kt:149)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.service.sword.epub.EpubBookKt.addManuallyInstalledEpubBooks(EpubBook.kt:172)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at net.bible.android.view.activity.installzip.InstallZip$installEpub$2.invokeSuspend(InstallZip.kt:525)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
09-17 10:07:34.645 13128 13128 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6457496, Dispatchers.Main.immediate]
```

**Comment by tuomas2** [comment]
asked for epub
