### ISSUE TITLE
Sync crash in Android 13 ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2877]
```
Device info:
Version: 5.0.729-beta#1fe1b8d07 googleplay standard release (built 14/09/23 17:15:14)
Android version: 13
Android SDK version: 33
Manufacturer: motorola
Model: moto g stylus 5G (2022)
Storage Mb free: 193971
WebView version: 118.0.5993.21
SQLITE version: 3.42.0
Used heap memory in Mb: 14
Max heap memory in Mb: 256

Exception:
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service net.bible.android.activity/net.bible.service.cloudsync.SyncService
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
at android.os.Parcel.readParcelableInternal(Parcel.java:4833)
at android.os.Parcel.readParcelable(Parcel.java:4795)
at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
at android.os.Parcel.createException(Parcel.java:3012)
at android.os.Parcel.readException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2937)
at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5896)
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1914)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1890)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at net.bible.service.cloudsync.CloudSync$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
at net.bible.service.cloudsync.CloudSync.start(CloudSync.kt:332)
at net.bible.android.view.activity.page.MainBibleActivity.synchronize(MainBibleActivity.kt:1366)
at net.bible.android.view.activity.page.MainBibleActivity.startSync(MainBibleActivity.kt:1328)
at net.bible.android.view.activity.page.MainBibleActivity.access$startSync(MainBibleActivity.kt:163)
at net.bible.android.view.activity.page.MainBibleActivity$onEvent$2.invokeSuspend(MainBibleActivity.kt:1384)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c2f6e99, Dispatchers.IO]

```
https://support.andbible.org/scp/tickets.php?id=2111

**Comment by tuomas2** [comment]
I also have Android 13 and it has not crashed like this so far.

**Comment by tuomas2** [comment]
User also has not experienced this any more

**Comment by timbze** [comment]
Another crash (user did not notice crash). https://support.andbible.org/scp/tickets.php?id=2164

**Comment by timbze** [comment]
May also be Google bug. https://issuetracker.google.com/issues/229000935?pli=1

#2843 could be same root issue

**Comment by tuomas2** [comment]
Yep it is weird bug because this sort of bug I would assume would appear in all devices of a specific android version.

**Comment by tuomas2** [comment]
or is it timing issue? startForeground could be run after app is already in background (it is triggered in `MainBibleActivity:onEvent(event: AppToBackgroundEvent)`.

**Comment by tuomas2** [comment]
I got this or similar sync-related issue in my waydroid device now
https://support.andbible.org/scp/tickets.php?id=2169

Not easily reproducible there though.

**Comment by tuomas2** [comment]
here too: https://support.andbible.org/scp/tickets.php?id=2184 (though this issue possibly has 2 separate errors)

**Comment by tuomas2** [comment]
Hmm maybe this one is interesting, could help in reproducing:

> Crash when changing orientation of phone.

https://support.andbible.org/scp/tickets.php?id=2190

...though exception is ForegroundServiceDidNotStartInTimeException here

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2197

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2209

**Comment by tuomas2** [comment]
I'm muting this error for now as it does not seem that fatal and there are several bug reports coming because of this.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2224

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2227
