### ISSUE TITLE
Crash: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2946]
# Possibly re-installing helps

> I created a backup, then reinstalled, and everything is working just fine.

https://support.andbible.org/scp/tickets.php?id=2158

```
Device info:
Version: 5.0.728-beta#b046948a0 googleplay standard release (built 12/09/23 20:43:16)
Android version: 12
Android SDK version: 31
Manufacturer: samsung
Model: SM-N975U
Storage Mb free: 373066
WebView version: 116.0.5845.172
SQLITE version: 3.42.0
Used heap memory in Mb: 7
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6347)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
at android.view.ViewGroup.addViewInner(ViewGroup.java:6084)
at android.view.ViewGroup.addView(ViewGroup.java:5903)
at android.view.ViewGroup.addView(ViewGroup.java:5875)
at net.bible.android.view.activity.page.screen.BibleFrame.build(BibleFrame.kt:141)
at net.bible.android.view.activity.page.screen.BibleFrame.(BibleFrame.kt:122)
at net.bible.android.view.activity.page.screen.SplitBibleArea.updateWindows(SplitBibleArea.kt:219)
at net.bible.android.view.activity.page.screen.SplitBibleArea.update(SplitBibleArea.kt:171)
at net.bible.android.view.activity.page.screen.DocumentViewManager.buildWebViews(DocumentViewManager.kt:77)
at net.bible.android.view.activity.page.screen.DocumentViewManager.buildView(DocumentViewManager.kt:83)
at net.bible.android.view.activity.page.screen.DocumentViewManager.buildView$default(DocumentViewManager.kt:82)
at net.bible.android.view.activity.page.MainBibleActivity.setupUi(MainBibleActivity.kt:319)
at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:274)
at android.app.Activity.performCreate(Activity.java:8290)
at android.app.Activity.performCreate(Activity.java:8270)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
... 15 more
 
```

**Comment by tuomas2** [comment]
`10-20 12:03:18.970 31553 31553 I Base-MainBibleActivity: onCreate: loading state: Bundle[{wasPaused=false, android:viewHierarchyState=Bundle[{android:views={16908290=android.view.AbsSavedState$1@5d13e8f, 2131296313=android.view.AbsSavedState$1@5d13e8f, 2131296324=android.view.AbsSavedState$1@5d13e8f, 2131296373=android.view.AbsSavedState$1@5d13e8f, 2131296375=android.view.AbsSavedState$1@5d13e8f, 2131296378=android.view.AbsSavedState$1@5d13e8f, 2131296394=android.view.AbsSavedState$1@5d13e8f, 2131296411=android.view.AbsSavedState$1@5d13e8f, 2131296415=android.view.AbsSavedState$1@5d13e8f, 2131296450=android.view.AbsSavedState$1@5d13e8f, 2131296453=android.view.AbsSavedState$1@5d13e8f, 2131296462=androidx.coordinatorlayout.widget.CoordinatorLayout$SavedState@b6cefc1, 2131296508=androidx.recyclerview.widget.RecyclerView$SavedState@eb51366, 2131296520=android.view.AbsSavedState$1@5d13e8f, 2131296526=android.view.AbsSavedState$1@5d13e8f, 2131296542=androidx.drawerlayout.widget.DrawerLayout$SavedState@5e686a7, 2131296588=android.view.AbsSavedState$1@5d13e8f, 2131296612=android.view.AbsSavedState$1@5d13e8f, 2131296613=android.view.AbsSavedState$1@5d13e8f, 2131296620=android.view.AbsSavedState$1@5d13e8f, 2131296683=android.view.AbsSavedState$1@5d13e8f, 2131296684=android.view.AbsSavedState$1@5d13e8f, 2131296758=com.google.android.material.navigation.NavigationView$SavedState@c586754, 2131296772=android.view.AbsSavedState$1@5d13e8f, 2131296796=android.view.AbsSavedState$1@5d13e8f, 2131296803=android.view.AbsSavedState$1@5d13e8f, 2131296804=android.view.AbsSavedState$1@5d13e8f, 2131296820=android.view.AbsSavedState$1@5d13e8f, 2131296829=android.view.AbsSavedState$1@5d13e8f, 2131296863=android.view.AbsSavedState$1@5d13e8f, 2131296864=HorizontalScrollView.SavedState{17c6fd scrollPosition=0}, 2131296869=android.view.AbsSavedState$1@5d13e8f, 2131296895=android.view.AbsSavedState$1@5d13e8f, 2131296962=android.view.AbsSavedState$1@5d13e8f, 2131296966=android.view.AbsSavedState$1@5d13e8f, 2131296969=android.view.AbsSavedState$1@5d13e8f, 2131296971=android.widget.ProgressBar$SavedState@d6efff2, 2131296994=android.view.AbsSavedState$1@5d13e8f, 2131296998=android.view.AbsSavedState$1@5d13e8f, 2131297000=android.view.AbsSavedState$1@5d13e8f, 2131297010=android.view.AbsSavedState$1@5d13e8f, 2131297013=android.view.AbsSavedState$1@5d13e8f, 2131297080=android.view.AbsSavedState$1@5d13e8f, 2131297082=android.view.AbsSavedState$1@5d13e8f, 2131297084=android.view.AbsSavedState$1@5d13e8f, 2131297102=android.view.AbsSavedState$1@5d13e8f, 2131297131=android.view.AbsSavedState$1@5d13e8f, 2131297132=android.view.AbsSavedState$1@5d13e8f}}], returningFromCalculator=false, androidx.lifecycle.BundlableSavedStateRegistry.key=Bundle[{androidx.lifecycle.internal.SavedStateHandlesProvider=Bundle[{}]}], doNotMarkPaused=false, android:lastAutofillId=1073741834, android:fragments=android.app.FragmentManagerState@16ae643}]`

Is Android saving view hierarchy somehow to state bundle? And then somehow try to restore that?

**Comment by tuomas2** [comment]
The app crashed when I clicked on a search result. 

https://support.andbible.org/scp/tickets.php?id=2161

**Comment by tuomas2** [comment]
>  The crashes are occurring when I click on a search result. Every time I do a search it either crashes when I click on any result, or it goes back to whatever verse I was on before doing the search. It never goes to the verse that I click on.

**Comment by tuomas2** [comment]
> I created a backup, then reinstalled, and everything is working just fine.

**Comment by tuomas2** [comment]
This happened after coming from settings screen, after changing language

https://support.andbible.org/scp/tickets.php?id=2170

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2238

> Switch apps, going to And bible from GMail.

**Comment by tuomas2** [comment]
> I created a backup, then reinstalled, and everything is working just fine. 
https://support.andbible.org/scp/tickets.php?id=2158

Hmm, interesting.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2356

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2391

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2508

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2840
