### ISSUE TITLE
Crash: RuntimeException: Unsupported category

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3023]
```
Device info:
Version: 5.0.753#a22994915 googleplay standard release (built 04/11/23 09:52:30)
Android version: 13
Android SDK version: 33
Manufacturer: samsung
Model: SM-A045M
Storage Mb free: 57935
WebView version: 120.0.6099.4
SQLITE version: 3.42.0
Used heap memory in Mb: 5
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { cmp=net.bible.android.activity/net.bible.android.view.activity.navigation.ChooseDocument (has extras) }} to activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.RuntimeException: Unsupported category
at android.app.ActivityThread.deliverResults(ActivityThread.java:5994)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.RuntimeException: Unsupported category
at net.bible.android.control.page.CurrentPageManagerKt.getDocumentCategory(CurrentPageManager.kt:72)
at net.bible.android.control.page.CurrentPageManager.getBookPage(CurrentPageManager.kt:237)
at net.bible.android.control.page.CurrentPageManager.setCurrentDocument(CurrentPageManager.kt:165)
at net.bible.android.control.document.DocumentControl.changeDocument(DocumentControl.kt:143)
at net.bible.android.view.activity.page.MainBibleActivity.onActivityResult(MainBibleActivity.kt:1628)
at android.app.Activity.dispatchActivityResult(Activity.java:8951)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2192

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2198

**Comment by tuomas2** [comment]
Happens after choosing RefParser in book selector

**Comment by tuomas2** [comment]
or FontPack. Should not allow opening them.
