### ISSUE TITLE
Crash: UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/net.bible.android.activity-2/base.apk!/lib/arm64-v8a/libsqlite3x.so" segment 1: Permission denied

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3025]
https://support.andbible.org/scp/tickets.php?id=2195

```
Geräteinfo:
Version: 5.0.742#cb7890fb1 googleplay standard release (built 02/11/23 15:00:54)
Android version: 9
Android SDK version: 28
Manufacturer: LGE
Model: LG-H930
Storage Mb free: 14785
WebView version: 119.0.6045.66
SQLITE version:
Used heap memory in Mb: 4
Max heap memory in Mb: 256

Exception:
java.lang.NoClassDefFoundError: io.requery.android.database.sqlite.SQLiteDatabase
at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(Unknown Source:0)
at net.bible.service.db.DatabaseContainer.backupOldDatabase(DatabaseContainer.kt:216)
at net.bible.service.db.DatabaseContainer.backupDatabaseIfNeeded(DatabaseContainer.kt:208)
at net.bible.service.db.DatabaseContainer.(DatabaseContainer.kt:72)
at net.bible.service.db.DatabaseContainer$Companion.getInstance(DatabaseContainer.kt:277)
at net.bible.android.view.activity.StartupActivity$initializeDatabase$2.invokeSuspend(StartupActivity.kt:229)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@45dde84, Dispatchers.Main.immediate]
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/net.bible.android.activity-2/base.apk!/lib/arm64-v8a/libsqlite3x.so" segment 1: Permission denied
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1669)
at io.requery.android.database.sqlite.SQLiteDatabase.(SQLiteDatabase.java:91)
at io.requery.android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(Unknown Source:0)
at net.bible.android.BibleApplication.logSqliteVersion(BibleApplication.kt:168)
at net.bible.android.BibleApplication.onCreate(BibleApplication.kt:141)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6169)
at android.app.ActivityThread.access$1100(ActivityThread.java:208)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:205)
at android.app.ActivityThread.main(ActivityThread.java:6991)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by tuomas2** [comment]
> Thank you for your support! I followed your advice and transfered the app back to the internel storage. Now its working perfect again. 

https://support.andbible.org/scp/tickets.php?id=2251
