### ISSUE TITLE
ZipException: duplicate entry: mods.d/strongsgreek.conf

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3039]
https://support.andbible.org/scp/tickets.php?id=2213

```
Device info:
Version: 5.0.742#cb7890fb1 googleplay standard release (built 02/11/23 15:00:54)
Android version: 13
Android SDK version: 33
Manufacturer: samsung
Model: SM-G998U1
Storage Mb free: 174071
WebView version: 118.0.5993.112
SQLITE version: 3.42.0
Used heap memory in Mb: 12
Max heap memory in Mb: 256

Exception:
java.util.zip.ZipException: duplicate entry: mods.d/strongsgreek.conf
at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:234)
at net.bible.android.control.backup.BackupControl.createModulesZip$addFile(BackupControl.kt:333)
at net.bible.android.control.backup.BackupControl.access$createModulesZip$addFile(BackupControl.kt:100)
at net.bible.android.control.backup.BackupControl$createModulesZip$2.invokeSuspend(BackupControl.kt:370)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@71f1ce, Dispatchers.Main.immediate]
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2239
