### ISSUE TITLE
Clicked Eastons Bible dictionary crashed (java.lang.Exception: Error in webview-js)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3056]
```
Device info:
Version: 5.0.755#27acfd2f5 googleplay standard release (built 10/11/23 18:17:01)
Android version: 9
Android SDK version: 28
Manufacturer: samsung
Model: SM-T380
Storage Mb free: 3389
WebView version: 119.0.6045.135
SQLITE version: 3.42.0
Used heap memory in Mb: 19
Max heap memory in Mb: 256

Exception:
java.lang.Exception: Error in webview-js
at net.bible.android.control.link.LinkControl.errorLink(LinkControl.kt:122)
at net.bible.android.view.activity.page.BibleView.openLink(BibleView.kt:1034)
at net.bible.android.view.activity.page.BibleView$BibleViewClient.shouldOverrideUrlLoading(BibleView.kt:1065)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-604513520:93)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:326)
at android.os.Looper.loop(Looper.java:183)
at android.app.ActivityThread.main(ActivityThread.java:7266)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Opened bible
Ckicked Eastons Bible dictionary
Crashed

**Comment by tuomas2** [comment]
Opened Bible app
Opened Book
Closed the app
Opened app 
Got Book error
Then had to reopen the Bible version I use.

https://support.andbible.org/scp/tickets.php?id=2231

**Comment by tuomas2** [comment]
similar 
https://support.andbible.org/scp/tickets.php?id=2233

**Comment by tuomas2** [comment]
771: https://support.andbible.org/scp/tickets.php?id=2255

```
11-24 12:09:26.651 26438 26699 I BibleView[c234c] WIN: Loading document:ISBE key:null
11-24 12:09:26.651 26438 26699 E CurrentPage: Key was null, giving ErrorDocument
```

Next version will have more logging for this.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2258
>  I opened app from settings because I couldn't open in the usual way

**Comment by tuomas2** [comment]
Strongs: https://support.andbible.org/scp/tickets.php?id=2301
