### ISSUE TITLE
NoSuchVerseException: Cannot understand OSISREF as a chapter or verse

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3058]
```
Device info:
Version: 5.0.762#9bdc35e58 googleplay standard release (built 16/11/23 10:21:03)
Android version: 13
Android SDK version: 33
Manufacturer: Vortex
Model: HD65
Storage Mb free: 38097
WebView version: 119.0.6045.66
SQLITE version: 3.42.0
Used heap memory in Mb: 15
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: org.crosswire.jsword.passage.NoSuchVerseException: Cannot understand OSISREF as a chapter or verse.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3716)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3853)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7941)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Cannot understand OSISREF as a chapter or verse.
at org.crosswire.jsword.passage.AccuracyType.parseInt(AccuracyType.java:527)
at org.crosswire.jsword.passage.AccuracyType.checkValidChapterOrVerse(AccuracyType.java:506)
at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:436)
at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:398)
at org.crosswire.jsword.passage.VerseRangeFactory.fromText(VerseRangeFactory.java:117)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:87)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:55)
at org.crosswire.jsword.passage.AbstractPassage.addVerses(AbstractPassage.java:938)
at org.crosswire.jsword.passage.RangedPassage.(RangedPassage.java:93)
at org.crosswire.jsword.passage.PassageType$4.createPassage(PassageType.java:99)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:168)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:187)
at net.bible.android.view.activity.page.MainBibleActivity.openLink(MainBibleActivity.kt:1107)
at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:317)
at android.app.Activity.performCreate(Activity.java:8290)
at android.app.Activity.performCreate(Activity.java:8269)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3697)
... 12 more
```

https://support.andbible.org/scp/tickets.php?id=2247

**Comment by tuomas2** [comment]
User has clicked link at  https://github.com/AndBible/and-bible/wiki/Bible-links (https://read.andbible.org/OSISREF). That has generated crash.

**Comment by tuomas2** [comment]
should add logging and make it not crash (but show error instead)
