### ISSUE TITLE
Crash when searching. java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3072]
Was performing searches one after another. Was looking for the roles regarding elders. Searched for elder, then elders, and then leaders... at leaders... crash! Specifically, was searching only the New Testament. Prior to the search, I was looking at various scriptures and some Greek words using the Strong's referenced from the KJV index. Hopefully enough information for you to replicate the crash. 

https://support.andbible.org/scp/tickets.php?id=2264

```
Device info:
Version: 5.0.771#5578074e8 googleplay standard release (built 23/11/23 10:43:02)
Android version: 7.1.1
Android SDK version: 25
Manufacturer: samsung
Model: SAMSUNG-SM-T377A
Storage Mb free: 1295
WebView version: 119.0.6045.163
SQLITE version: 3.42.0
Used heap memory in Mb: 15
Max heap memory in Mb: 128

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.search.SearchResults}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference
	at android.os.BaseBundle.(BaseBundle.java:164)
	at android.os.Bundle.(Bundle.java:106)
	at android.content.Intent.getExtras(Intent.java:7186)
	at androidx.activity.ComponentActivity.getDefaultViewModelCreationExtras(ComponentActivity.java:654)
	at androidx.lifecycle.ViewModelProviderGetKt.defaultCreationExtras(ViewModelProvider.kt:363)
	at androidx.lifecycle.ViewModelProvider.(ViewModelProvider.kt:132)
	at androidx.lifecycle.SavedStateHandleSupport.getSavedStateHandlesVM(SavedStateHandleSupport.kt:109)
	at androidx.lifecycle.SavedStateHandlesProvider$viewModel$2.invoke(SavedStateHandleSupport.kt:134)
	at androidx.lifecycle.SavedStateHandlesProvider$viewModel$2.invoke(SavedStateHandleSupport.kt:133)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.lifecycle.SavedStateHandlesProvider.getViewModel(SavedStateHandleSupport.kt:133)
	at androidx.lifecycle.SavedStateHandlesProvider.performRestore(SavedStateHandleSupport.kt:172)
	at androidx.lifecycle.SavedStateHandleAttacher.onStateChanged(SavedStateHandleSupport.kt:203)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.kt:87)
	at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.kt:50)
	at android.app.Fragment.performActivityCreated(Fragment.java:2362)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2043)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:177)
	at android.app.Activity.performCreateCommon(Activity.java:6967)
	at android.app.Activity.performCreate(Activity.java:6975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	... 9 more
```

**Comment by tuomas2** [comment]
eBibles engKJV2006eb(KJV) module

Search term:+[Mat-Rev] +Leaders
