### ISSUE TITLE
ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3075]
https://support.andbible.org/scp/tickets.php?id=2268

```
Device info:
Version: 5.0.771#5578074e8 googleplay standard release (built 23/11/23 10:43:02)
Android version: 13
Android SDK version: 33
Manufacturer: Vortex
Model: HD65
Storage Mb free: 36487
WebView version: 119.0.6045.66
SQLITE version: 3.42.0
Used heap memory in Mb: 13
Max heap memory in Mb: 256

Exception:
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9d22fcb u0 net.bible.android.activity/net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2043)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2014)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7941)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at net.bible.service.cloudsync.CloudSync$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
at net.bible.service.device.speak.TextToSpeechNotificationManager.startForeground(TextToSpeechNotificationManager.kt:353)
at net.bible.service.device.speak.TextToSpeechNotificationManager.onEventMainThread(TextToSpeechNotificationManager.kt:245)
at java.lang.reflect.Method.invoke(Native Method)
at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:515)
at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:450)
at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:427)
at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:400)
at [de.greenrobot.event.EventBus.post](http://de.greenrobot.event.eventbus.post/)(EventBus.java:280)
at [net.bible.android.control.event.ABEventBus.post](http://net.bible.android.control.event.abeventbus.post/)(ABEventBus.kt:56)
at net.bible.service.device.speak.TextToSpeechServiceManager.fireStateChangeEvent(TextToSpeechServiceManager.kt:620)
at net.bible.service.device.speak.TextToSpeechServiceManager.startSpeaking(TextToSpeechServiceManager.kt:531)
at net.bible.service.device.speak.TextToSpeechServiceManager.initializeTtsOrStartSpeaking(TextToSpeechServiceManager.kt:374)
at net.bible.service.device.speak.TextToSpeechServiceManager.continueAfterPause(TextToSpeechServiceManager.kt:470)
at net.bible.service.device.speak.TextToSpeechServiceManager.rewind(TextToSpeechServiceManager.kt:407)
at net.bible.android.control.speak.SpeakControl.rewind(SpeakControl.kt:329)
at net.bible.android.view.util.widget.SpeakTransportWidget.onButtonClick(SpeakTransportWidget.kt:121)
at net.bible.android.view.util.widget.SpeakTransportWidget.lambda$8$lambda$1(SpeakTransportWidget.kt:80)
at net.bible.android.view.util.widget.SpeakTransportWidget.$r8$lambda$Lef6YoivdZmSOP7hKmSrsjpDIvw(SpeakTransportWidget.kt:0)
at net.bible.android.view.util.widget.SpeakTransportWidget$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
at android.view.View.performClick(View.java:7527)
at android.view.View.performClickInternal(View.java:7500)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:29538)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
... 6 more
```

**Comment by tuomas2** [comment]
found possible fix for this.
