### ISSUE TITLE
Crash: java.lang.RuntimeException: Unable to start receiver net.bible.android.activity.SpeakWidgetManager$SpeakTextControlWidget: java.lang.RuntimeException: This class is singleton!

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3076]
> Version: 5.0.762#9bdc35e58 googleplay standard release (built 16/11/23 10:21:03)
> Android version: 7.1.1
> Android SDK version: 25
> Manufacturer: Sony
> Model: E6553
> Storage Mb free: 10242
> WebView version: 119.0.6045.163
> SQLITE version: 3.42.0
> Used heap memory in Mb: 7
> Max heap memory in Mb: 192
> 
> Exception:
> java.lang.RuntimeException: Unable to start receiver net.bible.android.activity.SpeakWidgetManager$SpeakTextControlWidget: java.lang.RuntimeException: This class is singleton!
> at android.app.ActivityThread.handleReceiver(ActivityThread.java:3111)
> at android.app.ActivityThread.-wrap18(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:241)
> at android.app.ActivityThread.main(ActivityThread.java:6274)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> Caused by: java.lang.RuntimeException: This class is singleton!
> at net.bible.service.device.speak.TextToSpeechNotificationManager.(TextToSpeechNotificationManager.kt:200)
> at net.bible.service.common.CommonUtils.initializeApp(CommonUtils.kt:1089)
> at net.bible.android.activity.SpeakWidgetManager$AbstractSpeakWidget.onReceive(SpeakWidgets.kt:233)
> at net.bible.android.activity.SpeakWidgetManager$AbstractButtonSpeakWidget.onReceive(SpeakWidgets.kt:322)
> at android.app.ActivityThread.handleReceiver(ActivityThread.java:3104)
> ... 8 more
>  bare startet som vanlig

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2270
