### ISSUE TITLE
Crash in migration ( no such column: _id (code 1 SQLITE_ERROR): , while compiling: INSERT INTO ReadingPlanMap SELECT _id, randomblob(16) FROM readingplan)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3079]
https://support.andbible.org/scp/tickets.php?id=2277
```
Device info:
Version: 5.0.771#5578074 github standard release (built 23/11/23 08:43:16)
Android version: 13
Android SDK version: 33
Manufacturer: OnePlus
Model: LE2115
Storage Mb free: 44176
WebView version: 119.0.6045.163
SQLITE version: 3.42.0
Used heap memory in Mb: 17
Max heap memory in Mb: 384

Exception:
android.database.sqlite.SQLiteException: no such column: _id (code 1 SQLITE_ERROR): , while compiling: INSERT INTO ReadingPlanMap SELECT _id, randomblob(16) FROM readingplan
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement([SQLiteConnection.java:1074](denied:SQLiteConnection.java:1074))
at android.database.sqlite.SQLiteConnection.prepare([SQLiteConnection.java:679](denied:SQLiteConnection.java:679))
at android.database.sqlite.SQLiteSession.prepare([SQLiteSession.java:590](denied:SQLiteSession.java:590))
at android.database.sqlite.SQLiteProgram. ([SQLiteProgram.java:62](denied:SQLiteProgram.java:62))
at android.database.sqlite.SQLiteStatement. ([SQLiteStatement.java:34](denied:SQLiteStatement.java:34))
at android.database.sqlite.SQLiteDatabase.executeSql([SQLiteDatabase.java:2086](denied:SQLiteDatabase.java:2086))
at android.database.sqlite.SQLiteDatabase.execSQL([SQLiteDatabase.java:2008](denied:SQLiteDatabase.java:2008))
at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.kt:246)
at [net.bible.android](https://net.bible.android/).database.migrations.DatabaseSplitMigrations.readingPlanDb(DatabaseSplitMigrations.kt:171)
at [net.bible.android](https://net.bible.android/).database.migrations.DatabaseSplitMigrations.migrateAll(DatabaseSplitMigrations.kt:47)
at [net.bible](https://net.bible/).service.db.DatabaseContainer.migrateOldDatabaseIfNeeded(DatabaseContainer.kt:99)
at [net.bible](https://net.bible/).service.db.DatabaseContainer. (DatabaseContainer.kt:73)
at [net.bible](https://net.bible/).service.db.DatabaseContainer$Companion.getInstance(DatabaseContainer.kt:277)
at [net.bible.android](https://net.bible.android/).view.activity.StartupActivity$initializeDatabase$2.invokeSuspend(StartupActivity.kt:229)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at [kotlinx.coroutines.DispatchedTask.run](https://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$[Worker.run](https://worker.run/)(LimitedDispatcher.kt:115)
at [kotlinx.coroutines.scheduling.TaskImpl.run](https://kotlinx.coroutines.scheduling.taskimpl.run/)(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](https://worker.run/)(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@525f366, Dispatchers.Main.immediate]
```

**Comment by tuomas2** [comment]
also: https://support.andbible.org/scp/tickets.php?id=2485

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2650

**Comment by tuomas2** [comment]
also https://support.andbible.org/scp/tickets.php?id=2729

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=3204

**Comment by timbze** [comment]
Same crash, new report — osTicket #569931, root cause now clear.

**Repro:** Fresh/no-bibles install → Startup "Restore database" → pick any non-AndBible SQLite file such as a MyBible module (`Biblia Poznanska apokryf V1_6.bbl.mybible`, `user_version` 0) via the picker → confirm the overwrite dialog → crash.

```
BackupControl: Filetype: SQLITE3
BackupControl: Loading from backup database with version 0
DbContainer: Can't open database
android.database.sqlite.SQLiteException: no such column: _id …
INSERT INTO ReadingPlanMap SELECT _id, randomblob(16) FROM readingplan
DatabaseSplitMigrations.readingPlanDb():171
```

**Root cause:** `restoreOldMonolithicDatabaseFromInputStream` accepts any file as an old monolithic backup based on only the SQLite header + `user_version <= 69`. A MyBible/foreign DB passes both, then `DatabaseSplitMigrations.readingPlanDb()` assumes the old AndBible `readingplan` schema and dies. Validation is missing both at restore time and (for this issue's original startup path) inside the migration.

**Two things that make this worse than a crash:**
- `deleteAllDatabases()`/`reset()` run *before* the failing migration, so a failed restore wipes the user's existing data.
- Picking a foreign file from a flaky provider (OneDrive) is a separate unhandled crash: `FileNotFoundException: No content provider: com.microsoft.skydrive.content.external` → `Failed to process backup file` — the StartupActivity restore path has no try/catch.

**Suggested fix (any of, ideally all):**
1. Validate the file is genuinely an old AndBible DB (e.g. `PRAGMA table_info(readingplan)` has `_id`) *before* deleting existing databases → friendly "not an AndBible backup" error.
2. Guard `readingPlanDb()`/`readingPlanStatusDb()` to skip when the table/column is missing, so startup migration can't crash on a stray `.db`.
3. Catch IO exceptions in the restore picker/stream flows (`restoreDatabaseZipFileInputStreamWithUI`, `StartupActivity.restoreDatabase`) and show a friendly message.

Logcat from the session is available if useful.

**Comment by timbze** [comment]
Same crash, new report. Startup, not a restore in this session.

https://support.andbible.org/scp/tickets.php?id=3448

Opened 21 Sep 2026. In-app after-crash report, no user comment. Screenshot is the splash screen. The app dies on `StartupActivity` and the next launch hits the same crash a few seconds later.

**Bug was found on AndBible version** 5.1.1110#4b352b3fc googleplay standard release (09/07/26)

**Device:** Samsung SM-S166V (Galaxy A16), Android 16 (SDK 36), WebView 152.0.7977.87

The on-disk monolithic DB is already at version 69 (`OLD_DATABASE_VERSION`). There is no `BackupControl` restore in this log.

```
DbContainer: backupping old database of version 69)
SQLiteConnection: DB version: 69
DbContainer: Can't open database
android.database.sqlite.SQLiteException: no such column: _id (code 1 SQLITE_ERROR): , while compiling: INSERT INTO ReadingPlanMap SELECT _id, randomblob(16) FROM readingplan
at net.bible.android.database.migrations.DatabaseSplitMigrations.migrateAll
at net.bible.service.db.DatabaseContainer.<init>
at net.bible.service.common.CommonUtils.initializeAppCoroutine
```

So this is the original startup path: a version-69 `andBibleDatabase.db` whose `readingplan` table has no `_id`, not the `user_version` 0 foreign-file restore described above. `readingPlanDb()` still assumes that column.
