### ISSUE TITLE
Crash in VersePage.getCurrentPassageBook

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3099]
https://support.andbible.org/scp/tickets.php?id=2298

```
Device info:
Version: 5.0.762#9bdc35e58 googleplay standard release (built 16/11/23 10:21:03)
Android version: 10
Android SDK version: 29
Manufacturer: samsung
Model: SM-A107F
Storage Mb free: 441
WebView version: 117.0.5938.140
SQLITE version: 3.42.0
Used heap memory in Mb: 3
Max heap memory in Mb: 256

Exception:
java.lang.NullPointerException: null cannot be cast to non-null type org.crosswire.jsword.book.basic.AbstractPassageBook
at net.bible.android.control.page.VersePage.getCurrentPassageBook(VersePage.kt:56)
at net.bible.android.control.page.CurrentPageManager.getCurrentPassageDocument(CurrentPageManager.kt:123)
at net.bible.android.control.search.SearchControl.getCurrentPassageDocument(SearchControl.kt:196)
at net.bible.android.control.search.SearchControl.currentDocumentContainsNonScripture(SearchControl.kt:199)
at net.bible.android.view.activity.search.searchresultsactionbar.ScriptureToggleActionBarButton.getCanShow(ScriptureToggleActionBarButton.kt:39)
at net.bible.android.view.activity.base.actionbar.QuickActionButton.update(QuickActionButton.kt:60)
at net.bible.android.view.activity.base.actionbar.QuickActionButton.addToMenu(QuickActionButton.kt:48)
at net.bible.android.view.activity.search.searchresultsactionbar.SearchResultsActionBarManager.prepareOptionsMenu(SearchResultsActionBarManager.kt:48)
at net.bible.android.view.activity.base.CustomTitlebarActivityBase.onPrepareOptionsMenu(CustomTitlebarActivityBase.kt:58)
at android.app.Activity.onPreparePanel(Activity.java:4137)
at androidx.activity.ComponentActivity.onPreparePanel(ComponentActivity.java:511)
at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:485)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:470)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:100)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3477)
at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:2054)
at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2313)
at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:281)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8019)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by tuomas2** [comment]
Duplicate of #3124
