### ISSUE TITLE
Crash: ExceptionInInitializerError

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3118]
https://support.andbible.org/scp/tickets.php?id=2329

```
Информация об устройстве:
Version: 5.0.781#ad34d14fc googleplay standard release (built 06/12/23 09:46:46)
Android version: 7.1.1
Android SDK version: 25
Manufacturer: Sony
Model: E6683
Storage Mb free: 10509
WebView version: 119.0.6045.193
SQLITE version: 3.42.0
Used heap memory in Mb: 7
Max heap memory in Mb: 192

Exception:
java.lang.ExceptionInInitializerError
at net.bible.android.control.versification.BookInstallWatcher.startListening(BookInstallWatcher.kt:38)
at net.bible.service.sword.SwordEnvironmentInitialisation.initialiseJSwordFolders(SwordEnvironmentInitialisation.kt:83)
at net.bible.android.BibleApplication.onCreate(BibleApplication.kt:144)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5548)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:6274)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
at org.crosswire.jsword.book.sword.SwordBookDriver.getBooks(SwordBookDriver.java:93)
at org.crosswire.jsword.book.sword.SwordBookDriver.getBooks(SwordBookDriver.java:77)
at org.crosswire.jsword.book.Books.registerDriver(Books.java:179)
at org.crosswire.jsword.book.Books.autoRegister(Books.java
```

**Comment by tuomas2** [comment]
Asked user for extra info

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2523

```
Exception:
java.lang.ExceptionInInitializerError
at org.crosswire.jsword.book.Books.installed(Books.java:0)
at net.bible.android.control.versification.BookInstallWatcher.startListening(BookInstallWatcher.kt:38)
at net.bible.service.sword.SwordEnvironmentInitialisation.initialiseJSwordFolders(SwordEnvironmentInitialisation.kt:84)
at net.bible.android.BibleApplication.onCreate(BibleApplication.kt:147)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1123)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6636)
at android.app.ActivityThread.-wrap2(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7555)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
at org.crosswire.jsword.book.basic.AbstractBookMetaData.compareTo(AbstractBookMetaData.java:250)
at org.crosswire.jsword.book.basic.AbstractBookMetaData.compareTo(AbstractBookMetaData.java:45)
at org.crosswire.jsword.book.basic.AbstractBook.compareTo(AbstractBook.java:458)
at org.crosswire.jsword.book.basic.AbstractBook.compareTo(AbstractBook.java:58)
at java.util.TreeMap.getEntry(TreeMap.java:353)
at java.util.TreeMap.containsKey(TreeMap.java:233)
at java.util.TreeSet.contains(TreeSet.java:234)
at org.crosswire.jsword.book.Books.addBook(Books.java:128)
at org.crosswire.jsword.book.Books.registerDriver(Books.java:190)
at org.crosswire.jsword.book.Books.autoRegister(Books.java:247)
at org.crosswire.jsword.book.Books.(Books.java:297)
```

**Comment by tuomas2** [comment]
User provided backup of a failing document here: https://support.andbible.org/scp/tickets.php?id=2523

**Comment by tuomas2** [comment]
This was related to BOM (Byte Order Mark) that was the first character of the mod conf file, written there probably by some text editor. Skipping this fixes reading file.
