### ISSUE TITLE
Remove "Find in Bible" context menu action (from other apps)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3119]
Causes more harm than benefit. I have seen some people hating it even.

Related: https://support.andbible.org/scp/tickets.php?id=2330

**Comment by tuomas2** [comment]
Created poll in Telegram

**Comment by tuomas2** [comment]
Related crash (in above mentioned ticket)

```
Exception:
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at org.crosswire.jsword.book.sword.SwordUtil.decodeLittleEndian32(SwordUtil.java:197)
at org.crosswire.jsword.book.sword.TreeKeyIndex.getOffset(TreeKeyIndex.java:118)
at org.crosswire.jsword.book.sword.TreeKeyIndex.getFirstChild(TreeKeyIndex.java:88)
at org.crosswire.jsword.book.sword.GenBookBackend.doReadIndex(GenBookBackend.java:210)
at org.crosswire.jsword.book.sword.GenBookBackend.readIndex(GenBookBackend.java:177)
at org.crosswire.jsword.book.sword.SwordGenBook.activate(SwordGenBook.java:76)
at org.crosswire.common.activate.Activator.activate(Activator.java:51)
at org.crosswire.jsword.book.sword.SwordGenBook.checkActive(SwordGenBook.java:247)
at org.crosswire.jsword.book.sword.SwordGenBook.getKey(SwordGenBook.java:200)
at net.bible.service.history.HistoryManager.restoreFrom(HistoryManager.kt:103)
at net.bible.android.control.page.window.WindowRepository.loadFromDb(WindowRepository.kt:359)
at net.bible.android.control.page.window.WindowRepository.initialize(WindowRepository.kt:104)
at net.bible.android.control.page.window.WindowRepository.getActiveWindow(WindowRepository.kt:117)
at net.bible.android.control.page.window.WindowControl.getActiveWindow(WindowControl.kt:75)
at net.bible.android.control.page.window.WindowControl.getActiveWindowPageManager(WindowControl.kt:70)
at net.bible.android.control.search.SearchControl.getCurrentPassageDocument(SearchControl.kt:196)
at net.bible.android.control.search.SearchControl.currentDocumentContainsNonScripture(SearchControl.kt:199)
```

**Comment by tuomas2** [comment]
> I am not yet sure if it can be made an option (it is declared in android manifest (PROCESS_TEXT intent for SearchResults activity)). By far easiest would be just remove it if it does not bring real value to any users, but if it is really useful even to 1% of users, it might be good idea to try to keep it.

**Comment by dbrgn** [comment]
Would be great if this could be removed from the app. It regularly bothers me, because I never use that feature, and it causes other frequently used context menu actions to be moved into the overflow menu. (After all, this functionality is meant for text processing. If every app would add itself as search target for highlighted text, usability of that menu would quickly deteriorate.)

I checked quickly to see whether intent filters can be configured dynamically, but I don't think that's the case. Android needs a way to determine elegible apps for text processing, and that must be possible even when said app is not running. Thus, it must rely on static information (declaration in manifest). So I guess there's no way to make this configurable.

**Comment by timbze** [comment]
I don't think it's useful enough to keep. I have never used the feature

**Comment by tuomas2** [comment]
Okay let's decide I will remove it then.

**Comment by meichthys** [comment]
Is it possible to toggle this kind of feature? I haven't used this specific feature, but I would be interested in sharing content from an external app into a study pad, but I wouldn't want to annoy other users who might not want the context menu action.

**Comment by tuomas2** [comment]
As I have concluded and @dbrgn above, it looks like this can't be made optional.
