### ISSUE TITLE
Download document fails

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3121]
>  I love  this  App  but   i don't know how to  Download the Documents 

https://support.andbible.org/scp/tickets.php?id=2335

```
Device info:
Version: 5.0.771#5578074e8 googleplay standard release (built 23/11/23 10:43:02)
Android version: 8.1.0
Android SDK version: 27
Manufacturer: samsung
Model: SM-J410F
Storage Mb free: 8300
WebView version: 116.0.5845.114
SQLITE version: 3.42.0
Used heap memory in Mb: 7
Max heap memory in Mb: 128

Exception:
java.lang.NullPointerException: Attempt to read from field 'java.util.TreeMap$TreeMapEntry java.util.TreeMap$TreeMapEntry.left' on a null object reference
at java.util.TreeMap.rotateLeft(TreeMap.java:2280)
at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2347)
at java.util.TreeMap.put(TreeMap.java:609)
at java.util.TreeSet.add(TreeSet.java:255)
at net.bible.service.download.GenericFileDownloader.addError(GenericFileDownloader.kt:55)
at net.bible.service.download.GenericFileDownloader.downloadFileSync(GenericFileDownloader.kt:166)
at net.bible.service.download.GenericFileDownloader.downloadFileSync$default(GenericFileDownloader.kt:115)
at net.bible.service.download.GenericFileDownloader$downloadFile$2.invokeSuspend(GenericFileDownloader.kt:108)
at net.bible.service.download.GenericFileDownloader$downloadFile$2.invoke(GenericFileDownloader.kt:0)
at net.bible.service.download.GenericFileDownloader$downloadFile$2.invoke(GenericFileDownloader.kt:0)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at net.bible.service.download.GenericFileDownloader.downloadFile(GenericFileDownloader.kt:107)
at net.bible.android.view.activity.download.DownloadActivity$loadPseudoBooks$2.invokeSuspend(DownloadActivity.kt:155)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b5ef639, Dispatchers.Main.immediate   I love  this  App  but   i don't know how to  Download the Documents 
```

**Comment by tuomas2** [comment]
loadPseudoBooks() reports error and error reporting somehow fails.
