### ISSUE TITLE
Epub crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3123]
https://support.andbible.org/scp/tickets.php?id=2337

```

Device info:
Version: 5.0.792#65e873836 googleplay standard release (built 16/12/23 21:22:36)
Android version: 11
Android SDK version: 30
Manufacturer: realme
Model: RMX3263
Storage Mb free: 29334
WebView version: 120.0.6099.43
SQLITE version: 3.42.0
Used heap memory in Mb: 5
Max heap memory in Mb: 192

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.navigation.genbookmap.ChooseGeneralBookKey}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jdom2.Document org.jdom2.Content.getDocument()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3680)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7950)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jdom2.Document org.jdom2.Content.getDocument()' on a null object reference
at org.jdom2.xpath.jaxen.JDOMCoreNavigator.getDocumentNode(JDOMCoreNavigator.java:254)
at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:96)
at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:96)
at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:662)
at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
at org.jdom2.xpath.jaxen.JaxenCompiled.evaluateRawAll(JaxenCompiled.java:198)
at org.jdom2.xpath.util.AbstractXPathCompiled.evaluate(AbstractXPathCompiled.java:356)
at net.bible.service.sword.epub.EpubBackendState$tocKeys$content$1.invoke(EpubBackendState.kt:152)
at net.bible.service.sword.epub.EpubBackendState$tocKeys$content$1.invoke(EpubBackendState.kt:150)
at net.bible.service.common.CommonUtilsKt.useXPathInstance(CommonUtils.kt:1715)
at net.bible.service.sword.epub.EpubBackendState.getTocKeys(EpubBackendState.kt:150)
at net.bible.service.sword.epub.EpubBackend.getTocKeys(EpubBook.kt:123)
at net.bible.android.view.activity.navigation.genbookmap.ChooseGeneralBookKey.getKeyList(ChooseGeneralBookKey.kt:43)
at net.bible.android.view.activity.navigation.genbookmap.ChooseKeyBase.prepareList(ChooseKeyBase.kt:72)
at net.bible.android.view.activity.navigation.genbookmap.ChooseKeyBase.onCreate(ChooseKeyBase.kt:53)
at android.app.Activity.performCreate(Activity.java:8071)
at android.app.Activity.performCreate(Activity.java:8054)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)
... 11 more
```

**Comment by tuomas2** [comment]
Checked logcat. Will continue investigation if getting epub.

**Comment by tuomas2** [comment]
Here too: https://support.andbible.org/scp/tickets.php?id=2700

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2807
