### ISSUE TITLE
Crash when restoring: FileNotFoundException: No content provider

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3135]
In startup screen
https://support.andbible.org/scp/tickets.php?id=2367

```
--- PLEASE WRITE YOUR FEEDBACK OR BUG REPORT ABOVE THIS LINE ---

Instructions:
Tell us briefly what did you do / what happened when issue took place.

For example:
  1. Opened app
  2. Clicked window menu
  -> Crash
 
Please use this function to report as soon as you have noticed issue taking place. You can also use this function after opening app, after crash has taken place.

Attachments:
  - logcat.txt.gz: Log file produced by this app. It does not contain information about any other apps.
  - screenshot.webp: Screenshot of app when crash took place, or when bug report was created.

Having these files attached helps app developers a lot in fixing the reported bug. Sometimes manually taken screenshots also are beneficial in resolving issues.

Device info:
Version: 5.0.755#27acfd2f5 googleplay standard release (built 10/11/23 18:17:01)
Android version: 13
Android SDK version: 33
Manufacturer: samsung
Model: SM-G981U
Storage Mb free: 80257
WebView version: 111.0.5563.116
SQLITE version: 3.42.0
Used heap memory in Mb: 6
Max heap memory in Mb: 256

Exception:
java.io.FileNotFoundException: No content provider: content://com.estrongs.files/storage/AE77-F8F4/AndBibleBackup/AndBibleDatabaseBackup.abdb.zip
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2020)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
at net.bible.android.view.activity.StartupActivity$restoreDatabase$1.invokeSuspend(StartupActivity.kt:344)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1406)
at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:320)
at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:297)
at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:810)
at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:90)
at net.bible.android.view.activity.base.ActivityBase.onActivityResult(ActivityBase.kt:355)
at android.app.Activity.dispatchActivityResult(Activity.java:8951)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6782479, Dispatchers.Main.immediate]
```

**Comment by tuomas2** [comment]
It appears that the root cause might not be in AndBible itself but the content provider (app id: com.estrongs.files). But will try to fix the crash that AndBible gives proper error message instead.

**Comment by timbze** [comment]
Another occurrence of the same crash, this time with OneDrive as the provider (`No content provider: com.microsoft.skydrive.content.external`) while restoring from the startup "Restore database" screen.

Support ticket: https://support.andbible.org/scp/tickets.php?id=3204
