### ISSUE TITLE
Crash when backupping documents ZipException: duplicate entry

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3138]
The app crashed while attempting to back up "documents," immediately before the selection of the app to be used to select the location to which the backup is to be saved.
https://support.andbible.org/scp/tickets.php?id=2359
```
Device info:
Version: 5.0.792#65e873836 googleplay standard release (built 16/12/23 21:22:36)
Android version: 11
Android SDK version: 30
Manufacturer: samsung
Model: SM-T510
Storage Mb free: 66855
WebView version: 120.0.6099.43
SQLITE version: 3.42.0
Used heap memory in Mb: 6
Max heap memory in Mb: 192

Exception:
[java.util.zip](https://java.util.zip/).ZipException: duplicate entry: mods.d/engbsb2020eb.conf
at [java.util.zip](https://java.util.zip/).ZipOutputStream.putNextEntry([ZipOutputStream.java:234](denied:ZipOutputStream.java:234))
at [net.bible.android](https://net.bible.android/).control.backup.BackupControl.createModulesZip$addFile(BackupControl.kt:333)
at [net.bible.android](https://net.bible.android/).control.backup.BackupControl.access$createModulesZip$addFile(BackupControl.kt:100)
at [net.bible.android](https://net.bible.android/).control.backup.BackupControl$createModulesZip$2.invokeSuspend(BackupControl.kt:370)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at [kotlinx.coroutines.DispatchedTask.run](https://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$[Worker.run](https://worker.run/)(LimitedDispatcher.kt:115)
at [kotlinx.coroutines.scheduling.TaskImpl.run](https://kotlinx.coroutines.scheduling.taskimpl.run/)(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](https://worker.run/)(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@939520a, Dispatchers.Main.immediate]
ALM4-Vendors
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2347
