### ISSUE TITLE
Crash in clicking strongs link

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3139]
Crash in clicking strongs link

https://support.andbible.org/scp/tickets.php?id=2357

```

Geräteinfo:
Version: 5.0.792#65e873836 googleplay standard release (built 16/12/23 21:22:36)
Android version: 14
Android SDK version: 34
Manufacturer: samsung
Model: SM-A528B
Storage Mb free: 15987
WebView version: 120.0.6099.43
SQLITE version: 3.42.0
Used heap memory in Mb: 6
Max heap memory in Mb: 256

Exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.io.RandomAccessFile.length()' on a null object reference
at org.crosswire.jsword.book.sword.RawLDBackend.getCardinality(RawLDBackend.java:119)
at org.crosswire.jsword.book.sword.RawLDBackend.search(RawLDBackend.java:279)
at org.crosswire.jsword.book.sword.RawLDBackend.indexOf(RawLDBackend.java:164)
at org.crosswire.jsword.book.sword.SwordDictionary.getKey(SwordDictionary.java:151)
at net.bible.android.control.link.LinkControl.getStrongsKey(LinkControl.kt:284)
at net.bible.android.control.link.LinkControl.getBookAndKey(LinkControl.kt:135)
at net.bible.android.control.link.LinkControl.loadApplicationUrl(LinkControl.kt:146)
at net.bible.android.control.link.LinkControl.loadApplicationUrl(LinkControl.kt:119)
at net.bible.android.view.activity.page.BibleView.openLink(BibleView.kt:981)
at net.bible.android.view.activity.page.BibleView$BibleViewClient.shouldOverrideUrlLoading(BibleView.kt:1075)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-609904333:93)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loopOnce(Looper.java:187)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8893)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by tuomas2** [comment]
Asked some questions.

German Luther Bible (from eBible repo) and russian strongs hebrew dict in use. and crash happens in Ez 1:28 by clicking strongs 6963.
