### ISSUE TITLE
Crash: SQLiteConstraintException: NOT NULL constraint failed: Window.window_layout_weight

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3149]
https://support.andbible.org/scp/tickets.php?id=2377

```
Device info:
Version: 5.0.792#65e873836 fdroid standard release (built 19/12/23 12:53:26)
Android version: 13
Android SDK version: 33
Manufacturer: LGE
Model: LM-V600
Storage Mb free: 35431
WebView version: 120.0.6099.144
SQLITE version: 3.42.0
Used heap memory in Mb: 4
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: Unable to pause activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Window.window_layout_weight (code 1299)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5109)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5060)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5012)
at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:8022)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Window.window_layout_weight (code 1299)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:778)
at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
at androidx.room.EntityDeletionOrUpdateAdapter.handleMultiple(EntityDeletionOrUpdateAdapter.kt:79)
at net.bible.android.database.WorkspaceDao_Impl.updateWindows(WorkspaceDao_Impl.java:1523)
at net.bible.android.control.page.window.WindowRepository.saveIntoDb(WindowRepository.kt:327)
at net.bible.android.view.activity.page.MainBibleActivity.onPause(MainBibleActivity.kt:1827)
at android.app.Activity.performPause(Activity.java:8488)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1586)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5099)
```

**Comment by tuomas2** [comment]
asked user for instructions to reproduce.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2510

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2547

> 1. Opened app after many windows from compare text. Additional factor was epubs and many windows from links that would close from a press
>  Installed an epub that was a grammar on a language and other Bibles via the epub import feature. Net data may effect performance though only in my experience isn't burdensome
> ->Crash
