### ISSUE TITLE
EPub Crash: org.jdom2.Document org.jdom2.Content.getDocument()' on a null object reference

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3151]
https://support.andbible.org/scp/tickets.php?id=2372

```
Device info:
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 13
Android SDK version: 33
Manufacturer: OnePlus
Model: NE2217
Storage Mb free: 51060
WebView version: 120.0.6099.144
SQLITE version: 3.42.0
Used heap memory in Mb: 6
Max heap memory in Mb: 384

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.navigation.genbookmap.ChooseGeneralBookKey}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jdom2.Document org.jdom2.Content.getDocument()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3872)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4014)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8423)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jdom2.Document org.jdom2.Content.getDocument()' on a null object reference
at org.jdom2.xpath.jaxen.JDOMCoreNavigator.getDocumentNode(JDOMCoreNavigator.java:254)
at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:96)
at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:96)
at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:662)
at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
at org.jdom2.xpath.jaxen.JaxenCompiled.evaluateRawAll(JaxenCompiled.java:198)
at org.jdom2.xpath.util.AbstractXPathCompiled.evaluate(AbstractXPathCompiled.java:356)
at net.bible.service.sword.epub.EpubBackendState$tocKeys$content$1.invoke(EpubBackendState.kt:152)
at net.bible.service.sword.epub.EpubBackendState$tocKeys$content$1.invoke(EpubBackendState.kt:150)
at net.bible.service.common.CommonUtilsKt.useXPathInstance(CommonUtils.kt:1715)
at net.bible.service.sword.epub.EpubBackendState.getTocKeys(EpubBackendState.kt:150)
at net.bible.service.sword.epub.EpubBackend.getTocKeys(EpubBook.kt:123)
at net.bible.android.view.activity.navigation.genbookmap.ChooseGeneralBookKey.getKeyList(ChooseGeneralBookKey.kt:43)
at net.bible.android.view.activity.navigation.genbookmap.ChooseKeyBase.prepareList(ChooseKeyBase.kt:72)
at net.bible.android.view.activity.navigation.genbookmap.ChooseKeyBase.onCreate(ChooseKeyBase.kt:53)
at android.app.Activity.performCreate(Activity.java:8422)
at android.app.Activity.performCreate(Activity.java:8395)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
```

**Comment by tuomas2** [comment]
Similar incident with epub provided: https://support.andbible.org/scp/tickets.php?id=2371
