### ISSUE TITLE
Crash: java.lang.SecurityException: Permission Denial:team.opay.pay.merchant.service/com.opay.webview.WebFoundationActivity

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3157]
https://support.andbible.org/scp/tickets.php?id=2379

```
Device info:
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 10
Android SDK version: 29
Manufacturer: TECNO MOBILE LIMITED
Model: TECNO LD7
Storage Mb free: 56127
WebView version: 118.0.5993.112
SQLITE version: 3.42.0
Used heap memory in Mb: 4
Max heap memory in Mb: 384

Exception:
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=[https://youtu.be/.](https://youtu.be/).. cmp=team.opay.pay.merchant.service/com.opay.webview.WebFoundationActivity } from ProcessRecord{cf630aa 15319:net.bible.android.activity/u0a205} (pid=15319, uid=10205) not exported from uid 10199
at android.os.Parcel.createException(Parcel.java:2071)
at android.os.Parcel.readException(Parcel.java:2039)
at android.os.Parcel.readException(Parcel.java:1987)
at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4251)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1712)
at android.app.Activity.startActivityForResult(Activity.java:5207)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
at net.bible.android.view.activity.base.ActivityBase.startActivityForResult(ActivityBase.kt:266)
at android.app.Activity.startActivityForResult(Activity.java:5165)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
at net.bible.android.view.activity.base.ActivityBase.startActivityForResult(ActivityBase.kt:165)
at net.bible.service.common.CommonUtils.openLink(CommonUtils.kt:1041)
at net.bible.service.common.CommonUtils.openLink$default(CommonUtils.kt:1026)
at net.bible.service.common.CommonUtilsKt$htmlToSpan$MyURLSpan.onClick(CommonU
```

**Comment by tuomas2** [comment]
Asking user more info
