### ISSUE TITLE
Crash: in index creation: BookException: Installation failed.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3158]
https://support.andbible.org/scp/tickets.php?id=2388

Información del dispositivo:
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 11
Android SDK version: 30
Manufacturer: TCL
Model: 6056A
Storage Mb free: 80603
WebView version: 120.0.6099.144
SQLITE version: 3.42.0
Used heap memory in Mb: 40
Max heap memory in Mb: 256

Exception:
org.crosswire.jsword.book.BookException: Installation failed.
at org.crosswire.jsword.index.lucene.LuceneIndex.(LuceneIndex.java:233)
at org.crosswire.jsword.index.lucene.LuceneIndexManager.scheduleIndexCreation(LuceneIndexManager.java:143)
at net.bible.service.sword.SwordDocumentFacade.scheduleIndexCreation$lambda$5(SwordDocumentFacade.kt:192)
at net.bible.service.sword.SwordDocumentFacade.$r8$lambda$0Fy70REw4_rwskZdlXqOylI8vJY(SwordDocumentFacade.kt:0)
at net.bible.service.sword.SwordDocumentFacade$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
at java.lang.Thread.run(Thread.java:923)

**Comment by tuomas2** [comment]
similar: https://support.andbible.org/scp/tickets.php?id=2464

**Comment by tuomas2** [comment]
> Please describe what kind of issue did you have with our app?  - It crashes.
> Can you please describe what did you do before the issue took place? - Please see below.
> 
> Does this issue take occur often / regularly? - Yes. every time I do the steps described below.
> 
> Can you give exact steps to reproduce the issue? What happened and does it happen regularly?
> 

**Title**: App Freezes When Attempting to Create Index for Bible Verse Search

**Summary**: User experiences an app crash while trying to create an index after clicking "Find all occurrences" in the Bible verse comparison feature.

**Key Points**:
1. User clicks on a verse and selects "Compare".
2. User clicks on a Greek word number and opens its dictionary definition.
3. Clicking "Find all occurrences" prompts the app to create an index.
4. After initiating index creation, the app crashes, prompting an error message and OS suggestion to close the app.

---

**Original Message**:
Reading a Bible, then click on a verse and choose "Compare" from the popup menu. On one of the versions, there are Greek words' numbers, so I clicked on one of them. A new section opens below the text with the dictionary definition. A link appears at the bottom named "Find all occurrences". I clicked on it. A full-screen message appears saying, "To search a document, we need an index. Create an index for Multiple references?". I clicked "Create". A progress bar appears, and after a few seconds, a popup appears with the text "An error occurred" and the option to send the report. At that point, the OS suggests closing the app as it is not responding.

*Summarized using [Summarize @ ChatGPT](https://chatgpt.com/g/g-tFjop0Fow-summarize)*


https://support.andbible.org/scp/tickets.php?id=2609

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2695

**Comment by tuomas2** [comment]
Possibly fixed also together with #3189

**Comment by tuomas2** [comment]
Closing in good hopes...
