### ISSUE TITLE
Crash: App crashes every time I try to load documents that have been backed-up to Google Drive FileNotFoundException: StorageFileLoadException[connection_failure]

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3160]
https://support.andbible.org/scp/tickets.php?id=2381

```
Device info:
Version: 5.0.792#65e873836 googleplay standard release (built 16/12/23 21:22:36)
Android version: 10
Android SDK version: 29
Manufacturer: HUAWEI
Model: CLT-L09
Storage Mb free: 100768
WebView version: 120.0.6099.144
SQLITE version: 3.42.0
Used heap memory in Mb: 3
Max heap memory in Mb: 384

Exception:
java.io.FileNotFoundException: StorageFileLoadException[connection_failure]
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
at net.bible.android.view.activity.installzip.InstallZip.installFromFile(InstallZip.kt:420)
at net.bible.android.view.activity.installzip.InstallZip.getFileFromUserAndInstall(InstallZip.kt:370)
at net.bible.android.view.activity.installzip.InstallZip.access$getFileFromUserAndInstall(InstallZip.kt:295)
at net.bible.android.view.activity.installzip.InstallZip$getFileFromUserAndInstall$1.invokeSuspend(InstallZip.kt:0)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1406)
at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:320)
at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:297)
at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:810)
at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:90)
at net.bible.android.view.activity.base.ActivityBase.onActivityResult(ActivityBase.kt:355)
at android.app.Activity.dispatchActivityResult(Activity.java:8541)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9ec0fcd, Dispatchers.Main.immediate]
```

**Comment by tuomas2** [comment]
> After reviewing the original mail I had sent about the bug, I noticed that I had not mentioned that the app crashes every time I try to load documents that have been backed-up to Google Drive into a newly installed app on another device. This happens regardless of the age of the back-up, whether old or new.
