### ISSUE TITLE
Crash in SearchResults

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3168]
https://support.andbible.org/scp/tickets.php?id=2390

```
SearchResults

Device info:
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 7.0
Android SDK version: 24
Manufacturer: HUAWEI
Model: KOB-L09
Storage Mb free: 1812
WebView version: 119.0.6045.193
SQLITE version: 3.42.0
Used heap memory in Mb: 7
Max heap memory in Mb: 192

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.search.SearchResults}: java.lang.IllegalArgumentException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2804)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.lang.IllegalArgumentException
at android.os.Parcel.nativeAppendFrom(Native Method)
at android.os.Parcel.appendFrom(Parcel.java:458)
at android.os.BaseBundle.(BaseBundle.java:164)
at android.os.Bundle.(Bundle.java:106)
at android.content.Intent.getExtras(Intent.java:6641)
at androidx.activity.ComponentActivity.getDefaultViewModelCreationExtras(ComponentActivity.java:654)
at androidx.lifecycle.ViewModelProviderGetKt.defaultCreationExtras(ViewModelProvider.kt:363)
at androidx.lifecycle.ViewModelProvider.(ViewModelProvider.kt:132)
at androidx.lifecycle.SavedStateHandleSupport.getSavedStateHandlesVM(SavedStateHandleSupport.kt:109)
at androidx.lifecycle.SavedStateHandlesProvider$viewModel$2.invoke(SavedStateHandleSupport.kt:134)
at androidx.lifecycle.SavedStateHandlesProvider$viewModel$2.invoke(SavedStateHandleSupport.kt:133)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at androidx.lifecycle.SavedStateHandlesProvider.getViewModel(SavedStateHandleSupport.kt:133)
at androidx.lifecycle.SavedStateHandlesProvider.performRestore(SavedStateHandleSupport.kt:172)
at androidx.lifecycle.SavedStateHandleAttacher.onStateChanged(SavedStateHandleSupport.kt:203)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.kt:87)
at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.kt:50)
at android.app.Fragment.performActivityCreated(Fragment.java:2373)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1021)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1178)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1160)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
at android.app.Activity.performCreateCommon(Activity.java:6903)
at android.app.Activity.performCreate(Activity.java:6913)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
... 9 more
```

**Comment by tuomas2** [comment]
> Crash happened when "finding all occurrences" from strong's. I've not been able to replicate it nor do I remember which bible translations/resources were open at the time of the crash.

**Comment by tuomas2** [comment]
Also https://support.andbible.org/scp/tickets.php?id=2438

>Everything normal until I did a search on a word and went to one of the references, then pressed the tablet' s Previous button to go back to my previous passage and Bible Study just switched off.
