### ISSUE TITLE
Creating index fails

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3182]
Possibly trying to index KJV.

01-25 08:02:19.067 16860 16907 I Base-SearchResults: Searching  strong:g00947 in KJV

https://support.andbible.org/scp/tickets.php?id=2423

```

Device info:
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 11
Android SDK version: 30
Manufacturer: Hisense
Model: Hisense Infinity H60 Lite
Storage Mb free: 105048
WebView version: 120.0.6099.230
SQLITE version: 3.42.0
Used heap memory in Mb: 11
Max heap memory in Mb: 192

Exception:
org.crosswire.jsword.book.BookException: Installation failed.
at org.crosswire.jsword.index.lucene.LuceneIndex.(LuceneIndex.java:233)
at org.crosswire.jsword.index.lucene.LuceneIndexManager.scheduleIndexCreation(LuceneIndexManager.java:143)
at net.bible.service.sword.SwordDocumentFacade.scheduleIndexCreation$lambda$5(SwordDocumentFacade.kt:192)
at net.bible.service.sword.SwordDocumentFacade.$r8$lambda$0Fy70REw4_rwskZdlXqOylI8vJY(SwordDocumentFacade.kt:0)
at net.bible.service.sword.SwordDocumentFacade$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
at java.lang.Thread.run(Thread.java:923)
```

**Comment by tuomas2** [comment]
Duplicate of #3158
