### ISSUE TITLE
Genbook speak crash ClassCastException: Expected key to be a Verse, VerseRange or Passage

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3184]
https://support.andbible.org/scp/tickets.php?id=2410

```
Info sur le périphérique :
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 13
Android SDK version: 33
Manufacturer: Xiaomi
Model: 2201117TY
Storage Mb free: 23200
WebView version: 120.0.6099.210
SQLITE version: 3.42.0
Used heap memory in Mb: 4
Max heap memory in Mb: 256

Exception:
java.lang.ClassCastException: Expected key to be a Verse, VerseRange or Passage
at org.crosswire.jsword.passage.KeyUtil.getVerse(KeyUtil.java:83)
at org.crosswire.jsword.book.sword.ZVerseBackend.getRawTextLength(ZVerseBackend.java:170)
at org.crosswire.jsword.book.sword.ZVerseBackend.contains(ZVerseBackend.java:156)
at org.crosswire.jsword.book.sword.SwordBook.contains(SwordBook.java:139)
at net.bible.service.sword.SwordContentFacade.bookContainsAnyOf(SwordContentFacade.kt:738)
at net.bible.service.sword.SwordContentFacade.readOsisFragment(SwordContentFacade.kt:163)
at net.bible.service.sword.SwordContentFacade.cachedText(SwordContentFacade.kt:393)
at net.bible.service.sword.SwordContentFacade.ordinalRangeFor(SwordContentFacade.kt:408)
at net.bible.service.common.CommonUtilsKt.ordinalRangeFor(CommonUtils.kt:1806)
at net.bible.service.device.speak.GeneralSpeakTextProvider.getStatusText(GeneralSpeakTextProvider.kt:219)
at net.bible.service.device.speak.TextToSpeechServiceManager.getStatusText(TextToSpeechServiceManager.kt:695)
at net.bible.android.control.speak.SpeakControl.getStatusText(SpeakControl.kt:472)
at net.bible.android.view.util.widget.SpeakTransportWidget.resetView(SpeakTransportWidget.kt:191)
at net.bible.android.view.util.widget.SpeakTransportWidget.onAttachedToWindow(SpeakTransportWidget.kt:113)
at android.view.View.dispatchAttachedToWindow(View.java:21458)
```

**Comment by tuomas2** [comment]
Again in 806 https://support.andbible.org/scp/tickets.php?id=2579

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2652

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2658

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2657

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2656

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2824

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2942

> Olin aiemmin siirtänyt vieraan tiedoston luettavaksi ja kuunneltavaksi. Luku ja kuuntelu onnistuivat. Ilmeisesti puhelimen sovelluspäivitys käynnistyi niin että tuo lukuohjelma oli päällä.

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=3226

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=3272

Same stack on 5.0.934 Play, Pixel 9a (Android 16). Empty in-app crash report; SpeakTransportWidget.getStatusText → ordinalRangeFor → ZVerseBackend ClassCastException: Expected key to be a Verse, VerseRange or Passage.
