### ISSUE TITLE
Crash: NoSuchKeyException: No entry for '06635 ' in StrongsHebrewRU.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3191]
https://support.andbible.org/scp/tickets.php?id=2429

```
Информация об устройстве:
App id: net.bible.android.activity
Version: 5.0.794#c119a7cc9 googleplay standard release (built 18/01/24 19:15:48)
Android version: 11
Android SDK version: 30
Manufacturer: motorola
Model: moto g(60)s
Storage Mb free: 53616
WebView version: 120.0.6099.231
SQLITE version: 3.42.0
Used heap memory in Mb: 6
Max heap memory in Mb: 256

Exception:
org.crosswire.jsword.passage.NoSuchKeyException: No entry for '06635
' in StrongsHebrewRU.
at org.crosswire.jsword.book.sword.SwordDictionary.getKey(SwordDictionary.java:153)
at net.bible.android.view.activity.page.BibleJavascriptInterface$speakGeneric$1.invokeSuspend(BibleJavascriptInterface.kt:432)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:250)
at android.app.ActivityThread.main(ActivityThread.java:7886)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fda639a, Dispatchers.Main]
```

**Comment by tuomas2** [comment]
User tries to speak in dictionary view and it crashes
