### ISSUE TITLE
Crash: Loading module backup from Google Drive 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3192]
https://support.andbible.org/scp/tickets.php?id=2428

```
Device info:
App id: net.bible.android.activity
Version: 5.0.794#c119a7cc9 googleplay standard release (built 18/01/24 19:15:48)
Android version: 11
Android SDK version: 30
Manufacturer: samsung
Model: SM-T510
Storage Mb free: 18666
WebView version: 120.0.6099.230
SQLITE version: 3.42.0
Used heap memory in Mb: 10
Max heap memory in Mb: 192

Exception:
java.io.FileNotFoundException: StorageFileLoadException[connection_failure]
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1485)
at net.bible.android.view.activity.installzip.InstallZip.installFromFile(InstallZip.kt:420)
at net.bible.android.view.activity.installzip.InstallZip.getFileFromUserAndInstall(InstallZip.kt:370)
at net.bible.android.view.activity.installzip.InstallZip.access$getFileFromUserAndInstall(InstallZip.kt:295)
at net.bible.android.view.activity.installzip.InstallZip$getFileFromUserAndInstall$1.invokeSuspend(InstallZip.kt:0)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1406)
at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:320)
at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:297)
at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:810)
at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:90)
at net.bible.android.view.activity.base.ActivityBase.onActivityResult(ActivityBase.kt:355)
at android.app.Activity.dispatchActivityResult(Activity.java:8550)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b7d1053, Dispatchers.Main.immediate]
```

**Comment by tuomas2** [comment]
Asked Bard https://g.co/bard/share/f23ba4e824af

**Comment by tuomas2** [comment]
Possibly connectivity issue.
