### ISSUE TITLE
synchronize: ConcurrentModificationException

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3200]
https://support.andbible.org/scp/tickets.php?id=2457

> 
> I didn't notice the application had crashed. So let me just report what I was doing last time I used the application. 
> 
> I was in split screen mode with the top and bottom windows roughly equal size. In the top window was a daily Bible study book open in Google play books. In the bottom window I had two Bible apps open: yours and the one from Living Stream Ministry. One of the Bible apps was in the foreground and the other hidden. I read the outline and reading portion for the day in Google books. When I got to a verse reference, tbere are over a dozen per day, I would read it in one of the Bible apps and go back to reading in Google play books. I used the Living Stream Bible app if I wanted footnotes. (The footnotes are not available in your app.) If I didn't want footnotes I used your app since it quicker. Plus all my notes are in your app since it is older.
> 
> The above is my normal situation. The last two days I have been having problems getting the Living Stream app to come up at all. It never finishes initializing. I also saw this in your app a few times. Neither app, but more so the Living Stream one, seems to work well in a low memory environment. I deleted some apps and cleared the storage cache of manh apps to get the Bible apps to come up. I had 4.2 GB free of 32 GB total when the apps would not come up. After that the apps worked. I don't know how much storage I had free then. Then they stppped working. I deleted more. Now I have 6 GB free. Things seem to be working.
> 
> I have an SSD memory card that is almost empty. Google play books has an option to store new books on the memory card instead of internal system memory. (Already downloaded books can be moved to the memory card by deleting them and downloading them again.) It would help if your app had an option to store Bibles and other documents plus my own notes on the memory card, and if it moved the documents and notes from system memory to the memory card when the new option was set to memory card. 

```
java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1322)
	at java.util.Vector$Itr.next(Vector.java:1272)
	at net.bible.service.history.HistoryManager.getEntities(HistoryManager.kt:1855)
	at net.bible.android.control.page.window.WindowRepository.saveIntoDb(WindowRepository.kt:309)
	at net.bible.android.view.activity.page.MainBibleActivity.synchronize(MainBibleActivity.kt:1377)
	at net.bible.android.view.activity.page.MainBibleActivity.startSync(MainBibleActivity.kt:1346)
	at net.bible.android.view.activity.page.MainBibleActivity.access$startSync(MainBibleActivity.kt:168)
	at net.bible.android.view.activity.page.MainBibleActivity$onEvent$2.invokeSuspend(MainBibleActivity.kt:1402)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d431fe4, Dispatchers.IO]
```

**Comment by timbze** [comment]
Slightly different, but same type of issue. https://support.andbible.org/scp/tickets.php?id=3372

Reproducible on 5.1.1110 (#4b352b3), Pixel 8a / Android 16.

**Comment by tuomas2** [comment]
Fixed on a branch (will be in the next release): the `ConcurrentModificationException` in `WindowRepository.saveIntoDb`. `windowList` was a plain `ArrayList` iterated on the background cloud-sync thread (`saveIntoDb`, via `synchronize`/`periodicSync` on `Dispatchers.IO`) while the main thread modified it (opening/closing/moving windows). Changed `windowList` to a `CopyOnWriteArrayList` so iterators operate on a stable snapshot and tolerate concurrent modification.

Same crash as support tickets 3372 and 3374. Safe to close once it lands in a release.

**Comment by timbze** [comment]
I looked at the commit fix, I think it's good and will fix my support ticket 3372, but I'm not sure it actually will fix this original issue.
