### ISSUE TITLE
java.lang.IllegalStateException: Already resumed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3202]
https://support.andbible.org/scp/tickets.php?id=2453

```
Exception:
java.lang.IllegalStateException: Already resumed
at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
at net.bible.android.view.activity.base.Dialogs$showMsg2$3$1$dlgBuilder$1.onClick(Dialogs.kt:138)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6758)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912) the 
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2480 also

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2505 also

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2543

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2538
