### ISSUE TITLE
Sync crash: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService()

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3204]
https://support.andbible.org/scp/tickets.php?id=2450

```
Device info:
App id: net.bible.android.activity
Version: 5.0.802#4940254ad googleplay standard release (built 01/02/24 18:56:14)
Android version: 13
Android SDK version: 33
Manufacturer: samsung
Model: SM-T227U
Storage Mb free: 5811
WebView version: 120.0.6099.230
SQLITE version: 3.42.0
Used heap memory in Mb: 5
Max heap memory in Mb: 192

Exception:
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{80ebbaf u0 net.bible.android.activity/net.bible.service.cloudsync.SyncService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2251)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2222)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2518)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2511

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2904

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2905
