### ISSUE TITLE
Copying a a link to clipboard fails

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3214]
https://support.andbible.org/scp/tickets.php?id=2461

Screenshot includeed in report

```
Device info:
App id: net.bible.android.activity
Version: 5.0.802#4940254ad googleplay standard release (built 01/02/24 18:56:14)
Android version: 13
Android SDK version: 33
Manufacturer: Xiaomi
Model: 23129RAA4G
Storage Mb free: 148393
WebView version: 121.0.6167.144
SQLITE version: 3.42.0
Used heap memory in Mb: 21
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:570)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560)
... 1 more
Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Too many parts to the Verse. (Parts are separated by any of Bible:Gen.4.26, Bible Gen, 4, 26)
at org.crosswire.jsword.passage.AccuracyType.buildVersePartsException(AccuracyType.java:493)
at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:480)
at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:398)
at org.crosswire.jsword.passage.VerseRangeFactory.fromText(VerseRangeFactory.java:117)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:87)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:55)
at org.crosswire.jsword.passage.AbstractPassage.addVerses(AbstractPassage.java:938)
at org.crosswire.jsword.passage.RangedPassage.(RangedPassage.java:93)
at org.crosswire.jsword.passage.PassageType$4.createPassage(PassageType.java:99)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:168)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:187)
at net.bible.service.common.CommonUtils.parseAndBibleReference(CommonUtils.kt:1663)
at net.bible.service.common.CommonUtils.parseAndBibleReference(CommonUtils.kt:1674)
at net.bible.android.view.activity.page.BibleView$LinkLongPressContextMenuInfo.onContextItemSelected(BibleView.kt:1132)
at net.bible.android.view.activity.page.MainBibleActivity.onContextItemSelected(MainBibleActivity.kt:1321)
at android.app.Activity.onMenuItemSelected(Activity.java:4611)
at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:528)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
at com.android.internal.policy.PhoneWindow$PhoneWindowMenuCallback.onMenuItemSelected(PhoneWindow.java:3768)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:170)
at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1258)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1231)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3258)
at android.widget.AbsListView.onTouchUp(AbsListView.java:4280)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:4005)
at android.view.View.dispatchTouchEvent(View.java:15132)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3135)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3148)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2816)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3148)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2816)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3148)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2816)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3148)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2816)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3148)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2816)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:578)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1903)
at android.app.Dialog.dispatchTouchEvent(Dialog.java:920)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:536)
at android.view.View.dispatchPointerEvent(View.java:15407)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7182)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6952)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6368)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6425)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6391)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6556)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6399)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6613)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6372)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6425)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6391)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6399)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6372)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9581)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9531)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9499)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9738)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:298)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:341)
at android.os.Looper.loopOnce(Looper.java:169)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8445)
```

**Comment by tuomas2** [comment]
also https://support.andbible.org/scp/tickets.php?id=2462

**Comment by tuomas2** [comment]
also https://support.andbible.org/scp/tickets.php?id=2468

**Comment by tuomas2** [comment]
also https://support.andbible.org/scp/tickets.php?id=2486

Hello,
1. I had a window open on:
THE INTERNATIONAL STANDARD BIBLE ENCYCLOPEDIA
Latest version: 2.2 (2009-09-07)
Installed version: 2.2
... I was looking at the topic:
BAPTISM (NON-IMMERSIONIST VIEW)
2. I long-pressed a reference in the first section under LITERATURE
"... after the death of Jesus. There and
in 1 Corinthians (1Co 1:13; 12:13) Paul ..."
3. I chose [Copy Link to Clipboard].
4. --> app crashed.

I tested this on other references and the app crashed with any reference I tried to copy the link to the Clipboard.

It crashed whether the window was maximised or not.
A normal Press on the links does not crash and correctly opens the link.
