### ISSUE TITLE
Crashed while dragging the screen

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3218]
> reading, finger dragging on screen 

https://support.andbible.org/scp/tickets.php?id=2484

```
Device info:
App id: net.bible.android.activity
Version: 5.0.794#c119a7cc9 googleplay standard release (built 18/01/24 19:15:48)
Android version: 14
Android SDK version: 34
Manufacturer: Google
Model: Pixel 8
Storage Mb free: 89123
WebView version: 121.0.6167.164
SQLITE version: 3.42.0
Used heap memory in Mb: 23
Max heap memory in Mb: 256

Exception:
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference in method 'boolean android.view.ViewGroup.resetCancelNextUpFlag(android.view.View)'
at android.view.ViewGroup.resetCancelNextUpFlag(ViewGroup.java:2897)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
at android.app.Activity.dispatchTouchEvent(Activity.java:4403)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
at android.view.View.dispatchPointerEvent(View.java:15928)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7242)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7032)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9432)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9383)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9352)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9558)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9515)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9649)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:875)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2534
