### ISSUE TITLE
Crash when pressing mediabutton (java.lang.NullPointerException: Attempt to invoke interface method 'org.crosswire.jsword.passage.Key)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3223]
https://support.andbible.org/scp/tickets.php?id=2521

```
Exception:
java.lang.NullPointerException: Attempt to invoke interface method 'org.crosswire.jsword.passage.Key org.crosswire.jsword.book.Book.getKey(java.lang.String)' on a null object reference
at net.bible.service.sword.BookAndKeySerialized.getBookAndKey(BookAndKey.kt:48)
at net.bible.android.control.speak.SpeakControl.speakAny(SpeakControl.kt:315)
at net.bible.android.control.speak.SpeakControl.continueLastPosition(SpeakControl.kt:406)
at net.bible.service.device.speak.MediaButtonHandler$cb$1.onPlay(MediaButtonHandler.kt:90)
at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1596)
at android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:955)
at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1586)
at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1593)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by tuomas2** [comment]
Possibly fixed by #3428 99bfc410775eb44d281fa2115ca3629e0f9a6a01

will close until reported again
