### ISSUE TITLE
TTS related crash (Unable to stop service)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3226]
https://support.andbible.org/scp/tickets.php?id=2504

```
Exception:
java.lang.RuntimeException: Unable to stop service net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService@962e60f: kotlin.UninitializedPropertyAccessException: lateinit property wakeLock has not been initialized
at android.app.ActivityThread.handleStopService(ActivityThread.java:5293)
at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2452)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property wakeLock has not been initialized
at net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService.stop(TextToSpeechNotificationManager.kt:127)
at net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService.stop$default(TextToSpeechNotificationManager.kt:125)
at net.bible.service.device.speak.TextToSpeechNotificationManager$ForegroundService.onDestroy(TextToSpeechNotificationManager.kt:116)
at android.app.ActivityThread.handleStopService(ActivityThread.java:5273)
... 9 more
 
```

**Comment by tuomas2** [comment]
Related: https://github.com/AndBible/and-bible/issues/2212
