### ISSUE TITLE
Creating module backup fails due to duplicate entry

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3230]
https://support.andbible.org/scp/tickets.php?id=2493

```
Exception:
[java.util.zip](https://java.util.zip/).ZipException: duplicate entry: mods.d/emtv.conf
at [java.util.zip](https://java.util.zip/).ZipOutputStream.putNextEntry([ZipOutputStream.java:234](denied:ZipOutputStream.java:234))
at [net.bible.android](https://net.bible.android/).control.backup.BackupControl.createModulesZip$addFile(BackupControl.kt:334)
at [net.bible.android](https://net.bible.android/).control.backup.BackupControl.access$createModulesZip$addFile(BackupControl.kt:100)
at [net.bible.android](https://net.bible.android/).control.backup.BackupControl$createModulesZip$2.invokeSuspend(BackupControl.kt:371)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at [kotlinx.coroutines.DispatchedTask.run](https://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$[Worker.run](https://worker.run/)(LimitedDispatcher.kt:115)
at [kotlinx.coroutines.scheduling.TaskImpl.run](https://kotlinx.coroutines.scheduling.taskimpl.run/)(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](https://worker.run/)(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6704a8e, Dispatchers.Main.immediate]
ALM4-Vendors
```

**Comment by tuomas2** [comment]
aslo here: https://support.andbible.org/scp/tickets.php?id=2526
