### ISSUE TITLE
Search dialog fails (java.lang.NullPointerException: null cannot be cast to non-null type org.crosswire.jsword.book.basic.AbstractPassageBook)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3231]
https://support.andbible.org/scp/tickets.php?id=2490

```
Exception:
java.lang.NullPointerException: null cannot be cast to non-null type org.crosswire.jsword.book.basic.AbstractPassageBook
at net.bible.android.control.page.VersePage.getCurrentPassageBook(VersePage.kt:56)
at net.bible.android.control.page.CurrentPageManager.getCurrentPassageDocument(CurrentPageManager.kt:122)
at net.bible.android.control.search.SearchControl.getCurrentPassageDocument(SearchControl.kt:204)
at net.bible.android.control.search.SearchControl.currentDocumentContainsNonScripture(SearchControl.kt:207)
at net.bible.android.view.activity.search.searchresultsactionbar.ScriptureToggleActionBarButton.getCanShow(ScriptureToggleActionBarButton.kt:39)
at net.bible.android.view.activity.base.actionbar.QuickActionButton.update(QuickActionButton.kt:60)
at net.bible.android.view.activity.base.actionbar.QuickActionButton.addToMenu(QuickActionButton.kt:48)
at net.bible.android.view.activity.search.searchresultsactionbar.SearchResultsActionBarManager.prepareOptionsMenu(SearchResultsActionBarManager.kt:48)
at net.bible.android.view.activity.base.CustomTitlebarActivityBase.onPrepareOptionsMenu(CustomTitlebarActivityBase.kt:58)
at android.app.Activity.onPreparePanel(Activity.java:4487)
at androidx.activity.ComponentActivity.onPreparePanel(ComponentActivity.java:511)
at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:485)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:470)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:100)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3477)
at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:2054)
at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2313)
at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:281)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by tuomas2** [comment]
Also: https://support.andbible.org/scp/tickets.php?id=2561

**Comment by tuomas2** [comment]
Screenshot shows "Find in the Bible" dialog.

**Comment by tuomas2** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.search.Search}: java.lang.ClassCastException: org.crosswire.jsword.book.sword.SwordGenBook cannot be cast to org.crosswire.jsword.book.sword.SwordBook

https://support.andbible.org/scp/tickets.php?id=2816
