### ISSUE TITLE
Chinese: failing to start listen

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3249]
> When trying to listen to the Bible, an unexpected termination program pops up. At that time, two windows were opened.

```

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
at java.util.Locale.getISO3Language(Locale.java:1738)
at android.speech.tts.TextToSpeech$9.run(TextToSpeech.java:1485)
at android.speech.tts.TextToSpeech$9.run(TextToSpeech.java:1477)
at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2312)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:763)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:753)
at android.speech.tts.TextToSpeech.setLanguage(TextToSpeech.java:1477)
at net.bible.service.device.speak.TextToSpeechServiceManager.onInitListener$lambda$0(TextToSpeechServiceManager.kt:175)
at net.bible.service.device.speak.TextToSpeechServiceManager.$r8$lambda$wQLdX01ocRC4XkWAzX0g20O9vdA(TextToSpeechServiceManager.kt:0)
at net.bible.service.device.speak.TextToSpeechServiceManager$$ExternalSyntheticLambda6.onInit(R8$$SyntheticClass:0)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:835)
at android.speech.tts.TextToSpeech.access$1500(TextToSpeech.java:63)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2226)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2181)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by tuomas2** [comment]
Again: https://support.andbible.org/scp/tickets.php?id=2777

**Comment by tuomas2** [comment]
> **Chinese (Traditional)**  
Butlers, thank you for developing this program. I have identified the following issues:  
> 1. After opening the program, I selected the Chinese Union Version of the Bible.  
> 2. Upon selecting the reading function, the program automatically closes.
