### ISSUE TITLE
Crash: SQLiteConstraintException: NOT NULL constraint failed: Window.window_layout_weight

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3292]
```

App id: net.bible.android.activity
Version: 5.0.807#0dd447569 googleplay standard release (built 23/05/24 20:15:31)
Android version: 12
Android SDK version: 31
Manufacturer: incar
Model: Smooth 8GT
Storage Mb free: 1319
WebView version: 125.0.6422.165
SQLITE version: 3.42.0
Used heap memory in Mb: 7
Max heap memory in Mb: 192

Exception:
java.lang.RuntimeException: Unable to pause activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Window.window_layout_weight (code 1299)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5111)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5060)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5012)
at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7941)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Window.window_layout_weight (code 1299)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:778)
at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
at androidx.room.EntityDeletionOrUpdateAdapter.handleMultiple(EntityDeletionOrUpdateAdapter.kt:79)
at net.bible.android.database.WorkspaceDao_Impl.updateWindows(WorkspaceDao_Impl.java:1483)
at net.bible.android.control.page.window.WindowRepository.saveIntoDb(WindowRepository.kt:327)
at net.bible.android.view.activity.page.MainBibleActivity.onPause(MainBibleActivity.kt:1814)
at android.app.Activity.performPause(Activity.java:8244)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5099)
... 14 more
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2648
