### ISSUE TITLE
JsonDecodingException: Unexpected JSON token

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3311]
https://support.andbible.org/scp/tickets.php?id=2693

Device info:
App id: net.bible.android.activity
Version: 5.0.831#8cb146983 googleplay standard release (built 01/08/24 16:44:30)
Android version: 13
Android SDK version: 33
Manufacturer: revoview
Model: A55
Storage Mb free: 791
WebView version: 127.0.6533.103
SQLITE version: 3.42.0
Used heap memory in Mb: 8
Max heap memory in Mb: 128

```
Exception:
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected start of the object '{', but had 'G' instead at path: $
JSON input: Gen.1.3
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:233)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default(AbstractJsonLexer.kt:228)
at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:225)
at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:102)
at net.bible.service.sword.BookAndKeySerialized$$serializer.deserialize(BookAndKey.kt:39)
at net.bible.service.sword.BookAndKeySerialized$$serializer.deserialize(BookAndKey.kt:39)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
at net.bible.service.sword.BookAndKeySerialized$Companion.fromJSON(BookAndKey.kt:56)
at net.bible.android.control.speak.SpeakControl.speakAny(SpeakControl.kt:315)
at net.bible.android.control.speak.SpeakControl.continueLastPosition(SpeakControl.kt:406)
at net.bible.android.control.speak.SpeakControl.continueAfterPause(SpeakControl.kt:416)
at net.bible.android.control.speak.SpeakControl.continueAfterPause(SpeakControl.kt:399)
at net.bible.android.view.util.widget.SpeakTransportWidget.onButtonClick(SpeakTransportWidget.kt:133)
at net.bible.android.view.util.widget.SpeakTransportWidget.lambda$8$lambda$0(SpeakTransportWidget.kt:79)
at net.bible.android.view.util.widget.SpeakTransportWidget.$r8$lambda$XVJxXKviq162yG1NWfVwWhPmQOg(SpeakTransportWidget.kt:0)
at net.bible.android.view.util.widget.SpeakTransportWidget$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
at android.view.View.performClick(View.java:7511)
at android.view.View.performClickInternal(View.java:7484)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:29472)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:8061)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by tuomas2** [comment]
Here too https://support.andbible.org/scp/tickets.php?id=2878
