### ISSUE TITLE
IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3312]
https://support.andbible.org/scp/tickets.php?id=2691

```
Device info:
Version: 5.0.781#ad34d14fc googleplay standard release (built 06/12/23 09:46:46)
Android version: 10
Android SDK version: 29
Manufacturer: Blackview
Model: Tab8
Storage Mb free: 39885
WebView version: 127.0.6533.103
SQLITE version: 3.42.0
Used heap memory in Mb: 5
Max heap memory in Mb: 192

Exception:
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:2367)
at androidx.customview.widget.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1195)
at androidx.drawerlayout.widget.DrawerLayout.onTouchEvent(DrawerLayout.java:1621)
at android.view.View.dispatchTouchEvent(View.java:13484)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3056)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2756)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2756)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2756)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2756)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2756)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:479)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
at android.app.Activity.dispatchTouchEvent(Activity.java:4056)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:437)
at android.view.View.dispatchPointerEvent(View.java:13747)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5558)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5354)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4856)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4910)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4875)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5016)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4883)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5073)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4856)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4910)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4875)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4883)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4856)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7646)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7615)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7576)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7779)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7722)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7807)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
at android.view.Choreographer.doCallbacks(Choreographer.java:790)
at android.view.Choreographer.doFrame(Choreographer.java:718)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7626)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 
```

**Comment by tuomas2** [comment]
Actually this looks like Android / lib /etc bug, and rare case. Closing.
