### ISSUE TITLE
TTS crash: DefaultLeafKeyList cannot be cast to Verse

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3318]
https://support.andbible.org/scp/tickets.php?id=2698

```
Device info:
App id: net.bible.android.activity
Version: 5.0.831#8cb146983 googleplay standard release (built 01/08/24 16:44:30)
Android version: 14
Android SDK version: 34
Manufacturer: samsung
Model: SM-S916U1
Storage Mb free: 195823
WebView version: 128.0.6613.127
SQLITE version: 3.42.0
Used heap memory in Mb: 27
Max heap memory in Mb: 256

Exception:
java.lang.ClassCastException: org.crosswire.jsword.passage.DefaultLeafKeyList cannot be cast to org.crosswire.jsword.passage.Verse
at net.bible.android.control.speak.SpeakControl.resetPassageRepeatIfOutsideRange(SpeakControl.kt:169)
at net.bible.android.control.speak.SpeakControl.speakAny(SpeakControl.kt:239)
at net.bible.android.view.util.widget.SpeakTransportWidget.onButtonClick(SpeakTransportWidget.kt:136)
at net.bible.android.view.util.widget.SpeakTransportWidget.lambda$8$lambda$0(SpeakTransportWidget.kt:79)
at net.bible.android.view.util.widget.SpeakTransportWidget.$r8$lambda$XVJxXKviq162yG1NWfVwWhPmQOg(SpeakTransportWidget.kt:0)
at net.bible.android.view.util.widget.SpeakTransportWidget$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
at android.view.View.performClick(View.java:8047)
at android.view.View.performClickInternal(View.java:8024)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31890)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by tuomas2** [comment]
Screenshot shows that user tries to use TTS for dictionary (most likely)

![image](https://github.com/user-attachments/assets/fba23a45-2042-4530-8548-814c50e067d9)
