### ISSUE TITLE
Link that was created by AndBible caused crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3325]
https://support.andbible.org/scp/tickets.php?id=2707

The app was open and I clicked on a link I shared from the app which was a link to search results. The link opened the app again and caused it to crash.

```

Instructions:
Tell us briefly what did you do / what happened when issue took place.

For example:
  1. Opened app
  2. Clicked window menu
  -> Crash
 
Please use this function to report as soon as you have noticed issue taking place. You can also use this function after opening app, after crash has taken place.

Attachments:
  - logcat.txt.gz: Log file produced by this app. It does not contain information about any other apps.
  - screenshot.webp: Screenshot of app when crash took place, or when bug report was created.

Having these files attached helps app developers a lot in fixing the reported bug. Sometimes manually taken screenshots also are beneficial in resolving issues.

Device info:
App id: net.bible.android.activity
Version: 5.0.832#8cb146983 googleplay standard release (built 01/08/24 16:44:30)
Android version: 14
Android SDK version: 34
Manufacturer: OnePlus
Model: CPH2513
Storage Mb free: 62550
WebView version: 128.0.6613.146
SQLITE version: 3.42.0
Used heap memory in Mb: 13
Max heap memory in Mb: 384

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: org.crosswire.jsword.passage.NoSuchVerseException: Too many parts to the Verse. (Parts are separated by any of NASB:Gen.31.27, NASB Gen, 31, 27)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4031)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4181)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:257)
at android.os.Looper.loop(Looper.java:368)
at android.app.ActivityThread.main(ActivityThread.java:8839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Too many parts to the Verse. (Parts are separated by any of NASB:Gen.31.27, NASB Gen, 31, 27)
at org.crosswire.jsword.passage.AccuracyType.buildVersePartsException(AccuracyType.java:493)
at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:480)
at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:398)
at org.crosswire.jsword.passage.VerseRangeFactory.fromText(VerseRangeFactory.java:117)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:87)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:55)
at org.crosswire.jsword.passage.AbstractPassage.addVerses(AbstractPassage.java:938)
at org.crosswire.jsword.passage.RangedPassage.(RangedPassage.java:93)
at org.crosswire.jsword.passage.PassageType$4.createPassage(PassageType.java:99)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:168)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:187)
at net.bible.service.common.CommonUtils.parseAndBibleReference(CommonUtils.kt:1668)
at net.bible.android.view.activity.page.MainBibleActivity.openLink(MainBibleActivity.kt:1110)
at net.bible.android.view.activity.page.MainBibleActivity.onCreate(MainBibleActivity.kt:317)
at android.app.Activity.performCreate(Activity.java:8757)
at android.app.Activity.performCreate(Activity.java:8729)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1475)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
```

**Comment by tuomas2** [comment]
Link generation from multidoc (search results) was fixed in #3343 (1a359abaf66fd85634feece855cc93ee81a27e8b) so should not happen any more. But could make also this so that it does not crash.
