### ISSUE TITLE
NoSuchVerseException in restoring TTS

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3337]
https://support.andbible.org/scp/tickets.php?id=2751

```
Информация об устройстве:
App id: net.bible.android.activity
Version: 5.0.832#17fb150 github standard release (built 05/09/24 15:06:53)
Android version: 14
Android SDK version: 34
Manufacturer: TECNO
Model: TECNO LH7n
Storage Mb free: 32668
WebView version: 131.0.6778.22
SQLITE version: 3.42.0
Used heap memory in Mb: 6
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.HEADSET_PLUG flg=0x40000010 (has extras) } in net.bible.service.device.speak.TextToSpeechNotificationManager$headsetReceiver$1@b1de424
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1837)
at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:243)
at android.os.Looper.loop(Looper.java:338)
at android.app.ActivityThread.main(ActivityThread.java:8446)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1064)
Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Глава должна быть между 0 и 12 для Даниил (given 13).
at org.crosswire.jsword.versification.Versification.validate(Versification.java:1087)
at org.crosswire.jsword.versification.Versification.validate(Versification.java:1037)
at org.crosswire.jsword.passage.VerseRangeFactory.fromText(VerseRangeFactory.java:119)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:87)
at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:55)
at org.crosswire.jsword.passage.AbstractPassage.addVerses(AbstractPassage.java:938)
at org.crosswire.jsword.passage.RangedPassage.(RangedPassage.java:93)
at org.crosswire.jsword.passage.PassageType$4.createPassage(PassageType.java:99)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:168)
at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:187)
at org.crosswire.jsword.book.basic.AbstractPassageBook.getKey(AbstractPassageBook.java:220)
at net.bible.service.device.speak.BibleSpeakTextProvider.osisIdToVerse(BibleSpeakTextProvider.kt:531)
at net.bible.service.device.speak.BibleSpeakTextProvider.restoreState(BibleSpeakTextProvider.kt:522)
at net.bible.service.device.speak.TextToSpeechServiceManager.restorePauseState(TextToSpeechServiceManager.kt:674)
at net.bible.service.device.speak.TextToSpeechServiceManager.(TextToSpeechServiceManager.kt:135)
at net.bible.service.device.speak.TextToSpeechServiceManager_Factory.newInstance(TextToSpeechServiceManager_Factory.java:62)
at net.bible.service.device.speak.TextToSpeechServiceManager_Factory.get(TextToSpeechServiceManager_Factory.java:49)
at net.bible.service.device.speak.TextToSpeechServiceManager_Factory.get(TextToSpeechServiceManager_Factory.java:14)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at dagger.internal.Providers$1.get(Providers.java:29)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at net.bible.android.control.speak.SpeakControl.getTtsServiceManager(SpeakControl.kt:83)
at net.bible.android.control.speak.SpeakControl.isPaused(SpeakControl.kt:112)
at net.bible.service.device.speak.TextToSpeechNotificationManager$headsetReceiver$1.onReceive(TextToSpeechNotificationManager.kt:175)
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1829)
... 10 more
 
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2767
