### ISSUE TITLE
java.lang.IllegalStateException: Cannot perform this action on a sealed instance.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#334]
```
FATAL EXCEPTION: main
Process: net.bible.android.activity, PID: 26859
java.lang.IllegalStateException: Cannot perform this action on a sealed instance.
	at android.view.accessibility.AccessibilityNodeInfo.enforceNotSealed(AccessibilityNodeInfo.java:2992)
	at android.view.accessibility.AccessibilityNodeInfo.setSource(AccessibilityNodeInfo.java:818)
	at android.view.accessibility.AccessibilityNodeInfo.setSource(AccessibilityNodeInfo.java:795)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:3008)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:7897)
	at android.view.View.createAccessibilityNodeInfo(View.java:7883)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1051)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:876)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:199)
	at android.view.AccessibilityInteractionController.-wrap1(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1225)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by tuomas2** [comment]
https://play.google.com/apps/publish/?account=6727655833913220393#PreLaunchReportPlace:p=net.bible.android.activity&plrvc=305&plrtab=CRASH

**Comment by tuomas2** [comment]
@bvahedy can you check the video from pre-launch report. I think this is some very rare case and I can't figure out how to reproduce. From stack trace it looks like it would be related to some accessibility features. The crash occurs when user presses "New window" button on right-bottom corner.

**Comment by bvahedy** [comment]
Without knowing what accessiblity settings this user has it would be hard to reproduce this. I tried but could not cause this crash.

**Comment by tuomas2** [comment]
Haven't seen this any more, closing
