### ISSUE TITLE
Crash: lateinit property documentItemAdapter has not been initialized

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3346]
Related: #3150 

https://support.andbible.org/scp/tickets.php?id=2778

```

12-06 12:43:19.539 25700 25700 E BibleApplication: App crashed due to exception
12-06 12:43:19.539 25700 25700 E BibleApplication: kotlin.UninitializedPropertyAccessException: lateinit property documentItemAdapter has not been initialized
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at net.bible.android.view.activity.base.DocumentSelectionBase.getDocumentItemAdapter(DocumentSelectionBase.kt:123)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at net.bible.android.view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invokeSuspend(DocumentSelectionBase.kt:385)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at android.os.Handler.handleCallback(Handler.java:1013)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at android.os.Handler.dispatchMessage(Handler.java:101)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at android.os.Looper.loopOnce(Looper.java:226)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at android.os.Looper.loop(Looper.java:328)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at android.app.ActivityThread.main(ActivityThread.java:9237)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
12-06 12:43:19.539 25700 25700 E BibleApplication: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@16d020b, Dispatchers.Main.immediate]
12-06 12:43:19.539 25700 25700 I ErrorReportControl: Trying to save logcat
12-06 12:43:19.539 25700 25700 I ErrorReportControl: logBasicInfo
12-06 12:43:19.539 25700 25700 I ErrorReportControl: OS:Linux ver 5.10.198-android12-9-00090-gf7559871b50a-ab11383503
12-06 12:43:19.539 25700 25700 I ErrorReportControl: Java:The Android Project ver 0
12-06 12:43:19.539 25700 25700 I ErrorReportControl: Java home:/apex/com.android.art
12-06 12:43:19.539 25700 25700 I ErrorReportControl: User dir:/ Timezone:null
12-06 12:43:19.541 25700 25700 I CommonUtils: Free space :103261925376
12-06 12:43:19.541 25700 25700 I CommonUtils: Megs available on internal memory :98478
12-06 12:43:19.542 25700 25700 I ErrorReportControl: App id: net.bible.android.activity
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Version: 5.0.833#9f1ca3cdb fdroid standard release (built 30/11/24 14:58:59)
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Android version: 14
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Android SDK version: 34
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Manufacturer: vivo
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Model: V2333
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Storage Mb free: 98478
12-06 12:43:19.542 25700 25700 I ErrorReportControl: WebView version: 131.0.6778.39
12-06 12:43:19.542 25700 25700 I ErrorReportControl: SQLITE version: 3.42.0
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Used heap memory in Mb: 8
12-06 12:43:19.542 25700 25700 I ErrorReportControl: Max heap memory in Mb: 256

```

**Comment by tuomas2** [comment]
Checked code and can't really find a reason why this happened.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2812

> when I opened the Download Documents option in the hamburger menu, the list of documents fail to load, I hope you can fix this issue.

```

kotlin.UninitializedPropertyAccessException: lateinit property documentItemAdapter has not been initialized
at net.bible.android.view.activity.base.DocumentSelectionBase.getDocumentItemAdapter(DocumentSelectionBase.kt:123)
at net.bible.android.view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invokeSuspend(DocumentSelectionBase.kt:385)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:255)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@449978d, Dispatchers.Main.immediate]
 
```

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2841

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2841 
user says:
> I tried opening it the next day and was able to set it up in the easy mode (the same way I tried previously).
