### ISSUE TITLE
Crash in startup: NoSuchVerseException: Too many parts to the Verse

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3347]
https://support.andbible.org/scp/tickets.php?id=2774

Related: #3294 #3256 #3214

```
Device info:
App id: net.bible.android.activity
Version: 5.0.832#8cb146983 googleplay standard release (built 01/08/24 16:44:30)
Android version: 14
Android SDK version: 34
Manufacturer: samsung
Model: SM-A346E
Storage Mb free: 130343
WebView version: 130.0.6723.108
SQLITE version: 3.42.0
Used heap memory in Mb: 9
Max heap memory in Mb: 256

Exception:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: org.crosswire.jsword.passage.NoSuchVerseException: Too many parts to the Verse. (Parts are separated by any of 2Macc.10.38, 2 Macc, 10, 38)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Too many parts to the Verse. (Parts are separated by any of 2Macc.10.38, 2 Macc, 10, 38)
```

**Comment by tuomas2** [comment]
here too https://support.andbible.org/scp/tickets.php?id=2797

**Comment by tuomas2** [comment]
> Amazon Tablet HD 10(11th Generation, Modified - Nova Launcher)
> 1.Opened app in Galatians 3
> 2. Selected Definition & Morphology for "bewitched" in Galatians 3:1. 
> 3. Note with text for the verse is open in top pane
> 4. Long pressed the Strong's number 
> -> selected 'copy link to clipboard ' trigging the crash

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2818

**Comment by tuomas2** [comment]
Fixed
