### ISSUE TITLE
Reading plan crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#491]
![Selection_119](https://user-images.githubusercontent.com/5811789/71745199-1e6f9500-2e72-11ea-981f-a5a56433c3fd.png)

https://play.google.com/apps/publish/?account=6727655833913220393#AndroidMetricsErrorsPlace:p=net.bible.android.activity&appid=4974350217168681006&appVersion=333&clusterName=apps/net.bible.android.activity/clusters/9630e110&detailsAppVersion=333&detailsSpan=7

**Comment by bvahedy** [comment]
How do you reproduce this?

**Comment by tuomas2** [comment]
I don't know yet. Reported by Google Play.

**Comment by tuomas2** [comment]
I'll investigate stack trace. (or @timbze can do it too)

**Comment by timbze** [comment]
From stack trace it looks like crash happened when manually setting reading
plan start date from top right menu but I wasn't able to reproduce yet.

**Comment by timbze** [comment]
Did a little more investigation. I cannot find that the affected table has any constraints, so this error seems strange.

We could change this line to CONFLICT_IGNORE instead of CONFLICT_FAIL to prevent the same error but that wouldn't get to the root of the issue.
https://github.com/AndBible/and-bible/blob/e5fdfb41a5eb9609c4b400d2da6cc032767e81b1/app/src/main/java/net/bible/service/db/readingplan/ReadingPlanDbAdapter.kt#L102

**Comment by timbze** [comment]
Did a new install on another device (android 7.1) and the issue comes up right away.

There is a not null constraint exception for column plan_current_day of readingplan table. Which shouldn't be because that column should have a default value of 1.

```
2020-01-06 09:23:06.032 5343-5343/net.bible.android.activity E/ReadingPlanList: Plan selection error
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: readingplan.plan_current_day (code 1299)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:798)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1509)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.insert(FrameworkSQLiteDatabase.java:188)
        at net.bible.service.db.readingplan.ReadingPlanDbAdapter.setReadingStartDate(ReadingPlanDbAdapter.kt:102)
        at net.bible.service.readingplan.ReadingPlanInfoDto.startOn(ReadingPlanInfoDto.kt:63)
        at net.bible.service.readingplan.ReadingPlanInfoDto.start(ReadingPlanInfoDto.kt:52)
        at net.bible.android.control.readingplan.ReadingPlanControl.startReadingPlan(ReadingPlanControl.kt:143)
        at net.bible.android.view.activity.readingplan.ReadingPlanSelectorList.onListItemClick(ReadingPlanSelectorList.kt:82)
        at net.bible.android.view.activity.base.ListActivityBase$2.onItemClick(ListActivityBase.java:210)
        at android.widget.AdapterView.performItemClick(AdapterView.java:315)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1210)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3330)
        at android.widget.AbsListView$4.run(AbsListView.java:4391)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6337)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

**Comment by tuomas2** [comment]
Looks like a bug in Room, which is responsible of creating initial database.

In autogenerated AppDatabase_Impl.java:

`CREATE TABLE IF NOT EXISTS `readingplan` (`_id` INTEGER, `plan_code` TEXT NOT NULL, `plan_start_date` INTEGER NOT NULL, `plan_current_day` INTEGER NOT NULL, PRIMARY KEY(`_id`))"`

**Comment by tuomas2** [comment]
So not a bug in Room, but bug in our migrations. It is documented feature that default values used in entities do not reflect to database default values, but need to be specified manually, if needed (though not needed if all operations are done via Room entities).

**Comment by timbze** [comment]
Fix verified in 335. Thank you Tuomas
