### ISSUE TITLE
Archive is not a ZIP file

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#527]
There are some errors in error mailbox.

```
And Bible version: 3.2.334#926a4127 (built 06/01/20 21:41:23)
Android version: 9
Android SDK version: 28
Manufacturer: samsung
Model: SM-F900U

SD card Mb free: 445556

Used heap memory in Mb: 28
Max heap memory in Mb: 512

Exception:
java.util.zip.ZipException: archive is not a ZIP archive
at org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:871)
at org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:801)
at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:542)
at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:217)
at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:193)
at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:154)
at org.crosswire.common.util.IOUtil.unpackZip(IOUtil.java:84)
at org.crosswire.jsword.book.install.sword.AbstractSwordInstaller.install(AbstractSwordInstaller.java:254)
at net.bible.service.download.DownloadManager.installBook(DownloadManager.java:129)
at net.bible.service.download.RepoBase.downloadDocument(RepoBase.java:62)
at net.bible.android.control.download.DownloadQueue$1.run(DownloadQueue.java:70)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

Sent via the Samsung Galaxy Fold, an AT&T 5G Evolution capable smartphone
Get Outlook for Android
```

**Comment by ildar** [comment]
why bother? sounds like a trivial human error.

**Comment by tuomas2** [comment]
This is not coming from "install module from zip file" which is displaying proper error message. The file downloaded from Crosswire repository seems to be corrupt.

User should be given proper error message and perhaps instructions to inform us / crosswire about the issue.

**Comment by tuomas2** [comment]
Example:

Try to download "Brenton English Septuagint".
 -> "Error occurred"

Stack trace from logcat: 
```
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: archive is not a ZIP archive [::0] Thread[pool-2-thread-1,5,main]
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: java.util.zip.ZipException: archive is not a ZIP archive
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:871)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:801)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:542)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:217)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:193)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:154)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.crosswire.common.util.IOUtil.unpackZip(IOUtil.java:84)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at org.crosswire.jsword.book.install.sword.AbstractSwordInstaller.install(AbstractSwordInstaller.java:254)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at net.bible.service.download.DownloadManager.installBook(DownloadManager.java:129)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at net.bible.service.download.RepoBase.downloadDocument(RepoBase.java:62)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at net.bible.android.control.download.DownloadQueue$1.run(DownloadQueue.java:70)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-21 09:39:10.795 10741  4559 W Slf4jAndroidLogger: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by tuomas2** [comment]
Sometimes it seems when "Report error" button is pressed, message will be empty (should contain error report with stack trace).

**Comment by tuomas2** [comment]
This has been improved in current beta.
