### ISSUE TITLE
Backup to phone storage does not work on android 10

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#636]
**Describe the bug**
When saving the application database to the sdcard "an error occurs".

**Bug was found on And Bible version**
2e5a3e5b9fee911498faba95623c5a170d17c48d

**To Reproduce**
Go to Administration > Backup & Restore > Backup application database to... > Phone storage

**Expected behavior**
File is saved to SD card

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android
 - Version 10.3.3

**Additional context**
While debugging I found that the problem is that `toDir.mkdir()` returns false, indicating that the directory could not be created. This results in an error on the directory path, because it does not exist. (`java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0/andbible_backup`)

According to [this QA](https://stackoverflow.com/questions/56821095/android-q-file-mkdirs-returns-false) writing to an arbitrary location on external storage is no longer possible on Android 10.

I think the best course of action is to remove the save to phone storage option since the share option can be used to make another application do the work, plus the user knows in which location it is saved.

**Comment by timbze** [comment]
I think we need to use something like Intent(Intent.ACTION_GET_CONTENT). This allows user to pick location to save file and I assume that will still work in Android 10.

This "backup to phone" feature was removed some time ago but recently put back in, see #600

**Comment by bvahedy** [comment]
I like to keep this feature as it requires no internet connection to save
your database and it also takes less time to restore the database back.

**Comment by tuomas2** [comment]
If it's causing error in android 10 then it will be disabled for android 10+.

But if someone would like to investigate better options to "share" that allows user to select folder from local storage, it would be best. I know there is / are some app(s) that can do it as "share" target, but is there anything better?

**Comment by tuomas2** [comment]
@JJK96 More informative would be if there would be something like "Bug was found on And Bible version 2e5a3e5 (366+)" instead of plain git hash.

**Comment by tuomas2** [comment]
@JJK96 Tested with Android 10 emulator and it works. QA says that it does not work any more with Android 11.

**Comment by JJK96** [comment]
I just tested again, for me it does not work, are you sure that you had not already created the `andbible_backup` directory in the emulator?

**Comment by tuomas2** [comment]
Tried again, removed folder and re-created backup and it looks fine.

**Comment by JJK96** [comment]
After creating the folder manually on my device:

```
E/net.bible.service.common.FileManager: Error moving file
    java.io.FileNotFoundException: /storage/emulated/0/andbible_backup/andBibleDatabase.db: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at net.bible.service.common.FileManager.copyFile(FileManager.kt:73)
        at net.bible.service.common.FileManager.copyFile(FileManager.kt:50)
        at net.bible.android.control.backup.BackupControl.backupDatabase(BackupControl.kt:85)
        at net.bible.android.view.activity.page.MenuCommandHandler$handleMenuRequest$1$1.onClick(MenuCommandHandler.kt:223)
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7581)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235) 
        at net.bible.service.common.FileManager.copyFile(FileManager.kt:73) 
        at net.bible.service.common.FileManager.copyFile(FileManager.kt:50) 
        at net.bible.android.control.backup.BackupControl.backupDatabase(BackupControl.kt:85) 
        at net.bible.android.view.activity.page.MenuCommandHandler$handleMenuRequest$1$1.onClick(MenuCommandHandler.kt:223) 
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
E/BackupControl: Error copying database to internal memory
```

**Comment by tuomas2** [comment]
Will be fixed in build 384
