### ISSUE TITLE
Error displayed after download sync or auto-sync in Downloads screen

### ISSUE THREAD

**Issue by mjdenham** [AndBible/and-bible#93]
This is a commonly reported error with no apparent side affects which I just caught because I could not reproduce it.   However, I have finally reproduced it.  The error is caused by a prior ClosedByInterruptException during FileChannel.transferFrom when moving the downloaded font.properties file.  However it seems unrelated to the font.properties download.  I suspect that when any error occurs fetching a repo's book list Android then attempts to interrupt the thread and the first interruptible command is transferFrom.

I have attempted the simple fix of replacing transferFrom with a simple file copy loop.

Error:
java.lang.Exception: Jsword Exception
at net.bible.service.sword.SwordEnvironmentInitialisation$1.showMsg(SwordEnvironmentInitialisation.java:115)
at net.bible.service.sword.SwordEnvironmentInitialisation$1.reportMessage(SwordEnvironmentInitialisation.java:96)
at org.crosswire.common.util.Reporter.fireCapture(Reporter.java:176)
at org.crosswire.common.util.Reporter.informUser(Reporter.java:139)
at net.bible.service.download.GenericFileDownloader.downloadFile(GenericFileDownloader.java:99)
at net.bible.service.font.FontControl.checkFontPropertiesFile(FontControl.java:150)
at net.bible.android.control.download.DownloadControl.getDownloadableDocuments(DownloadControl.java:116)
at net.bible.android.view.activity.download.Download.getDocumentsFromSource(Download.java:118)
at net.bible.android.view.activity.base.DocumentSelectionBase$4.doInBackground(DocumentSelectionBase.java:255)
at net.bible.android.view.activity.base.DocumentSelectionBase$4.doInBackground(DocumentSelectionBase.java:241)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by mjdenham** [comment]
This has been released in 2.9.2.  I need to wait a couple of weeks to see if these errors are still being reported.

**Comment by tuomas2** [comment]
As couple weeks have passed, I'll close this ticket now :)
