### ISSUE TITLE
App startup crash (workspace related)

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#966]
https://support.andbible.org/scp/tickets.php?id=424

**Describe the bug**
App crashed once on startup. Seems to be workspace related (according to log).

**To Reproduce**
1. Opened app
2. No 2. I never got that far. It crashed.

**Device info:**
And Bible version: 3.3.399#24411f9 (built 05/11/20 10:40:43)
Android version: 9
Android SDK version: 28
Manufacturer: LGE
Model: LG-H870DS

**Log lines related to crash:**
```
03-27 09:12:38.388 13421 13421 E AndroidRuntime: FATAL EXCEPTION: main
03-27 09:12:38.388 13421 13421 E AndroidRuntime: Process: net.bible.android.activity, PID: 13421
03-27 09:12:38.388 13421 13421 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.workspaces.WorkspaceSelectorActivity}: java.lang.NullPointerException
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3021)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:205)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6991)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: Caused by: java.lang.NullPointerException
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at net.bible.android.view.activity.workspaces.WorkspaceSelectorActivity.onCreate(WorkspaceSelectorActivity.kt:194)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7159)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7150)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
03-27 09:12:38.388 13421 13421 E AndroidRuntime: 	... 11 more
```

**Comment by timbze** [comment]
Another similar crash: https://support.andbible.org/scp/tickets.php?id=444

**Comment by timbze** [comment]
Play store log: https://play.google.com/console/u/0/developers/6727655833913220393/app/4974350217168681006/vitals/crashes/27a631ad/details

Not happening that often, but still has 15 occurrences in last 30 days

**Comment by tuomas2** [comment]
I believe this has been fixed in latest beta. Similar to DatabaseNotReady.
