### ISSUE TITLE
App crash on clicking word with Strongs underline turned on

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#998]
https://support.andbible.org/scp/tickets.php?id=476

**Describe the bug**
When clicking a word ( with Strongs underline turned on ) app crashes.

**Bug was found on And Bible version**
Build 514-beta

**Relevant log:**
```
04-26 23:25:23.305 10642 10642 D LinkControl: Loading: osis:και
04-26 23:25:23.310 10642 10743 D BibleView[32] JSInt: Selection cleared!
04-26 23:25:23.316 10642 10642 D AndroidRuntime: Shutting down VM
04-26 23:25:23.318 10642 10642 E AndroidRuntime: FATAL EXCEPTION: main
04-26 23:25:23.318 10642 10642 E AndroidRuntime: Process: net.bible.android.activity, PID: 10642
04-26 23:25:23.318 10642 10642 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	... 1 more
04-26 23:25:23.318 10642 10642 E AndroidRuntime: Caused by: org.crosswire.jsword.passage.NoSuchVerseException: Cannot understand και as a chapter or verse.
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.parseInt(AccuracyType.java:527)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.checkValidChapterOrVerse(AccuracyType.java:506)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:436)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.AccuracyType.fromText(AccuracyType.java:398)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.VerseRangeFactory.fromText(VerseRangeFactory.java:117)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:87)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.VerseRangeFactory.fromString(VerseRangeFactory.java:55)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.AbstractPassage.addVerses(AbstractPassage.java:938)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.RangedPassage.<init>(RangedPassage.java:93)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.PassageType$4.createPassage(PassageType.java:99)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:168)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.crosswire.jsword.passage.PassageKeyFactory.getKey(PassageKeyFactory.java:187)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.getBibleKey(LinkControl.kt:169)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.getBookAndKey(LinkControl.kt:101)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at net.bible.android.control.link.LinkControl.openMulti(LinkControl.kt:76)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView.openLink(BibleView.kt:616)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at net.bible.android.view.activity.page.BibleView$BibleViewClient.shouldOverrideUrlLoading(BibleView.kt:682)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-443008223:14)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:326)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:181)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7050)
04-26 23:25:23.318 10642 10642 E AndroidRuntime: 	... 3 more
04-26 23:25:25.281 10642 10682 D SplitBibleArea: toggleWindowButtonVisibility

```

**Comment by bvahedy** [comment]
I'm trying to see if I can duplicate this but want to know what you mean by strong's underlined turned on. When I tap on a strong's number it goes to the dictionary.

**Comment by tuomas2** [comment]
Strongs underlined turned on:![image](https://user-images.githubusercontent.com/5811789/116570895-47435580-a913-11eb-90b6-a70efa0df92f.png)![image](https://user-images.githubusercontent.com/5811789/116570895-47435580-a913-11eb-90b6-a70efa0df92f.png)
